### ISSUE TITLE
Can't save the cropped image

### ISSUE THREAD

**Issue by hgelb** [ArthurHub/Android-Image-Cropper#101]
Hi

After cutting the image, how can I save this image?

Thanks,
Hadas

**Comment by faizsameerahmed96** [comment]
Even I am getting this problem...

**Comment by altaf2892** [comment]
@faizsameerahmed96 @hgelb paste your code

**Comment by hgelb** [comment]
@altaf2892 it's according to your code (Android-Image-Cropper)

**Comment by altaf2892** [comment]
@hgelb i m able to save so it will be more specific if u show your implementation.

**Comment by hgelb** [comment]
@altaf2892 I downloaded your code, but I didn't see how can I save the cropped image. can you please share me an example code for this issue please? or to direct me to the relevant class?

**Comment by hgelb** [comment]
@altaf2892 please see in CropImage.startPickImageActivity method. how can I get the cropped image and save it to gallery layout (in this activity, like in the camera)?

**Comment by ArthurHub** [comment]
I don't know what do you mean by "save" so..

1. Picking image from camera/gallery doesn't "save" it anywhere, it makes it available for the code to do whatever you want.
2. Saving an image "Gallery" is not related to the functionality of this library, never had to do it so you will have to google it as I would have to.

thx @altaf2892 for trying to help.

**Comment by shailesh-matariya** [comment]
@hgelb as @ArthurHub said not functionality ..but to get cropped image u can use getCroppedImage() method and can save it wherever u want(google how to create folder ans save image to it)

**Comment by altaf2892** [comment]
@hgelb as @ArthurHub said not functionality ..but to get cropped image u can use getCroppedImage() method and can save it wherever u want(google how to create folder and save image to it)
