### ISSUE TITLE
setBackgroundColor with transparent,but it don't work

### ISSUE THREAD

**Issue by usedlie** [ArthurHub/Android-Image-Cropper#104]
here is code:
` cropImageView.setBackgroundColor(getResources().getColor(R.color.transparent));`

here is my "transparent" :)
` <color name="transparent">#00ffffff</color>`

well,i try to change the value,for example,#70ffffff,it work,but,when the transparency too low,for example,#20ffffff,it don't work totally,it may use the default backgroudColor i guess.

or may there is a api :isShowOverlayBackground(),or sth like that that i not found??

i don't know if i explain well,but since you guy speak English,so i guess you know what i talk about;
hope everything fine,thankyou

**Comment by ArthurHub** [comment]
see [Visual Customization](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Visual-Customization)

**Comment by usedlie** [comment]
BackgroundColor

Default: #77000000
The color of the crop overlay outside of crop window area, covering parts of the cropping image outside of the crop window.
Make sure the background has some transparency so the cropping image will be visible.

-------
actually,i have read  Visual Customization several times before(just mean i am not that kind of always ask autho whithout reading your introduction)..

i want to let The color of the crop overlay outside of crop window area,to be transparent at all~~~~
that is why i set setBackgroundColor(R.transparent).
but it dosen't work..
but if i set setBackgroundColor(R.black),it work.

so what's happened.. :)
------
happy weekend

**Comment by ArthurHub** [comment]
It was a poor choice of naming, didn't think it will be so confusing.
`cropImageView.setBackgroundColor` is Android method that affects the background color of the widget.
you need to change the overlay using custom attribute on the xml:
```xml
<com.theartofdev.edmodo.cropper.CropImageView
  xmlns:custom="http://schemas.android.com/apk/res-auto"
  android:id="@+id/cropImageView"
  android:layout_width="match_parent"
  android:layout_height="0dp"
  android:layout_weight="1"
  custom:cropBackgroundColor="#77000000"/>
```

**Comment by usedlie** [comment]
wow,it(using custom attribute on the xml:) really work!thank you..
Orz...it took me 4 hours yesterday
you reply so quick,make me surprise~~
you are a responsible man!nice~~god bless you
