### ISSUE TITLE
Changing aspect ratio properties via buttons doesn't work

### ISSUE THREAD

**Issue by Theonewithideas** [ArthurHub/Android-Image-Cropper#105]
Changing the aspect ratio values, and setting it to "fixed" works, but only when outside of the button methods, like:

![screenshot from 2016-06-24 11 31 32](https://cloud.githubusercontent.com/assets/6058082/16334076/3638b89e-39ff-11e6-8936-f038945f431a.png)

But when I try to use it from the "onClick" function of a Button, it doesn't work:

![screenshot from 2016-06-24 11 30 31](https://cloud.githubusercontent.com/assets/6058082/16334063/1c2cf208-39ff-11e6-90d5-2478a9d9a5ef.png)

It resets to the default bounds, and doesn't set the ratio to "fixed".

**Comment by ArthurHub** [comment]
It works in the sample app where you can change the aspect ratio from the drawer.
Try to see what you do differently.
Also note that in your `action_static` you should also set fixed aspect ratio to true.

**Comment by Theonewithideas** [comment]
I realized that I didn't use `break` after each case, and so it wrongfully executed all of the code.
It works now, thanks for the support!
