### ISSUE TITLE
Scale/Move the original picture instead of cropper?

### ISSUE THREAD

**Issue by eewwxac** [ArthurHub/Android-Image-Cropper#11]
Awesome library. I have an extra question:

Is there a way to scale&move the original picture instead of the cropper?

**Comment by ArthurHub** [comment]
Not sure I understand what you mean, can you explain the use case

**Comment by eewwxac** [comment]
So we try to mimic the facebook profile picture cropping function -- 
The cropper window stays in the middle, and the user has to zoom/move the picture to fit into the cropping window.

**Comment by ArthurHub** [comment]
Oh... sorry, the way it works now is basically 90% of the library so to creating the iPhone style cropping you need to rewrite almost all of it.

**Comment by eewwxac** [comment]
Thanks all the same!
