### ISSUE TITLE
Transparency on PNG

### ISSUE THREAD

**Issue by anandvenkatanarayanan** [ArthurHub/Android-Image-Cropper#111]
I am just using the following image in the gallery for generating a crop image. Since the image contains
transparency, it render a black image on the Image view. Is there a way in which I can force the cropper activity to always store it in the PNG format? 
![logo-apollo](https://cloud.githubusercontent.com/assets/6889702/16409642/3b6a46da-3d3c-11e6-80e7-56657b139449.png)

I can see that the image is handled transparently during the cropping activity but it is just stored as JPG (which does not support transparency) because the media store gallery app always says the Mime type as JPG. 

![cropped-145939481](https://cloud.githubusercontent.com/assets/6889702/16409689/766f30ce-3d3c-11e6-98f1-1d8976ba5ad8.jpg)

**Comment by ArthurHub** [comment]
Yes, use `.setOutputCompressFormat(Bitmap.CompressFormat.PNG)`

**Comment by anandvenkatanarayanan** [comment]
That solves my issue. Thanks for the prompt response.May be you should add it to the FAQ since the gallery app not handling transparency as it always returns mime type as JPEG is a frequent irritant.
