### ISSUE TITLE
 Wrong cropzone for portrait photo

### ISSUE THREAD

**Issue by TigranSarkisian** [ArthurHub/Android-Image-Cropper#112]
Device Sumsung Galaxy s6
Android 6.0.1

When taking portrait photo  cropper set wrong cropzone
http://prntscr.com/bmh4vc
http://prntscr.com/bmh51x

when taking landscape photo it set correct cropzone 
http://prntscr.com/bmh5gc
http://prntscr.com/bmh5ke

only on SUMSUNG

**Comment by ArthurHub** [comment]
what's the problem?

**Comment by TigranSarkisian** [comment]
The problem is that cropper set wrong cropzone - http://prnt.sc/bmh51x

**Comment by ArthurHub** [comment]
Why is it wrong?
what is the expected initial crop window?

**Comment by TigranSarkisian** [comment]
by default (and on other devices except sumsung) it set portrait rectangle while photo was main in portrait mode - look red line http://prntscr.com/bmicj5

**Comment by TigranSarkisian** [comment]
here is two small videos 
correct behaviour - https://goo.gl/py014y
sumsung  behaviour -https://goo.gl/ASQXRJ

**Comment by ArthurHub** [comment]
k, I think I know where the issue might be, will verify.
thx.

**Comment by TigranSarkisian** [comment]
Is there any quick fix which i can implement?

**Comment by ArthurHub** [comment]
fixed in 2.2.5
