### ISSUE TITLE
Action Bar not shown after images is selected from gallery or camera

### ISSUE THREAD

**Issue by alirazazulfi** [ArthurHub/Android-Image-Cropper#113]
Hi.
i m using "Pick image for cropping from Camera or Gallery"
i used the same code that you have written in the 
https://github.com/ArthurHub/Android-Image-Cropper/wiki/Pick-image-for-cropping-from-Camera-or-Gallery

but i m unable to see the Action bar when image is selected and open for cropping.
because of that i m unable to select the cropped image.

One more thing i cannot set the aspect ratio by this code
CropImage.activity(imageUri)
                .setGuidelines(CropImageView.Guidelines.ON)
                .setAllowRotation(true)
                .setActivityTitle("")
                .setAspectRatio(1, 1)
                .setFixAspectRatio(true)
                .start(this);

in Manifist i m using 
 <activity
            android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
            android:theme="@style/Base.Theme.AppCompat" />

and in build gradle i m using 
    compile 'com.theartofdev.edmodo:android-image-cropper:2.2.+'

Please help

**Comment by ArthurHub** [comment]
Attached test app, everything works in my test, see if it works for you and what is the difference with your code.
[TestCropActivity.zip](https://github.com/ArthurHub/Android-Image-Cropper/files/341125/TestCropActivity.zip)

**Comment by alirazazulfi** [comment]
thank you for your response .... that was solved before your reply... i just completely uninstalled the application from my mobile and then started the project ... and it was working
