### ISSUE TITLE
Blur Image after Cropping

### ISSUE THREAD

**Issue by alirazazulfi** [ArthurHub/Android-Image-Cropper#115]
Hello again
I have already sent you my code in my previous Issue
I select file from gallery or camera and then i crop the image and i m getting the blur image 
Please help

**Comment by ArthurHub** [comment]
can you upload example image

**Comment by alirazazulfi** [comment]
the one i m using to upload as my profile image?

**Comment by ArthurHub** [comment]
it's not only about a specific image, I need to understand what are you doing and what is the result compared to the expected result.

**Comment by alirazazulfi** [comment]
ahhhh i got the issue.... i wasn using small size of result image.... i m saving result in different sizes and i m using the wrong size in view 
thanks for your time
