### ISSUE TITLE
Change "CROP" label

### ISSUE THREAD

**Issue by Coletz** [ArthurHub/Android-Image-Cropper#116]
Is it possible to change the "CROP" label for the crop activity? That would be awesome. If that's already possible I can't find how to do that. Thanks!

**Comment by ArthurHub** [comment]
Yes, https://github.com/ArthurHub/Android-Image-Cropper/wiki/Activity-Visual-Customization

**Comment by Coletz** [comment]
Thanks for the fast answer! And also for this awesome library, that's amazing
