### ISSUE TITLE
zoom, panning image 

### ISSUE THREAD

**Issue by kuoliangkwong** [ArthurHub/Android-Image-Cropper#117]
Hi does the library have feature zooming and panning the image? I would like to have a fixed and non-moving crop frame with zooming and panning on image.

Thanks and look forward to your reply.

**Comment by ArthurHub** [comment]
See [uCrop](https://github.com/Yalantis/uCrop) library.

**Comment by kuoliangkwong** [comment]
I tried uCrop and it seems like it has some issue when using its CropImageView. It doesn't allow zoom in and overlayview not showing with just transparent black bg. Not sure what happen. Been spending hours try to solve it, but it seems alot of effort just to fix something i never change. Are you goin to have zooming and panning image feature any time soon in the future? I really prefer your library on its simplicity, and most importantly, it's working like magic.

**Comment by ArthurHub** [comment]
The is auto zoom feature and support for rotation.
But there is no plan to provide UX similar to uCrop, as i understand this
is the UX you want.

**Comment by kuoliangkwong** [comment]
I managed to get uCrop work now. Thanks alot for your help. Really appreciate it ; )
