### ISSUE TITLE
Crash when restoring view state

### ISSUE THREAD

**Issue by sethgho** [ArthurHub/Android-Image-Cropper#12]
Genymotion Android 5.0 emulator

Launch the sample app an rotate or app switch. A crash occurs:

```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@d10b73c
```

The same crash manifests on 4.1.1, 4.3, 4.4.2, and 5.1 *only* on rotation.

**Comment by ArthurHub** [comment]
thx
