### ISSUE TITLE
CV facial detection

### ISSUE THREAD

**Issue by jjhesk** [ArthurHub/Android-Image-Cropper#122]
I have a library that does facial detection calculation. So I am trying to integrate that into this library. Question. Are there anyways that I can programmatically setting the four points of location from the detection rectangle and that will fit into the bitmap portion of the selected crop image?

desired to see
`plot_detection_vert(x1,y1,x2,y2,x3,y3,x4,y4);`
four points fits as a rectangle or a sqaure.
if so i can `invalidate();` the canvas with an easy access I can see the changes instantly.

**Comment by ArthurHub** [comment]
`.setCropRect(Rect)`?
