### ISSUE TITLE
Pinch resizing of cropbox

### ISSUE THREAD

**Issue by petrfuka** [ArthurHub/Android-Image-Cropper#123]
Hello,
we tried the library in our application and it works great.

The only issue is that everyone I had try the cropping had trouble resizing the crop area. They all expected to resize with pinching and only some found out how the library does it in a short time.

We use a circular crop area so the corner lines don't show - perhaps they would help people understand how to resize, so the option to see those with circular crop area could help a bit. I would still prefer the option of resizing the cropbox with pinching motion.

**Comment by ArthurHub** [comment]
It's a good point, I think I will add corner borders for circular crop.
I don't want to add pinching as it may confuse and there is already a library with that: uCrop.

**Comment by ArthurHub** [comment]
added corners for circular crop in 2.2.5

**Comment by petrfuka** [comment]
Thank you for the quick response and resolution, this should be good enough.
