### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by urvish91** [ArthurHub/Android-Image-Cropper#124]
I have choosed image, and system saying image selected successfully. still not image coming, and cropping not working. Please respond as soon as possible, i am using nexus 5 marshmallow.

**Comment by tsiswandari** [comment]
I have the same issue above. 
Getting the sample code from the Release tag seems to be working for short term solution.

**Comment by ArthurHub** [comment]
Please provide more details. 
The code to get image for cropping, what API do you use and what happens exactly.

**Comment by tsiswandari** [comment]
With the latest code from master, the demo app wasn't loading images.  I'd get the toast that the image was loaded, but nothing appeared. 
There is also no Crop View overlay (circular, rectangular, etc etc) shows up on device.
Using the code from the last release was fine though.

**Comment by ArthurHub** [comment]
Oh.. I know that.. it's a minor bug introduced in my last commit I believe. 
But why are you using it instead of published release?

**Comment by tsiswandari** [comment]
I just want to check out the demo app! its a great library! Thank you!!

**Comment by ArthurHub** [comment]
Cool, just rollback to the latest release tag, you should be fine.
Will fix it tomorrow, lazy me.

**Comment by ArthurHub** [comment]
fixed.
