### ISSUE TITLE
Menu not found in : No Actionbar theme

### ISSUE THREAD

**Issue by boyfox** [ArthurHub/Android-Image-Cropper#125]
So, when I use library with Theme.AppCompat.Light.NoActionBar menu will be lose, I can't crope image:

![img_2016-07-11 19 20 48](https://cloud.githubusercontent.com/assets/3168694/16733870/bed1eafe-479c-11e6-856b-3a69c6a2d84a.jpg)

Anybody know how to fix it?

**Comment by ArthurHub** [comment]
You must have action bar for this activity, you can specify it in the manifest only for this activity:
```xml
<activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
    android:theme="@style/Base.Theme.AppCompat" />
```

**Comment by boyfox** [comment]
@thanks ArthurHub, work fine!
