### ISSUE TITLE
confusion

### ISSUE THREAD

**Issue by karopass** [ArthurHub/Android-Image-Cropper#128]
Hi sir !
I am little confused in .setRequestedSize as well in .setAspectRatio

If I want image with 800 height and 600 width than it will be like .setRequestedSize(600, 800) ? and .setAspectRatio(1,2) ?

means confusion is first value is for height or width ?

Thanks

**Comment by ArthurHub** [comment]
- It is `.setRequestedSize(width, height)', first is width.
- Aspect ratio of 1-2 means that the height it twice the width so 600x800 is not valied, 600x1200 is.
- `.setRequestedSize(width, height)` is something else entirely, used for sampling of the cropped image to reduce its total size.
- If you want to force the cropped image to specific size use `setMinCropResultSize` and `.setMaxCropResultSize()`.

You can play with the sample app to learn the API.
