### ISSUE TITLE
Unable to crop without ActionBar

### ISSUE THREAD

**Issue by NickRipley** [ArthurHub/Android-Image-Cropper#129]
First of all, thank you very much for this awesome tool! I have a quick suggest though. If I want to use your Activity builder but I am using a theme with no ActionBar, there's no way to do tell the Activity to crop and finish. If you could include a way to have buttons or a built in toolbar if there's no ActionBar present, it would be great for a situation like this. I'm getting around it by making a view instead, but if you wanted to add the functionality I think it would help! 

Again, thank you!

**Comment by ArthurHub** [comment]
Check the FAQ, you can have action bar for this activity.
