### ISSUE TITLE
CropBox fully expanded

### ISSUE THREAD

**Issue by franciscofranco** [ArthurHub/Android-Image-Cropper#130]
Is there a way to make the cropbox fully expanded to the full size of the image? I had a small trick in place for 2.2.3 but it's broken on 2.2.5. Is there any easy way to do it on my end or do I need to fork this and remove the padding during the init?

Thanks.

**Comment by ArthurHub** [comment]
What was the trick?

Also check the FAQ (it is the first question) or the "Visual Customization" wiki page.

**Comment by franciscofranco** [comment]
I'm a moron, since I didn't find the method from the cropImageView I assumed I couldn't change the padding. Did it through xml and worked fine.

**Comment by ArthurHub** [comment]
It happens, but what was the trick before? I wonder why it stopped working.

**Comment by franciscofranco** [comment]
I was doing something like:

`cropImageView.setCropRect(new Rect(view.getLeft(), view.getTop(), view.getRight(), view.getBottom()));`

On 2.2.3 it worked (but was kinda funky during rotations), then on 2.2.5 it broke and delivered a weird ass small cropbox.
