### ISSUE TITLE
No apps can perform this action on Huawei P9

### ISSUE THREAD

**Issue by geolyth** [ArthurHub/Android-Image-Cropper#132]
Hi guys,
this library works very well on all devices i tested but only on Huawei P9 i got a message "No apps can perform this action".
I checked on specific Huqawei P9 device and I saw other apps can use intents as we expected.

Why this happens?

Thanks in advance,
Fabio

**Comment by ArthurHub** [comment]
strange.. merged your PR, will be part of 2.3.0

**Comment by gpiccin** [comment]
Hi Arthur! 
Do you have expected to release image cropper 2.3? I need this fix!

**Comment by ArthurHub** [comment]
By the end of this week or early next.

**Comment by anandvenkatanarayanan** [comment]
I was using a Huawei honour device and until Android 5.X, the library was working correctly. However on upgrading to 6.0, I see the same error. (No Apps can perform this action). I can test the merge fix before release, if needed.

**Comment by ArthurHub** [comment]
published, check out **v2.3.0**

**Comment by gpiccin** [comment]
Thank's ArthurHub!

**Comment by ArthurHub** [comment]
All praise should go to @geolyth for finding, solving and sending a PR!
Thank you!

**Comment by gpiccin** [comment]
Hi, I updated the library to 2.3.0 but the users have the same error on Huawey device.
Any idea?

**Comment by geolyth** [comment]
In these days I found that this fix does not work on all huawei devices, but i don't know why this happens.

**Comment by geolyth** [comment]
I don't know why but i was thinking...maybe could be a Huawei Protected Apps issue?
Anyone could try to enable this feature on Huawei?

**Comment by ArthurHub** [comment]
I don't have the device to reproduce or test this issue so I need your help (all of you).
If you find a solution/workaround please let me know or send a PR.

**Comment by nicolabeghin** [comment]
Same issue on xiaomi mi5

**Comment by gpiccin** [comment]
Hi ArthurHub, 
Can you generate a hot fix with new pull request? 

Thanks nicolabeghin!

**Comment by nicolabeghin** [comment]
hi @gpiccin I don't know what you mean with that..

**Comment by gpiccin** [comment]
Hi @nicolabeghin I need urgently this bugfix #156.
I want to know if @ArthurHub can generate one build "2.3.1" only with this.

Thank's.

**Comment by nicolabeghin** [comment]
@ArthurHub is gonna build thenew release in a few hours (see PR #156)

**Comment by ArthurHub** [comment]
Published, let me know if all good or not.

**Comment by gpiccin** [comment]
Thanks @nicolabeghin and @ArthurHub!

**Comment by nicolabeghin** [comment]
Just updated to the 2.3.1 release, everything's good on Xiaomi MI5!

**Comment by gpiccin** [comment]
Updated to version 2.3.1 and worked on 2 Huawei devices! 

Thanks @nicolageghin and @ArthurHub.

**Comment by winster** [comment]
Had issues with Le1s in 6.0, 2.3.1 fixed the problem. Thanks :+1:

**Comment by emadPirayesh** [comment]
i use library com.theartofdev.edmodo:android-image-cropper:2.7.+. user reported me he see this  No apps can perform this action message in black screen in device redmi 4a with android 6.0.1

**Comment by krajzler** [comment]
It is the same on my Phone. I'm using Google Pixel 3 with Android 11. `android-image-cropper` lib is 2.8.0.

**Comment by sigdelbijay** [comment]
I have the same problem "no apps can perform this action" while trying to select image using this library version 2.8.0 on my Pixel 4a device.

**Comment by Dohmanlechx** [comment]
> It is the same on my Phone. I'm using Google Pixel 3 with Android 11. `android-image-cropper` lib is 2.8.0.

> I have the same problem "no apps can perform this action" while trying to select image using this library version 2.8.0 on my Pixel 4a device.

Same issue here.

**Comment by Dohmanlechx** [comment]
Solved! This library isn't maintained, see https://github.com/ArthurHub/Android-Image-Cropper/issues/806, I migrated to that new one and now it works like a charm.
