### ISSUE TITLE
Setting Min and MaxCropResultSize Programmatically on CropImageView

### ISSUE THREAD

**Issue by otuozema** [ArthurHub/Android-Image-Cropper#139]
First, I would like to say that this is a very good library for cropping, and it appears to suit my purposes well. However, I found that the method
 -- setMaxCropResultSize(maxCropResultWidth, maxCropResultHeight) -- 
could only be called if using the in-built activity (when trying to start it). 

For certain reasons, I have to use a custom activity, where I use a CropImageView, and it would be great if one could call myCropImageView.setMaxCropResultSize(width, height) through Java code, because the values of "width" and "height" are dependent on other factors. If this is currently possible somehow, please let me know how; if not, I hope it's something you consider to include.

Your efforts are appreciated. Thanks.

**Comment by ArthurHub** [comment]
Will add in next version.

**Comment by ArthurHub** [comment]
Done, see **v2.3.0**
