### ISSUE TITLE
No toolbar at CropImageActivity

### ISSUE THREAD

**Issue by jean2paulo** [ArthurHub/Android-Image-Cropper#142]
Toolbar is not showing when I open CropActivity. Am I missing anything? 

![screenshot 1](https://cloud.githubusercontent.com/assets/3248076/17518715/66ea9ebe-5e1f-11e6-8dba-fd7268ce5246.jpg)

**Comment by bamdad01** [comment]
It's because of your theme style, if you are using NoActionBar
Create a new Style in your Style.xml 
`<style name="NewTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>`
And apply it to the activity in manifest.

`<activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
                android:theme="@style/NewTheme"/>`

**Comment by jean2paulo** [comment]
Yeah I am using NoActionBar. With this new theme is working fine. Thanks 👍
