### ISSUE TITLE
change the word 'CROP' in toolbar

### ISSUE THREAD

**Issue by bamdad01** [ArthurHub/Android-Image-Cropper#143]
First of all thank you for this great library .
I'm using the code you provide in quick-start folder .
Is there any method or any way to change the word 'CROP' showing in toolbar (I'm going to translate it).
thank you.

**Comment by ArthurHub** [comment]
See the wiki please.

**Comment by bamdad01** [comment]
Thank you.
So easy ... 
https://github.com/ArthurHub/Android-Image-Cropper/wiki/Activity-Visual-Customization#crop-menu-item
