### ISSUE TITLE
Fix cropping area in center of screen

### ISSUE THREAD

**Issue by p4block** [ArthurHub/Android-Image-Cropper#144]
I'm really loving this lib, thanks to everyone involved. 

However, we are using it in a quite unusual way that requires something the current customization options do not allow. 

Our app has its content already centered, so I'd like to make the user unable to move the crop area, while still leaving them able to resize it (with a fixed aspect ratio)

Would this be within the scope of a newer version?

**Comment by ArthurHub** [comment]
maybe uCrop is a better option for this scenario, check it out.

**Comment by p4block** [comment]
I've swapped out this lib for uCrop on the app and found out they don't support resizing a fixed aspect ratio window keeping the center... centered either. The croptangle didn't move tho!

I prefer this one's workings, so I'll start working on modifying it now.

Thanks for the help.

**Comment by ArthurHub** [comment]
Cool, that will be great!
Make sure to check the PR I didn't have a chance to merge yet, the multi-touch support may be helpful.
