### ISSUE TITLE
Crop Button is not change.. :(

### ISSUE THREAD

**Issue by cnbcyln** [ArthurHub/Android-Image-Cropper#145]
Crop Button is not change.. :(

**Comment by ArthurHub** [comment]
what?

**Comment by cnbcyln** [comment]
I can not change the title of the Crop button.

**Comment by ArthurHub** [comment]
See the [wiki page](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Activity-Visual-Customization#activity-title) there are two (2) options

1. Using resource
2. Using builder method if dynamic name is required.

**Comment by cnbcyln** [comment]
I want to change "CROP BUTTON" text, I mean I want to translate it to my language.

Example: .setCropButtonTitle("Crop");

 I can not change the resource..

**Comment by ArthurHub** [comment]
common man... add `crop_image_activity_title` to the string resource file in your project and it will override the resource in the library, you can add it in multiple resource languages. this is how android resources works.

have you tried it?

**Comment by cnbcyln** [comment]
Aaah! Sorrym, I could'nt understand what you said before. Now I got it, thank you!
