### ISSUE TITLE
Uri is different from android gallery uri

### ISSUE THREAD

**Issue by alizarei95** [ArthurHub/Android-Image-Cropper#146]
hello and thank you for this library

result.getUri() returns uri of cropped image but this uri is different from android gallery uri.

for example :

android gallery uri :
`content://com.android.providers.media.documents/document/image.jpg`

cropped image uri :
`file:///data/data/com.example.farasoo.myapplication/cache/cropped1025206232.jpg`

so how can i get an uri from cropped image like android gallery ?

**Comment by ArthurHub** [comment]
you need to save the image into gallery,  you can set the uri that the library saves the cropped image to but i don't know if its as simple as that.
