### ISSUE TITLE
Cannot see the crop button on screen

### ISSUE THREAD

**Issue by winster** [ArthurHub/Android-Image-Cropper#148]
Once the crop activity is launched, it should show the action bar with crop button. But it is not shown

**Comment by ArthurHub** [comment]
see the wiki FAQ

**Comment by Bonissauro** [comment]
I've tryied adding on manifest but it didn't solve the issue. Crop button is not rendered

<activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
    android:theme="@style/Base.Theme.AppCompat" />
