### ISSUE TITLE
Permission Write External Storage

### ISSUE THREAD

**Issue by chacongalvez** [ArthurHub/Android-Image-Cropper#149]
Hello,

I found that if you are using a device with SDCard slot but without a external SDCard, needs to use <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> in the manifest, if this permission is not set, when you try to take an image from the camera the method getCaptureImageOutputUri(context) returns null.

Congratulations for this library.

**Comment by ArthurHub** [comment]
Thx, I would like to reproduce it, what device did you see it on?

**Comment by chacongalvez** [comment]
I'm using an Alcatel Pop C3 because the app I'm developing will be installed in old and low cost devices.

Here you are information related about this device: http://www.gsmarena.com/alcatel_pop_c3-5687.php

**Comment by chacongalvez** [comment]
Sorry, I don't know how but I forgot to show in the first comment the permission that I have used to solve the issue: <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

Hope it helps.

**Comment by ArthurHub** [comment]
Stuff like that frustrates me about Android.
Thank you for pointing it out I have added it to documentation.
