### ISSUE TITLE
Touch handle is off when using `setCropShape(CropImageView.CropShape.OVAL)`

### ISSUE THREAD

**Issue by loeschg** [ArthurHub/Android-Image-Cropper#15]
When setting the crop shape to oval - `setCropShape(CropImageView.CropShape.OVAL)` - the touch points to resize are not what I'd expect. It looks like it may still have the typical square touch points.  

![screenshot_2015-07-17_11_52_06](https://cloud.githubusercontent.com/assets/766021/8752592/9b9664cc-2c7a-11e5-8174-a5be7b6d91a4.png)
Red points indicate failed resize attempts. Green = successful.

Am going to try to dig into this myself and submit a PR. Any help pointing in the right direction would be awesome!

**Comment by loeschg** [comment]
https://github.com/ArthurHub/Android-Image-Cropper/blob/master/cropper/src/main/java/com/theartofdev/edmodo/cropper/util/HandleUtil.java#L52-L101

**Comment by loeschg** [comment]
@ArthurHub I went ahead and made some modifications. I opened a PR to at least begin dialogue... would love to know your thoughts!

**Comment by ArthurHub** [comment]
I thought I would have time to go into it, but unfortunately... life.
I have merged the PR, thank you.
