### ISSUE TITLE
The same error like “No apps can perform this action on Huawei P9‘’ on mi note 

### ISSUE THREAD

**Issue by gmm932** [ArthurHub/Android-Image-Cropper#150]
Hello,author
I test huawei and mi note. No select source.
Why? can you fix it?

**Comment by gpiccin** [comment]
See the issue #132

**Comment by ArthurHub** [comment]
I can't test it because I don't have this device.
If you can find what the issue is I will gladly add the fix to the code.

**Comment by bobingxin** [comment]
I have same problem,in xiaomi 5

**Comment by ArthurHub** [comment]
duplicate #132
