### ISSUE TITLE
How can I custom the select source view and change intent chooser view?

### ISSUE THREAD

**Issue by LT5505** [ArthurHub/Android-Image-Cropper#151]
In your library, you use the method of creating intent chooser.But In my Project,I need to change the select source view.I had searched something about it,but I can not resolve this problem.Can you help me?My English is not great,sorry

**Comment by ArthurHub** [comment]
See the code in the library, it's just a couple of methods.
See also [Android cropping image from camera or gallery](https://theartofdev.com/2015/02/15/android-cropping-image-from-camera-or-gallery/).

**Comment by LT5505** [comment]
Thank you every much.I want to use your library in my project and make some changes.I want to custom the select source view.As shown in the following figure,
![pic](https://cloud.githubusercontent.com/assets/6197224/18112822/4d8ff97e-6f5d-11e6-86b3-1e6c327c4802.jpg)

But I do not know What should I do,can you help me?Thanks for your help

**Comment by ArthurHub** [comment]
Can't write the code for you, you will have to learn it yourself, good luck.
