### ISSUE TITLE
Crop rect position issue

### ISSUE THREAD

**Issue by martinprevas** [ArthurHub/Android-Image-Cropper#153]
Hi,

Thanks for a great lib, it is really excellent!

I am experiencing a problem when using CropImageView in my own layout. The problem is that the crop rect seems to be centered on some point off center initially and this means it stretches beyond the size of the image. First time I touch the view it corrects this error immediately. I have attached a photo of the problem below. Do you have some suggestions on how to solve this problem or do you need more information?

![device-2016-08-25-221756](https://cloud.githubusercontent.com/assets/18552618/17984566/0dbd316c-6b12-11e6-9194-be010a7aaba7.png)

**Comment by ArthurHub** [comment]
Hey, looks like a bug.
I'm on vacation now, let me try to reproduce it next week, if I can reproduce it I will fix and publish a new version, otherwise will require more info.
Thx.

**Comment by martinprevas** [comment]
I will try to isolate the problem in a minimalistic example in the mean time.

Have a nice vacation :-)

Regards
Martin

**Comment by martinprevas** [comment]
I think the crop view does not respond very well with weighted sizes. If I place the crop view with match_parent in a linear layout which has height = 0 and weight = eg. 1 then it works as expected. Heres a working layout snippet:

`    <LinearLayout
        android:id="@+id/cropImageViewLayout"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:orientation="vertical"
        android:layout_weight="2"
        android:visibility="visible">
        <com.theartofdev.edmodo.cropper.CropImageView
            android:id="@+id/cropImageView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
    </LinearLayout>
`

**Comment by ArthurHub** [comment]
I didn't handle resize of the view, I think I fixed it in v2.3.1, let me know if all good now as its a bit tricky.
Thank you!

**Comment by ArthurHub** [comment]
@martinprevas ?

**Comment by martinprevas** [comment]
Hi, I tested it a couple of days ago and it seems to behave alright now. I will report back if I find any problems. Thanks for a great library and quick support :-)

Best regards
Martin

**Comment by ArthurHub** [comment]
Awesome! 
Thank you for reporting this issue and providing the info, it really helped me find the underline problem.
