### ISSUE TITLE
CropImage.toOvalBitmap 

### ISSUE THREAD

**Issue by piyushmishhy** [ArthurHub/Android-Image-Cropper#154]
I have used the cropped image to CropImage.toOvalBitmap then upload and download it however, the pictures are coming as blacked. Is there any function to crop image to transparent instead of black pixels?
![image](https://cloud.githubusercontent.com/assets/6805110/18034308/5ba09d14-6d57-11e6-90d0-525c00c38794.jpg)

**Comment by ArthurHub** [comment]
You are using jpeg image format that doesn't support transparency, you need to use png.
