### ISSUE TITLE
Using CropImage.startPickImageActivity in Fragment

### ISSUE THREAD

**Issue by victinformatici** [ArthurHub/Android-Image-Cropper#155]
I have an app with tabbed AppCompat Fragments. I'm trying to use the cropper in one of the tabbed Fragments. I start the camera/gallery activity with CropImage.startPickImageActivity(getActivity()) from within the Fragment. The result needs to go to the Fragment's onActivityResult. Calling super.onActivityResult in the main activity's onActivityResult won't pass it on to the Fragment; probably it gets only to the main Activity because I use getActivity() as a parameter for CropImage.startPickImageActivity. Is there a way to let the Fragment get the result, in the same way as I can use CropImage.activity(imageUri).start(getContext(), this) for Fragments?

**Comment by victinformatici** [comment]
To be short, I would like the CropImage.getPickImageResultUri to be retreived in my Fragment's onActivityResult, not in my main Activity. Just the way CropImage.getActivityResult can be retreived in the Fragment.

**Comment by ArthurHub** [comment]
the code of `startPickImageActivity` is just:
```java
public static void startPickImageActivity(@NonNull Activity activity) {
    activity.startActivityForResult(getPickImageChooserIntent(activity), PICK_IMAGE_CHOOSER_REQUEST_CODE);
}
```

So you can call `getPickImageChooserIntent()` to get the intent and use it in the fragment `startActivityForResult()` method.

**Comment by AshwiniDabir** [comment]
Thank you. I was facing the same issue.
I have a query here. (not sure where to post this).  I want to limit the size of the final cropped image to 1.5 MB, since I have a server restriction (image with size > 2MB cannot be uploaded).
I understand the size will depend on the device density, but it would be great if you could suggest a way too restrict it after cropping itself.

Thanks for a great library !!

**Comment by ArthurHub** [comment]
There is no feature to restrict the image size, it may be problematic as it depends on the image format used.
But you can restrict the resolution of the resulted cropped image using required size feature.
Setting it to 1080 x 1920 and using jpeg format with 90-95 quality should limit the potential size under 2MB.

**Comment by Shivumantur** [comment]
When i clicked circular image i called CropImage.startPickImageActivity(getActivity()) its open 
![device-2017-11-06-1648256](https://user-images.githubusercontent.com/22428229/32439188-9a586f60-c313-11e7-80ab-b6c146ccd058.jpg)
i get this but here Camera is not Open other Gallery and Filemanager working Fine please suggest me, sorry for my bad english

**Comment by NajafAli** [comment]
i am facing this issue on activity result image not found but when i take image from camera or gallery it process to crop , after that found nothing on actiuvity reslut here is my code:

` @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {

        if (resultCode != RESULT_OK) {
            return;
        }

        switch (requestCode) {
            case ACTION_REQUEST_EDITIMAGE://
                handleEditorImage(data);
                break;

            case REQUEST_CODE_GALLERY:

                if (mCurrentPhotoPath == null) {

                    Uri selectedImageUri = data.getData();
                    CropImage.activity(selectedImageUri)
                            .setGuidelines(CropImageView.Guidelines.ON)
                            .start(getActivity());
                }

                break;

            case REQUEST_CODE_CAPTURE:

                try {
                    Uri imageUri = Uri.parse(mCurrentPhotoPath);
                    if (imageUri == null) {

                    } else {
                        CropImage.activity(imageUri)
                                .setGuidelines(CropImageView.Guidelines.ON)
                                .start(getActivity());
                        MediaScannerConnection.scanFile(getActivity(),
                                new String[]{imageUri.getPath()}, null,
                                new MediaScannerConnection.OnScanCompletedListener() {
                                    public void onScanCompleted(String path, Uri uri) {
                                    }
                                });
                        mCurrentPhotoPath = null;
                    }

                } catch (Exception e) {

                }

                break;

            case CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE:
                CropImage.ActivityResult result = CropImage.getActivityResult(data);
                Uri resultUri = result.getUri();
                if (resultUri != null) {
                    path = resultUri.getPath();
                    if (TextUtils.isEmpty(path)) {
                        return;
                    }
                    Intent it = new Intent(getActivity(), EditImageActivity.class);
                    it.putExtra(EditImageActivity.FILE_PATH, path);
                    File outputFile = FileUtils.getEmptyFile("tietu"
                            + System.currentTimeMillis() + ".jpg");
                    it.putExtra(EditImageActivity.EXTRA_OUTPUT,
                            outputFile.getAbsolutePath());
                    startActivityForResult(it,
                            ACTION_REQUEST_EDITIMAGE);

                }

                break;

            case CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE:
                Toast.makeText(getActivity(), "error in cropping", Toast.LENGTH_SHORT).show();
                break;
        }
        super.onActivityResult(requestCode, resultCode, data);
    }
`private void openGallery() {

        Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
        photoPickerIntent.setType("image/*");
        startActivityForResult(photoPickerIntent, REQUEST_CODE_GALLERY);
    }`

**Comment by Shivumantur** [comment]
Step: 01) 
    compile 'de.hdodenhof:circleimageview:2.1.0'  // add in build graddle
	
	Step 02) 
	
	<de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/profile_image"
                android:layout_width="100dp"
                android:layout_height="100dp"
                android:layout_centerHorizontal="true"
                android:contentDescription="Profile Image"
                android:src="@drawable/ic_profile"
                app:civ_border_color="@color/colorWhite"
                app:civ_border_width="2dp" />
				
				
   Step 03) 
   private Uri cropImageUri;  //Global variable
   
   Step 04) 
   RxView.clicks(imageProfile).subscribe(view -> CropImage.startPickImageActivity(getActivity()));
 
 Step 05) 
 @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case CropImage.PICK_IMAGE_CHOOSER_REQUEST_CODE:
                if (resultCode == RESULT_OK) {
                    Uri imageUri = CropImage.getPickImageResultUri(getContext(), data);

                    // For API >= 23 we need to check specifically that we have permissions to read external storage.
                    if (CropImage.isReadExternalStoragePermissionsRequired(getContext(), imageUri)) {
                        // request permissions and handle the result in onRequestPermissionsResult()
                        cropImageUri = imageUri;

                        requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, CropImage.PICK_IMAGE_PERMISSIONS_REQUEST_CODE);
                    } else {
                        // no permissions required or already grunted, can start crop image activity
                        cropImage(imageUri);
                    }
                }
                break;
            case CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE:
                CropImage.ActivityResult result = CropImage.getActivityResult(data);
                if (resultCode == RESULT_OK) {
                    Uri resultUri = result.getUri();
                    try {
                        final InputStream imageStream = getActivity().getContentResolver().openInputStream(resultUri);
                        final Bitmap selectedImage = BitmapFactory.decodeStream(imageStream);

						// Use Picasso or Universal Image Loader:       compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5' 
						Picasso.with(getContext())
                                                    .load(R.drawable.ic_profile)
                                                    .error(R.drawable.ic_profile)
                                                    .fit()
                                                    .centerCrop()
                                                    .into(imageProfile);
													
						// or
						
						// imageProfile.setImageBitmap(selectedImage);
			
                    } catch (FileNotFoundException e) {
                        e.printStackTrace();
                    }
                } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                    Log.d(TAG, "onActivityResult: Error in cropping");
                }
                break;
        }
    }

	Step 06)
    private void cropImage(Uri imageUri) {
        CropImage.activity(imageUri)
                .setGuidelines(CropImageView.Guidelines.ON)
                .start(getContext(), this);
    }

**Comment by NajafAli** [comment]
thanks dear

**Comment by JMCMARQUES** [comment]
> 
> 
> the code of `startPickImageActivity` is just:
> 
> ```java
> public static void startPickImageActivity(@NonNull Activity activity) {
>     activity.startActivityForResult(getPickImageChooserIntent(activity), PICK_IMAGE_CHOOSER_REQUEST_CODE);
> }
> ```
> 
> So you can call `getPickImageChooserIntent()` to get the intent and use it in the fragment `startActivityForResult()` method.


Hello ArthurHub,

I think that I'm using the equivalent of what you are writing above, however, after the image is selected, the flow of the program goes to the activity onActivityResult() and not to the fragment onActivityResult()

this is what I have in the fragment:
*activity?.run {
                startActivityForResult(CropImage.getPickImageChooserIntent(this, getString(R.string.select_app), false, false), CHOOSE_IMAGE_REQUEST)
            }*

after selecting the image, the app flow shifts to the activity and not the fragment itself

is there something missing on the code above that is preventing the flow to be kept on the fragment method onActivityResult()?

ps: I'm using kotlin
