### ISSUE TITLE
Crop Screen Rotation Crash the Application

### ISSUE THREAD

**Issue by sghazagh** [ArthurHub/Android-Image-Cropper#157]
Hi,
I know that might be my screen rotation issue but I thought you might guide me if there is anything that I can do to preventing this.

In my activity, when I start camera, after taking photo I use this CropImage library.
If I rotate my screen during cropping, and then Crop image to save the crop, then my app crashes.

Probably because my back activity is rotated.(I have implemented the CropImage at Activity Level)
I tried to lock the orientation of activity before Camera intent starts but it still happens.

Do you know any way that I can preventing this.
Or maybe stop rotating the screen at the time of Cropping?

Many thanks

**Comment by ArthurHub** [comment]
Well, there is no reason for the app to crash, ever.
So my advice is to find why it happens, it doesn't happen just because of screen rotation, it's probably just a trigger.
Start by looking at the stack trace of the crash.
