### ISSUE TITLE
not in maven central

### ISSUE THREAD

**Issue by jhegedus42** [ArthurHub/Android-Image-Cropper#158]
the lib cannot be installed from maven central, it is not in maven central:
http://search.maven.org/#search%7Cga%7C1%7Ccropper

**Comment by jhegedus42** [comment]
but it seems to be in jcenter : https://bintray.com/arthurhub/maven/Android-Image-Cropper

**Comment by ArthurHub** [comment]
Yep, android standard repository is jcenter.

**Comment by jhegedus42** [comment]
right, I use sbt, and needed to add `resolvers += Resolver.jcenterRepo` to `build.sbt`, works now, thanks!
