### ISSUE TITLE
Failed to open cropped image pickImageResult.jpeg

### ISSUE THREAD

**Issue by vajiralasantha** [ArthurHub/Android-Image-Cropper#160]
Hi,
First I like to thank you for creating this library. However I have an issue using this lib in my app.

I have some images in **RAW** folder of my app and I can load them to CropImage using following code.
```
Resources res = getResources();
Uri resUri = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE +
                        "://" + res.getResourcePackageName(resId)
                        + '/' + res.getResourceTypeName(resId)
                        + '/' + res.getResourceEntryName(resId)
                );
CropImage.activity(resUri)
.setGuidelines(CropImageView.Guidelines.ON)
.start(TestActivity.this);
```

After cropping on onActivityResult method, I use an InputStream to read cropped image using following code.
```
if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE && resultCode == AppCompatActivity.RESULT_OK) {
            Uri imageUri = CropImage.getPickImageResultUri(this, data);
            Log.i(TAG, "onActivityResult: " + imageUri);
            try {
                inStream = getContentResolver().openInputStream(imageUri);
            } catch (Exception e) {
                Log.i(TAG, "onActivityResult: EX " + e.getMessage());
                finish();
            }
        }
```

but it gives me following error.
`/mnt/sdcard/Android/data/com.my.app/cache/pickImageResult.jpeg: open failed: ENOENT (No such file or directory)`

I checked this file path and there is no file called **pickImageResult.jpeg** there either.

Yes I have both WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE permission in manifest file.

Tried on Android 4.1.1 and 6.0 but both time same error.

Any idea why this is happening?

Thanks.

**Comment by ArthurHub** [comment]
Thx.

`CropImage.getPickImageResultUri` is for selecting image for cropping, not for the resulted cropped image, you need to call `CropImage.getActivityResult` like it described in step 3:

```java
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
   if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
       CropImage.ActivityResult result = CropImage.getActivityResult(data);
       if (resultCode == RESULT_OK) {
           Uri resultUri = result.getUri();
       } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
           Exception error = result.getError();
       }
   }
}
```

**Comment by vajiralasantha** [comment]
Awesome. Working just fine. Thank you for quick response.
