### ISSUE TITLE
Werird Issue with Google Camera

### ISSUE THREAD

**Issue by Frankenstein666** [ArthurHub/Android-Image-Cropper#162]
I have setup two options 1) take picture from camera 2) choose from galley. 
if i chose from gallery first like this:
  _

**final Uri imageUri = data.getData();
                    Log.i("galleryuri", imageUri + "");
                    CropImage.activity(imageUri)
                            .setGuidelines(CropImageView.Guidelines.ON)
                            .setActivityTitle("Crop Image")
                            .setFixAspectRatio(true)
                            .start(this);**

CropActivity launches successfully i can crop image without any issue.

and if i chose to take picture from camera first and pass the uri of captured image to cropActivity like this:

  **if (resultCode == RESULT_OK) {
                    CropImage.activity(mImageCaptureUri)
                            .setGuidelines(CropImageView.Guidelines.ON)
                            .setActivityTitle("Crop Image")
                            .setFixAspectRatio(true)
                            .setBorderLineThickness(2.0f)
                            .setBorderLineColor(getResources().getColor(R.color.colorAccent))
                            .start(this);**

Nothing happens, i am back to where i was before launching the camera app.

what i mean is if i choose take picture first, cropActivity doesn't even opens up. if i choose from gallery everything is alright.

**Comment by Frankenstein666** [comment]
if i put a log after requestcode 203 and before RESULT_OK check, i get 
open failed: EACCES (Permission denied) message, do i need read external storage permission for this purpose as well?

**Comment by ArthurHub** [comment]
It may be server things depending on Android version and the permissions you already request, see [Pick image for cropping from Camera or Gallery](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Pick-image-for-cropping-from-Camera-or-Gallery).

**Comment by Frankenstein666** [comment]
I asked both permissions i.e, CAMERA and READ_EXTERNAL_STORAGE before launching camera and now it works perfectly.

**Comment by Frankenstein666** [comment]
I asked both permissions i.e, CAMERA and READ_EXTERNAL_STORAGE before launching camera and now it works perfectly.
