### ISSUE TITLE
remove square crop view

### ISSUE THREAD

**Issue by NaveenJayaram1994** [ArthurHub/Android-Image-Cropper#163]
i really need it. after i cropping the image  i need to disable the square box used to crop the image .
anyone please help me

**Comment by ArthurHub** [comment]
I don't understand your question.
Do you want to hide the crop window overlay? then `setShowCropOverlay` can do that.

**Comment by ArthurHub** [comment]
@NaveenJayaram1994 ?

**Comment by NaveenJayaram1994** [comment]
it worked thank thank thank thank thank you sooooo much
