### ISSUE TITLE
Why some classes are marked as final

### ISSUE THREAD

**Issue by nicolabeghin** [ArthurHub/Android-Image-Cropper#165]
Hi 
I'd like to know if there's any reason for marking as `final` some fundamental (and extremely useful) classes like 
```java
public final class CropImage
```

I think it would be helpful to be able to extend them, if needed.

Thanks
nicola

**Comment by ArthurHub** [comment]
`CropImage` is a "static class" there is no point in extending it, as java doesn't have special syntax for it the way to do it is making the class final with a private constructor.

Making non-static class final allows the runtime do some optimization knowing that all its method a are final like inlining.

**Comment by nicolabeghin** [comment]
I'm trying to extend the CropImage in order to start an extended CropImageActivity, since that's hardcoded. Being the class marked as final this is not possible. I think it's much more future-proof to extend CropImage in place of copy-pasting it in a new one..

**Comment by nicolabeghin** [comment]
So sorry, I just saw the method
`public void start(@NonNull Activity activity, @Nullable Class<?> cls)`

This solves everything. So sorry for bringing this up, you rock as always!
