### ISSUE TITLE
ResetCropRect() rotates the original image by 90 degree (Android 6.0 portrait orientation)

### ISSUE THREAD

**Issue by wyzard** [ArthurHub/Android-Image-Cropper#168]
When I make a picture on my LG G4 (Android 6.0) in portrait orientation (than I pass it to your library), than I call resetCropRect() method I get the original picture and zoom level, but the image is rotated by 90 degree.

Do you have any idea how can I fix this ? Thank you.

**Comment by ArthurHub** [comment]
Hmm... I think it's because the image was rotated on load by exif data, reset sets it to zero instead of the initial value.

As a work around until a fix try doing it yourself, if you use the view directly and not the activity that is.

**Comment by wyzard** [comment]
Ok, thank you for the information.

**Comment by a371166028** [comment]
hello i meet the bug too when rotate 330 degress-359 degress   （-30~0）

**Comment by ArthurHub** [comment]
fixed in 2.4.0
