### ISSUE TITLE
Crop window size Bug?

### ISSUE THREAD

**Issue by CharnLau** [ArthurHub/Android-Image-Cropper#176]
I set cropAspectRatioX to 9 and cropAspectRatioX to 1.
But I touch the top-left or top-right or bottom-left or bottom-right, the crop window's width will change to image's width, and It can move, but it can't change to small.
Is it bug?

**Comment by CharnLau** [comment]
I'm sorry, I don't understand how to upload image.
I set FixAspectRatio to true, and set cropAspectRatioX to 9 and cropAspectRatioY to 1.
But, the crop windows can change to big, can't change to small. 
Your sample also has this bug.
You can change to code to this. and you can find this bug.
`                        mCropImageViewOptions.aspectRatio = new Pair<>(9, 1);`
thanks!

**Comment by ArthurHub** [comment]
Maybe you are hitting [crop min size limit](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Limit-cropped-image-result-min-max-size)?
