### ISSUE TITLE
getCroppedImage(int reqWidth, int reqHeight, RequestSizeOptions options) causes java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by sneps85** [ArthurHub/Android-Image-Cropper#178]
When calling 

`getCroppedImage(int reqWidth, int reqHeight, RequestSizeOptions options)`

 on very large images, an OutOfMemory exception occurs.

Specially I am calling 

`getCroppedImage(2048, 2048, CropImageView.RequestSizeOptions.RESIZE_INSIDE)`

on a 2.6MB image with 5494x3666 resolution without cropping.

**Comment by asiop** [comment]
![image](https://cloud.githubusercontent.com/assets/3198163/19936970/1edffe56-a128-11e6-88c9-03b62942c6f3.png)

I ran into the same problem, here's the stack trace, thanks in advance!

**Comment by ArthurHub** [comment]
In 2.4.0 I have added handling of OOM by reducing the size of the image if exception occurs.
Previously it was only if cropping image was loaded by uri, added for bitmap as well.
This should solve the issue.
