### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by anshulg12** [ArthurHub/Android-Image-Cropper#18]
Hello,

Do you know how to use your library and allow for the user to zoom into the image before cropping?

Thanks,
Anshul

**Comment by ArthurHub** [comment]
I'm gonna try to add auto zoom in/out depending on crop size relative to the image...

**Comment by gupta11** [comment]
Wow that would actually be amazing. Please let me know when you want me to test. :) I can QA it properly for you.

**Comment by ArthurHub** [comment]
update: will start working on it soon, but because its not a trivial feature and I don't have a lot of time it may take at least a month, sorry.

**Comment by davidaik** [comment]
+1 I love this library and I've been wishing for auto zoom feature. It'll definitely be very useful. Hope to get it soon. Thanks, Arthur!

**Comment by ArthurHub** [comment]
It took long enough but it's finally here **v2.0.0**, hope you will find it useful.
I marked it as *beta* because it required many changes so there might be a bug or two, let me know and I will fix them ASAP.
