### ISSUE TITLE
AppCompat Dependency

### ISSUE THREAD

**Issue by adwiv** [ArthurHub/Android-Image-Cropper#184]
My requirement is to use this in a app that does not depend on support libraries. We want to keep the app very small in size, hence we are trying to avoid unnecessary dependencies.

From what I understand, the cropper library has a dependency on AppCompat for three reasons:

1. CropImageActivity extends `AppCompatActivity`
2. two start methods of `ActivityBuilder` take a v4 fragment
3. `showAsAction` requires  support library or android api 11 (current is 10)

These three restrictions can be easily solved by setting minimum api 11 and removing the start methods that use a fragment and instead using getIntent() instead of start for fragments.

```
Intent intent = CropImage.activity(imageUri)
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setMultiTouchEnabled(true)
                        .getIntent(this);
startActivityForResult(intent, CROP_IMAGE_ACTIVITY_REQUEST_CODE);
```

Would you be interested in removing the dependency from the cropper library?

**Comment by ArthurHub** [comment]
I understand your use case but it is not very common.
I feel it will be too risky to change it now.

**Comment by adwiv** [comment]
Yes, I agree with the uncommon use case.

Just wanted to check with you.

Thanks. Please close the issue.
