### ISSUE TITLE
Show image picker when Uri is not provided

### ISSUE THREAD

**Issue by adwiv** [ArthurHub/Android-Image-Cropper#185]
A common use case is to first start a chooser to select the file to crop and then call the `CropImage.activity(uri)` method. It would be great if we can include the file selection as a part of the cropping flow.

For example if the image Uri is not provided, it should start a chooser and then automatically start the cropper once the file is selected. Essentially this is quite same as moving part of the quick-start MainActivity into the main library.

**Comment by ArthurHub** [comment]
can't be done because of how start activity for result works in android.

**Comment by adwiv** [comment]
This I believe should be quite easy by introducing another activity
in-between when the Uri is null. The getIntent method would check the Uri
and use the PickerActivity class instead of CropActivity. The
PickerActivity would onActivityResult success start the CropActivity.

Alternate method would be to call the CropImage.startPickImageActivity()
from onCreate of CropImageActivity instead of  setImageUriAsync() when Uri
is null and do the setImageUriAsync in onActivityResult when we get the
response from picker.

I had done this with an older version of library. Will be doing again with
latest version.

If you would be interested in this, I can send a pull request when ready.

Thanks.

**Comment by ArthurHub** [comment]
Definitely interested, PR would be awesome!

Couple of points:
* Must be backward compatible, prefer adding new method than changing the behavior of existing one unless upgrade path is very clear to existing users.
* Make sure you handle Android 6 new security scheme, `requestPermissions` stuff.
* If you can also make it work for fragments that would be great.

Good luck,
Thank you.

**Comment by adwiv** [comment]
Sent a PR. Seems to work for me with the permissions.

Not tested with fragments, but it should probably work as no change should interfere with caller fragment.

Thanks.

**Comment by ArthurHub** [comment]
available in 2.4.0, thx
