### ISSUE TITLE
Provide Custom Request code while starting CropActivity

### ISSUE THREAD

**Issue by BhaveshPatadiya** [ArthurHub/Android-Image-Cropper#186]
I am using your library in one of my project and it works quite well. However, I couldn't able to find a way to send you custom request code while starting the CropActivity. The reason I wanted to have this is because my app is having many different action that will be taken care after crop completion and it seems currently it passes the onActivityResult with RequestCode of CROP_IMAGE_ACTIVITY_REQUEST_CODE only.

**Comment by ArthurHub** [comment]
You can get the intent and start it manually:
```java
Intent intent = CropImage.activity(imageUri)
  .getIntent(getContext());
startActivityForResult(intent, myCode);
```

**Comment by BhaveshPatadiya** [comment]
Thanks Much!!
