### ISSUE TITLE
.png images are not keeping transparent background

### ISSUE THREAD

**Issue by martinbaciga** [ArthurHub/Android-Image-Cropper#191]
Hi!

I'm using this library on my current project and i have this issue with .png images. 

.png images are not keeping transparent background. Could it be something wrong with the library? 

Thanks!

**Comment by ArthurHub** [comment]
by default the library output image format is gif, but you can change it to png.

**Comment by martinbaciga** [comment]
Ok thanks for your reply. But how can i do that?

**Comment by ArthurHub** [comment]
```
CropImage.activity(imageUri)
        .setOutputCompressFormat(Bitmap.CompressFormat.PNG)
        .start(this);
```

**Comment by martinbaciga** [comment]
Ok, thanks i will try that.

**Comment by Mr-Ramzan** [comment]
> .setOutputCompressFormat(Bitmap.CompressFormat.PNG)

Any Luck?
