### ISSUE TITLE
Crop image in portrait Image

### ISSUE THREAD

**Issue by anhtth** [ArthurHub/Android-Image-Cropper#196]
I have a portrait photo take from LG G3, I move crop rect to top left of the image and then press crop.The crop image is fine but when I call result.getCropRect() it return a rect with left = 0, top = 468. I think when crop rect in top left the rect should be left = 0, top = 0. Please help me

**Comment by ArthurHub** [comment]
The photo (probably) has exif rotation data, so the image was rotated when it was shown for cropping.
If you request the raw crop rectangle then you will receive the original coordinates, otherwise, you will try to crop and get the wrong part of the image.

**Comment by georgesamuel96** [comment]
how can I get the raw crop rectangle? @ArthurHub
