### ISSUE TITLE
compileSdkVersion 22 fails

### ISSUE THREAD

**Issue by stefanb22** [ArthurHub/Android-Image-Cropper#198]
I'd love to use your library but when I include it in gradle I fail the gradle sync with compileSdkVersion 22.
It works if I use compileSdkVersion 23 but I currently have no time to adapt to all the changes in Marsmallow. Is there anyway of getting around this?

**Comment by ArthurHub** [comment]
Interesting, to be honest, I don't know what are the implications of lowering the target SDK version...
How will it affect existing devs?
How do other libraries handle it? Looking at another popular cropping library it also targets 24...
It is very easy for you to just fork it and change only this value.

**Comment by sunshinetpu** [comment]
@stefanb22 You should clone the project. Then decrease the compileSdkVersion to 22 and add the "cropper" as a module.

**Comment by ArthurHub** [comment]
@sunshinetpu I know it is always an option to clone a project, but is it the correct option to use in you opinion?
