### ISSUE TITLE
Transparency on PNG

### ISSUE THREAD

**Issue by joaquinlateral** [ArthurHub/Android-Image-Cropper#202]
Hi! I know this subject has been replied before but I still have a situation using your library and trying to get a cropped transparent PNG. I'm using the attached file to be cropped and this is how I call the library:

CropImage.ActivityBuilder cropImageActivityBuilder = CropImage.activity(imagePath);

			if (squareAspect)
			{
				cropImageActivityBuilder.setAspectRatio(100, 100)
						.setFixAspectRatio(true);
			}

			cropImageActivityBuilder
					.setGuidelines(CropImageView.Guidelines.ON)
					.setAutoZoomEnabled(false)
					.setOutputUri(croppedImage)
					.setOutputCompressFormat(Bitmap.CompressFormat.PNG);

			Intent intent = cropImageActivityBuilder.getIntent(mCallerActivity);
			mCallerActivity.startActivityForResult(intent, mRequestId);

Everytime I get the transparent PNG file with the transparent pixels replaced by black ones. Have anyone got into a similar situation? Is this an expected behavior for this library?

I've tried the sample app and it does not return the image with the transparent pixels replaced by black ones but I'm really confused at this point because I've checked my code and the image enters as a transparent background PNG and the one I get is the same but with the problem I describe above.

![dona](https://cloud.githubusercontent.com/assets/9967571/20577270/4e50f496-b1a0-11e6-8fde-9a98a4672b64.png)

**Comment by ArthurHub** [comment]
I have retested the flow for PNG again in the "quick-start" sample app and it works, that is, transparent pixels remain transparent.
From a technical perspective, the only place when bitmap can drop the transparent data is when it is saved. At this point, the raw pixels are encoded into the target format, if PNG is used then the transparent data is encoded, and that's what I have seen.
So I don't have an answer for you on what can go wrong except, the library is 100% supports transparent data in PNG format and I'm open if you prove otherwise.

**Comment by Hitesh12345678** [comment]
i have same problem above. when selecting png image with background transparent from gallery, the transparent parts get black after cropping image. 
you can see the below screen shot i have attached. @ArthurHub 
![screenshot_20181207-131431](https://user-images.githubusercontent.com/38131352/49634307-51064e80-fa22-11e8-8c8a-4f19382a0533.png)

**Comment by shubhamnandanwar** [comment]
I am also facing the same problem

**Comment by Mr-Ramzan** [comment]
> Hi! I know this subject has been replied before but I still have a situation using your library and trying to get a cropped transparent PNG. I'm using the attached file to be cropped and this is how I call the library:
> 
> CropImage.ActivityBuilder cropImageActivityBuilder = CropImage.activity(imagePath);
> 
> ```
> 		if (squareAspect)
> 		{
> 			cropImageActivityBuilder.setAspectRatio(100, 100)
> 					.setFixAspectRatio(true);
> 		}
> 
> 		cropImageActivityBuilder
> 				.setGuidelines(CropImageView.Guidelines.ON)
> 				.setAutoZoomEnabled(false)
> 				.setOutputUri(croppedImage)
> 				.setOutputCompressFormat(Bitmap.CompressFormat.PNG);
> 
> 		Intent intent = cropImageActivityBuilder.getIntent(mCallerActivity);
> 		mCallerActivity.startActivityForResult(intent, mRequestId);
> ```
> 
> Everytime I get the transparent PNG file with the transparent pixels replaced by black ones. Have anyone got into a similar situation? Is this an expected behavior for this library?
> 
> I've tried the sample app and it does not return the image with the transparent pixels replaced by black ones but I'm really confused at this point because I've checked my code and the image enters as a transparent background PNG and the one I get is the same but with the problem I describe above.
> 
> ![dona](https://cloud.githubusercontent.com/assets/9967571/20577270/4e50f496-b1a0-11e6-8fde-9a98a4672b64.png)

Any Luck? please help

**Comment by Mr-Ramzan** [comment]
> i have same problem above. when selecting png image with background transparent from gallery, the transparent parts get black after cropping image. you can see the below screen shot i have attached. @ArthurHub ![screenshot_20181207-131431](https://user-images.githubusercontent.com/38131352/49634307-51064e80-fa22-11e8-8c8a-4f19382a0533.png)

Facing same issue Can you provide any guidance?

**Comment by websoftstar** [comment]
Try this CropImage.activity().setOutputCompressFormat(Bitmap.CompressFormat.PNG).setAspectRatio(1,1).start(this);
