### ISSUE TITLE
brother i am not getting bitmap image

### ISSUE THREAD

**Issue by immyemperor** [ArthurHub/Android-Image-Cropper#203]
result.getBitmap() is returning null...expected to return bitmap image

**Comment by ArthurHub** [comment]
Activity will always return uri only, you can load bitmap from it ([see this](https://github.com/ArthurHub/Android-Image-Cropper/issues/193))

**Comment by immyemperor** [comment]
thanks but i figured it out my own..i took uri and converted it into bitmap..now fully working...thanks for sharing your code
