### ISSUE TITLE
Could not find any version that matches com.theartofdev.edmodo:android-image-cropper:+

### ISSUE THREAD

**Issue by santoshneo** [ArthurHub/Android-Image-Cropper#206]
when i'm adding compile 'com.theartofdev.edmodo:android-image-cropper:2.3.+' to my gradle file im getting:

` Could not find any version that matches com.theartofdev.edmodo:android-image-cropper:+.`

For more details please check [here](http://stackoverflow.com/questions/40856947/could-not-find-any-version-that-matches-com-theartofdev-edmodoandroid-image-cro).

**Comment by ArthurHub** [comment]
[yep :)](http://stackoverflow.com/a/40857016/651336)
