### ISSUE TITLE
 "CAMERA" Failure to write file

### ISSUE THREAD

**Issue by muhammad-usman-tatla** [ArthurHub/Android-Image-Cropper#209]
I am using lg g-pro android version 5.0.1, When I select camera as source and take snap, Toast shows Saying "Failure to write file" and it doesn't redirect to cropping activity. 
I have given <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> this permission.

When I changed device to Samsung Grand prime 5.1.1 | Nexus 6 | GenyMotion Emulator Samsung S3. App runs fine on them i.e it takes camera snap then crop activity start and I got image.

**Comment by ArthurHub** [comment]
Check logcat, it is possible you require `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

**Comment by muhammad-usman-tatla** [comment]
i have mentioned this permission in manifest, and noting logs on logcat.

**Comment by ArthurHub** [comment]
Try using a different path to save the image to, you will need to create the intent manually.
And... Google and experiment.. let me know what you find out and if there is something I can add to the library to handle this case or document it.
