### ISSUE TITLE
Cropping directly without using the activity?

### ISSUE THREAD

**Issue by jojonarte** [ArthurHub/Android-Image-Cropper#212]
Does this library have the function to just pass the rectangles and the image and apply the crop and return the image?

**Comment by amityadav0910** [comment]
Yes it does, pass your imageURI and your options using the below code

`CropImage.activity(imageURI)
                    .setGuidelines(CropImageView.Guidelines.ON)
                    .setAspectRatio(16, 9)
                    .setActivityTitle("Crop Image")
                    .start(this);`

Then get the result/cropped image using onActivityResult() 

` @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            if (resultCode == RESULT_OK) {
                Uri resultUri = result.getUri();
                imageView.setImageURI(resultUri);

            } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                Exception error = result.getError();
            }
        }
`

**Comment by amityadav0910** [comment]
Yes it does, pass your imageURI and your options using the below code

`CropImage.activity(imageURI) `
                   `.setGuidelines(CropImageView.Guidelines.ON) `
                   `.setAspectRatio(16, 9) `
                  ` .setActivityTitle("Crop Image") `
                   `.start(this);`

Then get the result/cropped image using onActivityResult()

`@Override`
`protected void onActivityResult(int requestCode, int resultCode, Intent data) {`
`super.onActivityResult(requestCode, resultCode, data);`

`if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {`
`CropImage.ActivityResult result = CropImage.getActivityResult(data);`
` if (resultCode == RESULT_OK) {`
`Uri resultUri = result.getUri();`

`imageView.setImageURI(resultUri);`
` } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {`
`Exception error = result.getError();`
       ` }`
   ` } `
