### ISSUE TITLE
Could I ask for a new version?

### ISSUE THREAD

**Issue by Rainer-Lang** [ArthurHub/Android-Image-Cropper#213]
Maybe something for xmas?

I found that this method is corrected: ```public Bitmap getCroppedImage(int reqWidth, int reqHeight) { return getCroppedImage(0, 0, RequestSizeOptions.RESIZE_INSIDE); }```
Sure I could use it directly....

**Comment by ArthurHub** [comment]
a bit late but 2.4.0 is out
