### ISSUE TITLE
Calling getImageUri after onGetCroppedImageComplete is null

### ISSUE THREAD

**Issue by EdgarMP** [ArthurHub/Android-Image-Cropper#215]
I am calling this method
`mCropImageView.getCroppedImageAsync();`

Getting callback in:
`public void onGetCroppedImageComplete(CropImageView view, Bitmap bitmap, Exception error) {
        if (error == null) {
            if (bitmap != null) {
                Log.wtf(TAG, "onGetCroppedImageComplete");
                mCropImageView.setImageBitmap(bitmap);

                Log.wtf(TAG, "onGetCroppedImageComplete "+mCropImageView.getImageUri()); //Null
                Log.wtf(TAG, "onGetCroppedImageComplete2 "+view.getImageUri()); //Null
                view.getImageUri();
                mCropImageView.setGuidelines(CropImageView.Guidelines.OFF);
                mCropImageView.setShowCropOverlay(false);
                isCroppedImage = false;
            }
        } else {
            Log.e("Crop",  "Failed to crop image", error);
            Toast.makeText(this,  "Something went wrong, try again", Toast.LENGTH_LONG).show();
        }
    }`

Calling `mCropImageView.getImageUri()` inside the callback throws null.

I know that I am only setting a new bitmap on mCropImageView but why can I get the Uri? is it the same at the beginning? Because I start my activity with this:

`mCropImageView.setImageUriAsync(mCropImageUri);`

Thanks!

**Comment by EdgarMP** [comment]
It is deprecated `CropImageView.OnGetCroppedImageCompleteListener`
However it still happens using `CropImageView.OnCropImageCompleteListener

`    @Override
    public void onCropImageComplete(CropImageView view, CropImageView.CropResult result) {
        Log.wtf(TAG, "onCropImageComplete");


        mCropImageView.setImageBitmap(result.getBitmap());

        Log.wtf(TAG, "onCropImageComplete "+result.getUri());
        mCropImageView.setGuidelines(CropImageView.Guidelines.OFF);
        mCropImageView.setShowCropOverlay(false);
        isCroppedImage = false;
    }`

**Comment by alizarei95** [comment]
result.getUri() is null here

**Comment by EdgarMP** [comment]
Sometimes is null because you need to wait until the reference is created
