### ISSUE TITLE
Save circular image

### ISSUE THREAD

**Issue by helloerika** [ArthurHub/Android-Image-Cropper#216]
It is possible to save the circular image from the circle fixed aspect ratio crop view?

**Comment by ignatiusbill** [comment]
+1. For me after cropping with circular option, the image comes out as a square/rectangle.

**Comment by Johnny850807** [comment]
+1 please><

**Comment by JacobMuchow** [comment]
@ArthurHub I ran into this problem today as well. I noticed the `CropImage.toOvalBitmap()` function, but it only accepts a Bitmap while the CropImageActivity result has only a Uri of course. It would be helpful to make an async version of the function that accepts a Uri or to expose your Bitmap loading task for use by the public.

**Comment by EmkaMk** [comment]
+1 please :)

**Comment by wallacerobertoc** [comment]
Use CircleImageView 
    compile 'de.hdodenhof:circleimageview:2.1.0'

**Comment by ArthurHub** [comment]
I know it looks like the easiest solution but it's not the correct one.
Your should use [CircleImageView](https://github.com/hdodenhof/CircleImageView) or similar solution.

**Comment by symphonyrecords** [comment]
possible solve #642
