### ISSUE TITLE
setOnClickListener and setOnTouchListener not working

### ISSUE THREAD

**Issue by ryee1** [ArthurHub/Android-Image-Cropper#218]
When using com.theartofdev.edmodo.cropper.CropImageView as a croppable imageview, I'm not able to receive touch or click events for the cropimageview. The listener does not seem to trigger at all.

What can I do to receive touch and click events?

**Comment by leduyhung** [comment]
In my way, you can set touch when you set setTouchscreenBlocksFocus is false and setShowCropOverlay is false. hope that help, and waiting for new version !

**Comment by ryee1** [comment]
Thanks, but without the crop overlay the croppable imageview isn't useful to me.
