### ISSUE TITLE
not able to start from fagment.

### ISSUE THREAD

**Issue by aalap03** [ArthurHub/Android-Image-Cropper#219]
After taking picture from custom camera which extends fragment, I am trying to start CropImageActivity but the start method is unresolved with the possible attempts made to start from fragment as per your description. 
// for fragment (DO NOT use `getActivity()`)
CropImage.activity(imageUri)
   .start(getContext(), this);

    public class MyFragment extends Fragment{
    Camera.PictureCallback mPicture = new Camera.PictureCallback() {
        @Override
        public void onPictureTaken(byte[] data, Camera camera) {
            Log.d(TAG, "onPictureTaken: ");
            photo = getOutputMediaFile();
            if (photo != null) {
                try {
                    FileOutputStream fos = new FileOutputStream(photo);
                    fos.write(data);
                    fos.flush();
                    fos.close();

                    CropImage.activity(Uri.parse(photo.getAbsolutepath()))
       .start(getContext(), this); //obviously doesnt work as I am in anonymous class
    possible tried options but it says cant resolve start method...
    .start(getContext(), MyFragment.this)
    .start(getContext(), MyFragment.class)
    .start(getContext(), new MyFragemnt(), MyFragment.class) //shows error for second parameter as it needs support fragment and mine is .app one.
    .start(getContext(), new MyFragment())
    .start(getContext(), (Fragment) new MyFragment()) //extended fragment is of android.app class

                 } catch (IOException e) {
                    Log.d(TAG, e.getMessage());
                }
            }
        }
    };
}

**Comment by milen-3web** [comment]
Same here

**Comment by akshaywohlig** [comment]
same

**Comment by ArthurHub** [comment]
You probably used `android.app.Fragment` and not `android.support.v4.app.Fragment`.
I used `android.support.v4.app.Fragment` because I need API available from 11.
In 2.4.1 I have added overload to `start` method that accepts `android.app.Fragment` and restricts it using annotation to API 11.
Hope it solve the issue for you guys.
