### ISSUE TITLE
The ability to set a minimum \ maximum height/width 

### ISSUE THREAD

**Issue by SolaBe** [ArthurHub/Android-Image-Cropper#22]
How can i set min/max crop height ?

**Comment by ArthurHub** [comment]
currently you can't, will add it soon

**Comment by ArthurHub** [comment]
update: started working on it but ther is an issue with some current code so I will probably finish it in a week or so.

**Comment by esmas-antoni** [comment]
I wait for it too! :dancer: good library man :)

**Comment by ArthurHub** [comment]
See **1.2.0**
- Add min limit config on cropping window width/height in the UI (`cropMinCropWindowWidth`, `cropMinCropWindowHeight`)
- Add min/max config on cropping image result width/height (`cropMinCropResultWidthPX`, `cropMinCropResultHeightPX`, `cropMaxCropResultWidthPX` , `cropMaxCropResultHeightPX`)

*Note* the cropping image result min/max is in pixels and can effect the usability of the cropping UI if set to low values for large images.
I wasn't sure on the best way to approach it so let me know what your use case is.
