### ISSUE TITLE
How can I change "CROP"word ?

### ISSUE THREAD

**Issue by Francescogatto** [ArthurHub/Android-Image-Cropper#221]
How can I change "CROP" word using the library and the built-in activity?

**Comment by timothylcooke** [comment]
The short answer: I'm not sure.

It's defined in the library as `@string/crop_image_menu_crop`. According to [this answer](http://stackoverflow.com/a/4383517/2041550), it looks like you can override it by defining it in your project, though I'm not certain it will override the menu that's also defined in the library.

If you want to replace it with an image, add a drawable to your project called `@drawable/crop_image_menu_crop`.

**Comment by Francescogatto** [comment]
> It's defined in the library as @string/crop_image_menu_crop. According to this answer,

it's worked! Thanks
