### ISSUE TITLE
i want have blank space, you can help me?

### ISSUE THREAD

**Issue by abbasalim** [ArthurHub/Android-Image-Cropper#224]
hello,
i want a crop library that let user to crop image only if match width or match height also (2) : 

![untitled-1](https://cloud.githubusercontent.com/assets/2588914/22059771/735219f0-dd83-11e6-8c0e-7abcc73671bc.jpg)

you can help me?

**Comment by ArthurHub** [comment]
set cropping to square? see [wiki](https://github.com/ArthurHub/Android-Image-Cropper/wiki/FAQ)
or did I misunderstood your question?

**Comment by abbasalim** [comment]
no, i want user can crop a image with specific aspect ratio 
while select full of image with blank space

**Comment by ArthurHub** [comment]
This scenario is not supported.
I must say it's quite unique so I don't think I will have time supporting it.
If you decide to add the support in the library I would gladly accept a PR.
Good luck.
