### ISSUE TITLE
Overriding Rotation Exif parameter of mDegreesRotated with 0

### ISSUE THREAD

**Issue by oba2cat3** [ArthurHub/Android-Image-Cropper#227]
when using this method:
public void setImageBitmap(Bitmap bitmap, ExifInterface exif)
the rotation as read from the Exif data is set to private field mDegreesRotated.
then private field is later overwritten by the subsequent call (chain of calls to be precise) to setBitmap method with wrong parameter 0.
refer to line 1014
mDegreesRotated = degreesRotated;
This ignores the correct rotation.

**Comment by timothylcooke** [comment]
It certainly seems you've done a lot of work diagnosing this problem. I would suggest creating a pull request.

**Comment by oba2cat3** [comment]
While creating a Pull request is perhaps the best way to fix my particular use case upstream, it could break other use cases I was not aware of when going deep on the issue. The issue is in the end of the call chain, that many other setBitmap method calls use. 
I recommend a package maintainer take a closer look at this issue, and see how to fix for other use cases.

**Comment by ArthurHub** [comment]
That is a stupid, stupid bug :(
Gonna fix it shortly, thank you @oba2cat3 for pointing to the right place!

**Comment by ArthurHub** [comment]
fixed in 2.4.0
