### ISSUE TITLE
PaintUtil colors

### ISSUE THREAD

**Issue by saurabharora90** [ArthurHub/Android-Image-Cropper#23]
Is it possible to add a enhancement which would allow me to change the border, guidelines and corner colors? That would be helpful to use the brand identity colors.

Thanks

**Comment by ArthurHub** [comment]
sure, I think I will add it this week

**Comment by saurabharora90** [comment]
Great. Thanks

**Comment by ArthurHub** [comment]
Now available in [v1.1.1](https://bintray.com/arthurhub/maven/Android-Image-Cropper/1.1.1/view)
See attributes: 
- `borderLineThickness`
- `borderLineColor`
- `borderCornerThickness`
- `borderCornerOffset`
- `borderCornerLength`
- `borderCornerColor`
- `guidelinesThickness`
- `guidelinesColor`
- `backgroundColor`

Sorry it took so long.
