### ISSUE TITLE
Image Size should not vary based on distance between Android phone and Image while using Camera

### ISSUE THREAD

**Issue by manikavi** [ArthurHub/Android-Image-Cropper#233]
I wanna implement this Programatically. While taking Image in android phone,image size should not vary based on distance between Android Phone and Actual Image,

for example,If distance between Android Phone and View is more ,then taken Image will look Big,If distance is less,then image will look small.

Is there any way to implement this?

**Comment by cdchirag** [comment]
I'm facing the same problem. if i do big crop then it gives cropped image outside the specified zone and when i do small crop then it gives the perfect result. Kindly request any suitable solution for that.

**Comment by ArthurHub** [comment]
I'm sorry, I'm sure I understand the scenario.. I think example images will help clear it.
