### ISSUE TITLE
Can change the color of toolbar of crop image activity?

### ISSUE THREAD

**Issue by siddhi17** [ArthurHub/Android-Image-Cropper#234]
I want to change the color of toolbar in crop image activity, which is black by default, can I change it?

**Comment by gworkman** [comment]
Yeah, if you change the style of the crop image activity in the manifest it will change the color of the toolbar. For example, you can use the following theme:

    <style name="CropTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/yourColor</item>
        <item name="colorPrimaryDark">@color/yourColorDark</item>
        <item name="android:windowBackground">@color/yourWindowBackgroundColor</item>
    </style>

and then in the manifest change the activity to 

    <activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
            android:theme="@style/CropTheme"/>

**Comment by ArthurHub** [comment]
see [wiki](https://github.com/ArthurHub/Android-Image-Cropper/wiki)
