### ISSUE TITLE
How to handle Multiple OnActivityResult() ??

### ISSUE THREAD

**Issue by AkhilTMohan** [ArthurHub/Android-Image-Cropper#236]
if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {//how to handle multiple result?
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            if (resultCode == RESULT_OK ) {
                Toast.makeText(getActivity(), "result Crop", Toast.LENGTH_SHORT).show();
                Uri resultUri = result.getUri();
                Toast.makeText(getActivity(), resultUri.toString(), Toast.LENGTH_SHORT).show();
                profImage.setImageURI(resultUri);
            } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                Exception error = result.getError();
            }
        }

**Comment by ArthurHub** [comment]
See [wiki](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Using-built-in-CropImageActivity) on how you get use the intent to start crop activity with custom request code.
