### ISSUE TITLE
How can I show cropped image on the screen?

### ISSUE THREAD

**Issue by timbuktu031** [ArthurHub/Android-Image-Cropper#239]
cropImageView.setImageUriAsync(uri);

Where should I put this line?

**Comment by MountainNine** [comment]
hello, did you solve the problem? How?

**Comment by timbuktu031** [comment]
sorry . I do not remember how I did it because it was a long time ago.

2017-05-27 14:25 GMT+09:00 MountainNine <notifications@github.com>:
