### ISSUE TITLE
Ability to set an initial crop rectangle

### ISSUE THREAD

**Issue by Actify** [ArthurHub/Android-Image-Cropper#24]
Hi, is there a way to set an initial crop rectangle, for example set at 100% of the image?
Thanks

**Comment by ArthurHub** [comment]
Not yet, 
I'm going to add customization to the margin of the initial cropping window
currently it is 10% of the image
setting it to 0 will achieve what you want
probably will add it this or next week

**Comment by Actify** [comment]
Thank you for your quick reply! I'll wait for it so!

**Comment by ArthurHub** [comment]
Added `cropInitialCropWindowPaddingRatio` [0 - 0.5) in **1.2.0**
