### ISSUE TITLE
App crashes with TransactionTooLargeException when onRestoreInstanceState called

### ISSUE THREAD

**Issue by AZaiats** [ArthurHub/Android-Image-Cropper#244]
#### Problem
After putting large bitmap to the Parcelable `TransactionTooLargeException` will be thrown.
You are putting bitmap in `onRestoreInstanceState` method:
`bitmap = (Bitmap)bundle.getParcelable("SET_BITMAP");` 
[Google doc](https://developer.android.com/reference/android/os/TransactionTooLargeException.html) about `TransactionTooLargeException`:
`The Binder transaction buffer has a limited fixed size, currently 1Mb, which is shared by all transactions in progress for the process. Consequently this exception can be thrown when there are many transactions in progress even when most of the individual transactions are of moderate size.`

#### Steps to reproduce
* Turn on "Don't keep activities" option in developer options
* Open Editor Activity with large photo
* Press home button to minimize application
* Open it from recents
* `TransactionTooLargeException` will be thrown

#### Possible solution:
* Never put bitmap to the Parcelable and load it again when the view restores.

**Comment by PohilAlex** [comment]
Agree. Passing bitmap through Parcelable is bad practice.

**Comment by ArthurHub** [comment]
I agree, it an issue, I was aware of it when I wrote the code.
But simply not doing it is not a solution, what should happen then on activity restore? Show error as we don't have an image to crop anymore?
So the proper solution is to not set bitmap object for multiple reasons (memory optimization), if you use uri then only the uri will be stored is the parcel.
Another option is to save the image to disk and then load, basically, I was too lazy to do though..
make sense?

**Comment by ankitbatra11** [comment]
It's very much common almost 70% of my app users were hitting this because of decently sized bitmaps.

**Comment by ArthurHub** [comment]
Sorry, I mean to use bitmap object instead of URI.
If you use `setImageUriAsync` API you won't get this issue and the user experience will be much better.

**Comment by ArthurHub** [comment]
fixed in 2.4.3

**Comment by ankitbatra11** [comment]
@ArthurHub Thanks. Verified the fix.
