### ISSUE TITLE
scale down the guidelines window ?

### ISSUE THREAD

**Issue by TharakaDamayantha** [ArthurHub/Android-Image-Cropper#245]
First thank you very much for this awesome library. 
When i set 
 cropImageView.setScaleX((float)1.5);
 cropImageView.setScaleY((float)1.5);
image get zoomed but the problem is guidline window(whole cropimageview view is scaling so) is also larger than the actual display size. So the edges are not easy to touch because they are out of the current display area. I need a way to set guidline window to small size when i scale the image. I checked but i couldn't find any method in library to scale that down. Or is there a another way to zoom image( without touching the screen) while keep the guidline window edges inside the display? i hope you got my problem thanks

ps: and thanks for adding image flip operations 👍 👍

**Comment by ArthurHub** [comment]
the library uses auto-zoom so it zooms when the crop rectangle is small and zoom-out when is large (compared to the available area).
so what you are asking will break this functionality, I don't see how I can expose setting zoom level.

**Comment by TharakaDamayantha** [comment]
ok point taken . will take a another way. thanks for ur time.
