### ISSUE TITLE
CropImageView.getCropRect() returns null

### ISSUE THREAD

**Issue by j-garin** [ArthurHub/Android-Image-Cropper#246]
Hello.
I am using this library, version 2.3.1 and built a custom image cropper activity. It only contains a toolbar and a CropImageView.

When crop icon is clicked in toolbar, i call:
```
					int width;
					int height;
					width = cropImageView.getCropRect().width();
					height = cropImageView.getCropRect().height();
					if (width == Math.max(width, height)) {
						width = maxDimension;
						height = maxDimension * height / cropImageView.getCropRect().width();
					} else {
						height = maxDimension;
						width = maxDimension * width / cropImageView.getCropRect().height();
					}
					cropImageView.saveCroppedImageAsync(resultUri, Bitmap.CompressFormat.PNG, COMPRESS_QUALITY, width, height);

```
and my cropImageView.getCropRect() returns null which causes a NullPointerException. What could be wrong and how can i fix this issue? Thank you.

**Comment by ArthurHub** [comment]
that can only happen if no image was loaded in the `CropImageView`..
