### ISSUE TITLE
Question: setMinimumHeight for cropView area

### ISSUE THREAD

**Issue by Scrounger** [ArthurHub/Android-Image-Cropper#248]
@ArthurHub 
Im using the follwing view in my activity:
```
<com.theartofdev.edmodo.cropper.CropImageView xmlns:custom="http://schemas.android.com/apk/res-auto"
                        android:id="@+id/cropImageView"
                        android:layout_width="match_parent"
                        android:layout_height="0dp"
                        android:layout_weight="1"
                        custom:cropBorderCornerOffset="0dp"
                        custom:cropBorderCornerThickness="0dp"
                        custom:cropBorderLineColor="@color/colorPrimary"
                        custom:cropBorderLineThickness="3dp"
                        custom:cropGuidelinesColor="@color/ticker_neutral"
                        custom:cropGuidelinesThickness="1dp"
                        custom:cropSnapRadius="0dp"
                        android:layout_marginBottom="4dp"/>
```

Is it possible to set a minimum height for the whole view (=cropping area, i dont mean the MinCropWindowWidth)? Because on small images <40px the area is very large

**Comment by ArthurHub** [comment]
I'm not sure what you mean, can you post at image?

**Comment by Scrounger** [comment]
@ArthurHub 
![example](https://cloud.githubusercontent.com/assets/6370451/24849386/c70b91b0-1dcb-11e7-9342-214fe0f8e010.png)

As you can see in the screenshot the CropImageView is very small on small images. So i would like to set a minWidth and a minHeight for the CropImageView (grey area in the picture).
I tried using minWidth and minHeight but it has no effect. Only solution was to set a fix height with contra for big images.

**Comment by ArthurHub** [comment]
I see, what about setting `CropImageView` to match parent and using [ScaleType](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Visual-Customization#scaletype) so the coriing image will fit in all available space?

**Comment by Scrounger** [comment]
@ArthurHub:
Ok i tried a lot also with scaleTypes, but without success. minWidth is not recognize by the CropImageView.
Only solution is to set a fixed hight (e.g. layout_height="200dp"), but thats bad for bigger images where the height is greater than 200. Also tried to set the CropImageView as subItem in LinearLayout and RelativeLayout with minHeight, no success.

I need a method to set the minHeight for CropImageView, so if the image is smaller then the minHeight, image should be strechted to minHeight keeping the aspect ratio.

**Comment by ArthurHub** [comment]
I don't think there is a good way to support dynamic size for `CropImageView` I would suggest it should be `match_parent` and use parent layout to provide set size for it.
You can see how it works in the sample app, see in the image below how changing `ScaleType` from `CENTER_INSIDE` to `FIT_CENTER` stretched a smaller image to fit in the view.

![image](https://cloud.githubusercontent.com/assets/5463635/24860609/1659b6ac-1dfe-11e7-97c5-86ded6ba177e.png)

```xml
<com.theartofdev.edmodo.cropper.CropImageView
    android:id="@+id/cropImageView"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
```
```xml
<android.support.v4.widget.DrawerLayout
    android:id="@+id/drawer_layout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.theartofdev.edmodo.cropper.sample.MainActivity">

    <!-- main content view. -->
    <FrameLayout
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <!-- drawer view.... -->
    
</android.support.v4.widget.DrawerLayout>
```

**Comment by Abu-Abdullah** [comment]
@Scrounger 
ConstraintLayout might be an option to solve this. you can control the ratio between H/W e.g.
```
<android.support.constraint.ConstraintLayout
            xmlns:app="http://schemas.android.com/tools"
            android:layout_below="@+id/zones"
            android:padding="5dp"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_constraintDimensionRatio="H,1:1">

            <com.theartofdev.edmodo.cropper.CropImageView
                android:id="@+id/cropImageView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                custom:cropInitialCropWindowPaddingRatio="0"/>
        </android.support.constraint.ConstraintLayout>
```
ratio is 1:1 in this case. at lease you do not need to specify the H/W manually and at the same time it can extend to the real ratio of the image itself in a normal layout e.g. RelativeLayout, ScrollView .......
