### ISSUE TITLE
I want to use 2 image crops in single page

### ISSUE THREAD

**Issue by BishalSaha** [ArthurHub/Android-Image-Cropper#249]
**Sir please help
please begging for help i want to use 2 image crops but OnActivityResult() have errors
i want to have different aspect ratios**

**Comment by ArthurHub** [comment]
See the [wiki](https://github.com/ArthurHub/Android-Image-Cropper/wiki)
There should be no problem, you have to be clear on the issue though.

**Comment by burhankhanzada199888** [comment]
there is no solution in wiki for this issue
