### ISSUE TITLE
Resource naming collisions

### ISSUE THREAD

**Issue by loeschg** [ArthurHub/Android-Image-Cropper#25]
Currently in our app we have an attribute called `backgroundColor` which collides with the attribute in this library (https://github.com/ArthurHub/Android-Image-Cropper/blob/master/cropper/src/main/res/values/attrs.xml). Thoughts on changing this/adding prefixes to the attributes?

**Comment by ArthurHub** [comment]
sorry, fixing by adding `crop` prefix to all cropper resources

**Comment by loeschg** [comment]
Awesome! Thanks. If I happen to get around to this before, I'll open a PR.

**Comment by ArthurHub** [comment]
fixed in **1.2.0**
