### ISSUE TITLE
issue with android 7.0

### ISSUE THREAD

**Issue by Frankenstein666** [ArthurHub/Android-Image-Cropper#251]
since android 7.0, file:// scheme is now not allowed to be attached with Intent on targetSdkVersion 24 (Android Nougat). so we should send the URI through content:// scheme instead which is the URI scheme for Content Provider. how can we obtain file uri from the content:// uri and pass to cropImage Activity Builder???

**Comment by ArthurHub** [comment]
I'm not sure what doesn't work.
[Uri.fromFile](https://developer.android.com/reference/android/net/Uri.html#fromFile(java.io.File)) API is not deprecated and running find in an emulator...
I just tested the library sample and quick-start on 7.1.1 emulator and everything works fine...

**Comment by Frankenstein666** [comment]
When i try to pass the content:// uri to cropImage.activity(uri) nothing happens(CropActivity is not launching).I can log the uri in onActivityResult(), i don't know what the issue is.

**Comment by ArthurHub** [comment]
can you provide code snippet so I can reproduce the issue?

**Comment by Frankenstein666** [comment]
```
private Uri mImageCaptureUri;
private static final int PICK_FROM_CAMERA = 1;
``` 

// function to open camera application
```
 if (Build.VERSION.SDK_INT >= 24) {             
      File file=newFile(Environment.getExternalStorageDirectory(),""+String.valueOf(System.currentTimeMillis()) + ".jpg");             mImageCaptureUri=FileProvider.getUriForFile(this,BuildConfig.APPLICATION_ID+".provider", file);
                    intent.putExtra(android.provider.MediaStore.EXTRA_OUTPUT, mImageCaptureUri);
                    try {
                        startActivityForResult(intent, PICK_FROM_CAMERA);
                    } catch (ActivityNotFoundException e) {
                        e.printStackTrace();
                    }
                }
```

//onActivityResult

```
@Override
    protected void onActivityResult(int reqCode, int resultCode, Intent data) {
        super.onActivityResult(reqCode, resultCode, data);
        switch (reqCode) {
case PICK_FROM_CAMERA:
                    if (resultCode == RESULT_OK) {
                    if (Build.VERSION.SDK_INT >= 24) {
                        CropImage.activity(Uri.parse(mCurrentPhotoPath))
                                .setGuidelines(CropImageView.Guidelines.ON)
                                .setActivityTitle("Crop Image")
                                .setFixAspectRatio(true)
                                .setBorderLineThickness(2.0f)
                                .setBorderLineColor(getResources().getColor(R.color.colorPrimary))
                                .start(this);
                    }
             
                }
                break;


}

```

The Crop Image Activity is not launcing as expected. it was working fine below android N.

**Comment by ArthurHub** [comment]
Looks like you are passing `mCurrentPhotoPath` to `CropImage.activity` but I don't see how you create it.
Seems like you should use `mImageCaptureUri` that is used for the camera intent.
Do you check if you get an error result?

**Comment by Frankenstein666** [comment]
Nevermind it's working now, it seems like  i misconfigured the File Provider Path.
