### ISSUE TITLE
how to get current image in cropImageview (not cropped) to bitmap?

### ISSUE THREAD

**Issue by TharakaDamayantha** [ArthurHub/Android-Image-Cropper#253]
First thanks for awesome library. what i want to do is i need to get the image shown(not the cropped one) in cropimageview into bitmap so then i can do some operations on it. i tried going through your methods still didn't get any method to do this. can you please let me know how to achieve this?

**Comment by TharakaDamayantha** [comment]
hello anybody ? :(

**Comment by ArthurHub** [comment]
Do you want to manipulate the shown image during cropping? why?
I don't think it's a good idea as the image lifecycle is controlled by the view and it may not be used in  cropping.

**Comment by TharakaDamayantha** [comment]
thanks for reply sir. yes my requirement is after zooming / rotating i need to get the bitmap from cropimageview without cropping. then i can add more user features in the app. anyway now i decided to remove the zoom/rotate/flip features from my app . so no need to worry on that. thanks for nice library sir.

**Comment by ArthurHub** [comment]
Well just to be clear, you do want to crop the image if you want just the zoomed area...
`CropImageView` doesn't change the bitmap during zoom/rotation.
Either way I guess it's a moot point now.

**Comment by TharakaDamayantha** [comment]
mmm no i don't want to crop the image( i want that but forget it for now :) )  what i want is do operations zoom,flip,rotate on image using CropImageView and take the image from that as bitmap. currently we only can get the image from cropimageview by getcroppedimage after cropping right?  hope you got my idea here :)

**Comment by ArthurHub** [comment]
flip and rotate make sense though without cropping not really related to this library.
but zoom is a property of a current view, it's not image manipulation, what do you expect to happen?

**Comment by TharakaDamayantha** [comment]
"flip and rotate make sense though without cropping not really related to this library." yes ofcoz sorry if i am bothering you.  "but zoom is a property of a current view, it's not image manipulation, what do you expect to happen?" ok for clear picture i am making photo editing app so i need to give user the abilities like zoom in ,zoom out,rotate,flip and save/ share the image. anyway i have removed those features and added only crop feature (i added many other features so no problem xD ) to my app. i am not native English speaker so just i ignore if i am not answering your questions properly . 

And there are this other two problems that seems to be a bug and i will post them in another thread. thanks for your precious time.
