### ISSUE TITLE
Bitmap too large to be uploaded...

### ISSUE THREAD

**Issue by IlynPayne** [ArthurHub/Android-Image-Cropper#254]
When I try to open a bitmap in `CropImageView`, the logcat is being flooded by the following warnings:
```
W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (4160x3120, max=4096x4096)
```

Resizing the bitmap before passing it to View isn't an ideal solution.

**Comment by ArthurHub** [comment]
Are you using `setImageBitmap` or `setImageUriAsync` API?

**Comment by IlynPayne** [comment]
I'm using `setImageBitmap`.

**Comment by ArthurHub** [comment]
that's the reason, the library doesn't manipulate the bitmap object.
I would strongly advise using the URI API, you get a lot of enhancements like handling max texture size, memory, etc.

**Comment by IlynPayne** [comment]
I see, but unfortunately some Bitmaps I'd like to process don't even reside in mass storage - they are created by `MediaProjection` API.

Anyway, thanks for clarification and quick response.
