### ISSUE TITLE
How to call only camera Intent?

### ISSUE THREAD

**Issue by rahulwadhai** [ArthurHub/Android-Image-Cropper#255]

**Comment by ArthurHub** [comment]
see [wiki](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Pick-image-for-cropping-from-Camera-or-Gallery) and `CropImage.getCameraIntent` method.

**Comment by core2root** [comment]
hi, i saw wiki but still no idea how to restrict the user to use only camera or only gallery

**Comment by mwshubham** [comment]
For those who are looking for the same. 
You need to call getCameraIntent which will simply give you an intent with action `android.media.action.IMAGE_CAPTURE` then on the result obtain you can call  ```
public static ActivityBuilder activity(@Nullable Uri uri) {
    return new ActivityBuilder(uri);
  }
```

e.g.  `CropImage.activity(uri).start(this)`

**Comment by rmeph13** [comment]
can u more explain it...i not able to use it...plz
