### ISSUE TITLE
Bug: elipsis get outside of its rectangular boundary

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ArthurHub/Android-Image-Cropper#256]
See this image:

![device-2017-04-19-114111](https://cloud.githubusercontent.com/assets/5357526/25171034/31472e88-24f5-11e7-9744-9b4cbbbb9261.png)

**Comment by ArthurHub** [comment]
thank you, will verify and fix.

**Comment by ArthurHub** [comment]
fixed in 2.4.1
