### ISSUE TITLE
Zoom interval

### ISSUE THREAD

**Issue by DavidMatos91** [ArthurHub/Android-Image-Cropper#258]
Hi there,

Is there any way to set a maximum and minimum zoom scale? 

Thanks!

**Comment by ArthurHub** [comment]
See [wiki](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Visual-Customization#maxzoom) for max-zoom.
There is no min-zoom, why do you need it?

**Comment by DavidMatos91** [comment]
Thanks for the response, somehow I missed the max-zoom property. The min-zoom feature would also be nice, to avoid the user to downsize the image to the point it's invisible. With min-zoom and max-zoom combined we could define a safe interval.

**Comment by ArthurHub** [comment]
hmm... the min-zoom should be 1... is it possible to zoom out more than original size?
