### ISSUE TITLE
when capture image from camera some time it crash..?

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [ArthurHub/Android-Image-Cropper#259]
java.lang.RuntimeException: Failed to load sampled bitmap: file:///storage/emulated/0/picture.jpg
                                                                                         /storage/emulated/0/picture.jpg: open failed: ENOENT (No such file or directory)

**Comment by ArthurHub** [comment]
are you sure it's a valid URI?
how do you create and use it?

**Comment by ArthurHub** [comment]
You may also check this one: #264
