### ISSUE TITLE
bug for mCropImageView.rotateImage(-30);

### ISSUE THREAD

**Issue by a371166028** [ArthurHub/Android-Image-Cropper#260]
when i set rotate  <0  some important bug ocurred    for example mCropImageView.rotateImage(-30);

**Comment by ArthurHub** [comment]
are you using the latest version?

**Comment by a371166028** [comment]
yes   ,i  updated  a  new  version   and  make sure for it.       hm... i set rotation -30   and  touch just


发自网易邮箱大师
On 04/21/2017 22:36, Arthur wrote:

are you using the latest version?

**Comment by ArthurHub** [comment]
bug, will fix soon, thanks

**Comment by ArthurHub** [comment]
fixed in 2.4.1

**Comment by a371166028** [comment]
i saw the bug exist 。 just setp follow  friend ：
1.open the MainFragment form module sample.
2. see   onOptionsItemSelected method :
`    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == R.id.main_action_crop) {
            mCropImageView.getCroppedImageAsync();
            return true;
        } else if (item.getItemId() == R.id.main_action_rotate) {
            _**mCropImageView.rotateImage(-20);**_
            return true;
        } else if (item.getItemId() == R.id.main_action_flip_horizontally) {
            mCropImageView.flipImageHorizontally();
            return true;
        } else if (item.getItemId() == R.id.main_action_flip_vertically) {
            mCropImageView.flipImageVertically();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }`
3. change line to *mCropImageView.rotateImage(-20); 
4 .now just run  sample and then click rotate button from toolbar right 
5. pressed the image cat and move (don't up)
6.click rotate  again
7.now all you would see something what i want to show you. 
8.thanks for your reading my dear friend.
