### ISSUE TITLE
Gradle Sync fails to resolve

### ISSUE THREAD

**Issue by PriyankSharma** [ArthurHub/Android-Image-Cropper#261]
Seemed to be working fine until last week. Now, all of a sudden, I’m getting this error when syncing:
**Failed to resolve: com.theartofdev.edmodo:android-image-cropper:2.4+**

along with,
**Failed to resolve: annotationProcessor**

**Comment by ArthurHub** [comment]
looks unrelated to the library, try updating gradle and sdk versions

**Comment by PriyankSharma** [comment]
My project has a lot of libraries. The issue was only with this one. Tried every possible solution. Finally, had to manually import your source code into my project (as a module) to get it to work.

**Comment by ArthurHub** [comment]
I can't reproduce it...

**Comment by ArthurHub** [comment]
Maybe it's related to latest support library, did you try updating to v25?
Also see [this](http://stackoverflow.com/questions/40703394/errorfailed-to-resolve-annotationprocessor)
If you find a solution please let me know.

**Comment by PriyankSharma** [comment]
Yes, I’m on the latest one. For now, you can close this thread as my issue is kinda resolved. I’ll report again if it happens on any of my future projects. Great library BTW. Cheers!
