### ISSUE TITLE
How to set orientation for CropActivity?

### ISSUE THREAD

**Issue by tuanbaros** [ArthurHub/Android-Image-Cropper#265]
Hi author, I using this library to crop image but I want to set orientation (portrait or landscape) for CropActivity, how to do it? :D thank you :D

**Comment by ArthurHub** [comment]
The [same way](http://stackoverflow.com/questions/4885620/force-portrait-orientation-mode) you would for any android activity.

**Comment by tuanbaros** [comment]
No, I want to set it when runtime, not setup in manifest?

**Comment by ArthurHub** [comment]
You need to call `setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)` in activity `onCreate`.
You need to extend 'CropImageActivity' to do that, and use the activity builder start overload to start your activity instead of the default.

**Comment by tuanbaros** [comment]
Ok, thank u

**Comment by shylendramadda** [comment]
> You need to call `setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)` in activity `onCreate`.
> You need to extend 'CropImageActivity' to do that, and use the activity builder start overload to start your activity instead of the default.

I created a new activity and set orientation in onCreate but how do I start my activity by passing an Image URL?

```
class LandscapeCropActivity : CropImageActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
    }
}
```

This is how started crop activity earlier:

`CropImage.activity(Uri.fromFile(File(filePath))).start(this)``
