### ISSUE TITLE
How to zoom image to crop, not autozoom?

### ISSUE THREAD

**Issue by tuanbaros** [ArthurHub/Android-Image-Cropper#266]
I want zoom image to crop but not autozoom, how to do it? thank for best crop library :D

**Comment by ArthurHub** [comment]
At the moment only auto-zoom is supported, do you have a scenario where it is not appropriate? what method would you like to use?

**Comment by tuanbaros** [comment]
why must be autozoom? it really convinient? why not zooming is control by user?

**Comment by ArthurHub** [comment]
I think it's the preferred UX, that why I implemented it.
I'm not planning to add another zoom mechanism, if you are willing to write the code I will appreciate it.

**Comment by tuanbaros** [comment]
So Ok, thank u
