### ISSUE TITLE
Problem with rotate 

### ISSUE THREAD

**Issue by albka1986** [ArthurHub/Android-Image-Cropper#267]
After making a photo from camera on portrait mode, the image is rotate in landscape mode. How can I fix it? Help me please.

**Comment by ArthurHub** [comment]
It is probably because the image has exif data, if you open the image in any viewer you should also see it rotated.
If this is not the case please provide the image original file so I can check it.

**Comment by danikula** [comment]
[`getFileFromUri`](https://github.com/ArthurHub/Android-Image-Cropper/blob/master/cropper/src/main/java/com/theartofdev/edmodo/cropper/BitmapUtils.java#L625) method checks only `file://` and standard media `content://` uris. If uri come from some custom file provider it won't work. So you need to get content from uri's input stream by `getContentResolver().openInputStream(source);` and then save it to file to get change `ExifInterface` read correct rotation. If you want I can prepare PR.

**Comment by Yury-D** [comment]
```
 InputStream is = context.getContentResolver().openInputStream(uri);
 ExifInterface ei = new ExifInterface(is);
```
Works fine. Please add if into rotateBitmapByExif

**Comment by ArthurHub** [comment]
I would really love a PR, also if you can post a simple repro I would appreciate it.
Thank you!

**Comment by danikula** [comment]
@ArthurHub, please take a look to PR.

**Comment by j-garin** [comment]
@ArthurHub could you please notify me when you release a new version with this fix? Thank you.

I am using lib version 2.4.3 and this is still an issue (TargetAPI 25, tested on API 22 device, custom ContentProvider).

Glide loads the image in correct orientation, this lib doe not, image appears rotated.

**Comment by joshkendrick** [comment]
I believe I also was experiencing the issue described here and the master branch seems to have the fix.

Testing on a Samsung S7, if I open the camera (not using Crop lib) and take a picture in portrait, and send the uri of that photo to the Crop activity, the photo appears landscape in the cropper. This was with Crop lib 2.4.3

I checked out the project and imported it into our project and tried the same flow with the master branch and the problem seems to be resolved.

A 2.4.4 would be greatly appreciated :) -- it's a great project! I'm glad it's available

**Comment by ArthurHub** [comment]
Published 2.4.4
Huge thanks for all the help with this issue.

**Comment by j-garin** [comment]
@ArthurHub works perfectly. Thank you. Keep up the good work!

**Comment by AbhilashReddy17** [comment]
I am still facing the same issue it loads on to the imageview as is cropped perfectly but when i upload it into server its again an rotated image how do i solve this...

**Comment by ArthurHub** [comment]
@AbhilashReddy17 it's not the same issue, please open a new issue and provide more details

**Comment by AbhilashReddy17** [comment]
@ArthurHub sure will do sorry for posting it here
