### ISSUE TITLE
Rotation issue with postRotate on CropImageView 

### ISSUE THREAD

**Issue by riclage** [ArthurHub/Android-Image-Cropper#274]
I have an image that is rotated 270 degrees. It loads correctly and the rotation is detected and assigned to `mDegreesRotated`.

However, on `applyImageMatrix()`, this code is puzzling:

```
// rotate the image the required degrees from center of image
if (mDegreesRotated > 0) {
    mImageMatrix.postRotate(mDegreesRotated, BitmapUtils.getRectCenterX(mImagePoints), BitmapUtils.getRectCenterY(mImagePoints));
    mapImagePointsByImageMatrix();
}
```

Why rotate the image by the amount of degrees the image is already rotated? We should rotate the image only once by `360 - mDegreesRotated`, no?

The other issue is that the `applyImageMatrix()` method is currently being called twice: once from `onSetImageUriAsyncComplete()` and then again from `onLayout()`. So my image is currently being rotated by 540 degrees.

**Comment by ArthurHub** [comment]
The matrix is used to apply transformation during rendering of the image in `ImageView`, the actual image is never rotated.
Note that `applyImageMatrix()` resets the matrix in the beginning before calculating the proper transformation (`mImageMatrix.reset();`).

Do you see an issue?

**Comment by riclage** [comment]
Yes, this one image I have with 270 degrees rotation doesn't rotate properly. Will investigate this further and report back.

Thanks.
