### ISSUE TITLE
Intent.ACTION_GET_CONTENT not working on 4.4.4

### ISSUE THREAD

**Issue by PingForward** [ArthurHub/Android-Image-Cropper#276]
```
    Intent target;
        if (allIntents.isEmpty()) {
            target = new Intent();
        } else {
            target = allIntents.get(allIntents.size() - 1);
            allIntents.remove(allIntents.size() - 1);
        }

        // Create a chooser from the main  intent
        Intent chooserIntent = Intent.createChooser(target, title);
```

Not working on 4.4.4 it shows "No apps can ..."

If use  getGalleryIntents(packageManager, **Intent.ACTION_PICK**, includeDocuments);
It shows the correct apps for all devices.

I think the problem is  here `target = allIntents.get(allIntents.size() - 1);`
kitkat can't open chooser with Intent.ACTION_GET_CONTENT

May be we need different  target intent to handle all versions?

**Comment by ArthurHub** [comment]
It's hard to say what will work for all versions / devices...
What is the content of `galleryIntents` after this code is executed?
```
List<Intent> galleryIntents = getGalleryIntents(packageManager, Intent.ACTION_GET_CONTENT, includeDocuments);
if (galleryIntents.size() == 0) {
    // if no intents found for get-content try pick intent action (Huawei P9).
    galleryIntents = getGalleryIntents(packageManager, Intent.ACTION_PICK, includeDocuments);
}
allIntents.addAll(galleryIntents);
```

**Comment by PingForward** [comment]
The gallery intent contains a six items (dropbox, gallery etc..) 

![default](https://cloud.githubusercontent.com/assets/17492722/25894792/f86f20a6-3585-11e7-8089-c2c0f237f1f6.PNG)

The problem is in target Intent. You use the last item from gallery intent to create the target one and all items use Intent.ACTION_GET_CONTENT which will show "No apps can perform this action" on old versions

**Comment by ArthurHub** [comment]
Initially, I have used empty intent as target, that didn't work for some devices.
Then, I used the first intent in the list, but that put it the last on the list.
So I used the last on the list.
What do you think the target intent should be?
