### ISSUE TITLE
Not showing list of source to select from like camera ,gallery,drive

### ISSUE THREAD

**Issue by arifnoumankhan** [ArthurHub/Android-Image-Cropper#277]
2 days back it was working fine .
CropImage.activity(null)
                .setGuidelines(CropImageView.Guidelines.ON)
                .setAutoZoomEnabled(true)
                .start(this);
by passing null it was poping up list to choose from source like camera ,gallery ,drive i was happy with that. so i removed manual intents from my code .
and now this is poping up empty screen with title Select Source

**Comment by ArthurHub** [comment]
Looks like regression in one of the minor version. 
Can you check in which version it started?
Thank you.

**Comment by arifnoumankhan** [comment]
the issue was with the gennymotion 2.8 verion with 2.9 its working like a charm thanks
