### ISSUE TITLE
Size Issue

### ISSUE THREAD

**Issue by dmp17** [ArthurHub/Android-Image-Cropper#28]
Some time when i zoom it will cross limit of window size.

![untitled](https://cloud.githubusercontent.com/assets/8749772/12883657/3fafc480-ce7f-11e5-9d87-ae62d5670bfb.png)

![untitled1](https://cloud.githubusercontent.com/assets/8749772/12883661/4787cdec-ce7f-11e5-942e-39eeb85a3719.png)

**Comment by ArthurHub** [comment]
Can you provide the configuration you used and/or the steps to reproduce
Thx

**Comment by dmp17** [comment]
This problem is also in your sample project. when i click outside of Guidelines than some time occurs this problem. i sets fixed aspect ratio.

**Comment by ArthurHub** [comment]
k, will fix it, thx

**Comment by ArthurHub** [comment]
fixed in **v1.2.1**
