### ISSUE TITLE
Is it possible to start the activity with a Bitmap object?

### ISSUE THREAD

**Issue by eugenio-caicedo** [ArthurHub/Android-Image-Cropper#280]
I think it is not possible for the latest version. But is it possible to solve this differently?

Summary a little my case: I have an activity that takes a photo with the help of the camera or select an image from the gallery. The idea is that if the image meets a maximum size, the app should call `CropImage.activity (imageUri).start (this);` with the selected image.

For the case of selecting the image of the gallery works perfectly. But for the case of taking a photo with the camera, the current try result returns:

````
intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
getActivity().startActivityForResult(intent, TAKE_PICTURE);

......

Bitmap bitmap = (Bitmap) data.getExtras().get("data");
````

**Comment by ArthurHub** [comment]
You don't really get the real image from camera by using `data.getExtras().get("data")`
See: https://github.com/ArthurHub/Android-Image-Cropper/wiki/FAQ#why-image-captured-from-camera-is-blurred-or-low-quality

**Comment by eugenio-caicedo** [comment]
Excellent. It works perfect. Thank you very much.
