### ISSUE TITLE
Can not compile via gradle

### ISSUE THREAD

**Issue by zzdjk6** [ArthurHub/Android-Image-Cropper#282]
I see following error messages after include this lib in gradle, can't build.

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

What should I do?

**Comment by ArthurHub** [comment]
http://stackoverflow.com/questions/17587751/gradle-execution-failed-for-task-processdebugmanifest

**Comment by zzdjk6** [comment]
Really appreciate! @ArthurHub
