### ISSUE TITLE
Deleting the crop button from the actionbar

### ISSUE THREAD

**Issue by Pantkowsky** [ArthurHub/Android-Image-Cropper#284]
Hey !

First of all, thanks for this great library !!

I however have one question. Is it possible to remove the crop button from the action bar (or disable it ?? )
I would much rather like to have a floating button than a button in the action bar.

**Comment by ArthurHub** [comment]
Create your own activity, you can inherit from the build-in and override whatever you like.

**Comment by eTechist** [comment]
@ArthurHub i have posted a doubt.Have seen my issue?
