### ISSUE TITLE
Image is rotated after uploading into the server

### ISSUE THREAD

**Issue by AbhilashReddy17** [ArthurHub/Android-Image-Cropper#285]
after cropping the image it is diplayed as is but after you upload into the server it was rotated, i figured it out that you have to save exif information before you upload into the server but it would be cool if we implement it in this library automatically

**Comment by AbhilashReddy17** [comment]
this link helped me out 
http://stackoverflow.com/questions/39515637/camera-image-gets-rotated-when-i-upload-to-server

**Comment by ArthurHub** [comment]
That shouldn't happen... when the image the actual bitmap is rotated as required and saved as you see it on the screen, no exif data should be required...

**Comment by AbhilashReddy17** [comment]
bu this happened with me , I used the intent to take picture from camera and then i stored that image on firebase later to display it on , i retrieved the image from firebase then when i am trying to display the image it was rotated, so i had to use the exif information before i upload it on to firebase

**Comment by AbhilashReddy17** [comment]
//for taking image

String timestamp = new SimpleDateFormat("yyyyMMddHHmmssSSS").format(new Date());
                                    String imageName = "IMG_"+timestamp+".jpg";

                                    File filesDir = getFilesDir();
                                    imageFilePointer = new File(filesDir,imageName);

                                    Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);

                                    boolean captureImage = imageFilePointer!=null && intent.resolveActivity(getPackageManager()) != null ;
                                    if(captureImage){

                                        Uri uri = FileProvider.getUriForFile(UserProfile.this,
                                                "abcd.com.abhilash.android.check.fileprovider",imageFilePointer);

                                        imageHoldUri = uri;
                                        intent.putExtra(MediaStore.EXTRA_OUTPUT,uri);

                                        //get list of all apps installed
                                        List<ResolveInfo> cameraActivities = getPackageManager().
                                                queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);

                                        for(ResolveInfo activity:cameraActivities){
                                            grantUriPermission(activity.activityInfo.packageName,uri,Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
                                        }

                                        startActivityForResult(intent,REQUEST_IMAGE_CAPTURE);


//capturing image
 if (requestCode == REQUEST_IMAGE_CAPTURE && resultCode == RESULT_OK) {

            Uri uri = FileProvider.getUriForFile(UserProfile.this,
                    "abcd.com.abhilash.android.check.fileprovider",imageFilePointer);

            Log.d("userprofile", "onActivityResult: "+uri.toString());

            CropImage.activity(uri).
                    setGuidelines(CropImageView.Guidelines.ON)
                    .start(UserProfile.this);

        }

**Comment by ArthurHub** [comment]
What image do you upload to the server? the one captured by camera or the result of crop activity?

**Comment by AbhilashReddy17** [comment]
@ArthurHub my bad i was loading the result from image captured by camera now i flipped the bits i am loading image from crop activity now , this works very fine thanks for the library Arthur. its very easy to use.
