### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by mittal-vivek** [ArthurHub/Android-Image-Cropper#287]
/home/sanganan10/AndroidProjects/Zui/zuibusinessandroid/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by jmgirven** [comment]
What `compileSdkVersion` / `buildToolsVersion` version are you using? I have just updated from 23 to 25 and the issue seems to have gone.

**Comment by ArthurHub** [comment]
I always update to the latest, you can see [build.gradle](https://github.com/ArthurHub/Android-Image-Cropper/blob/5ba4bbb3252fe286f3b5c37c98bfbd25972c1829/cropper/build.gradle#L15) in the repository.
