### ISSUE TITLE
Add getter for degreesRotated

### ISSUE THREAD

**Issue by hpoul** [ArthurHub/Android-Image-Cropper#29]
Hello,
we had a problem that on old memory limited devices we did not get a reasonable quality of cropped images (because we would have to limit the output size significantly to not have out of memory issues when the app is limited to 16MB ram) - so we decided the best option is to simply use the view to let the user choose a crop / rotation area and let the server do the heavy lifting. The only thing missing for this to work would be an accessor for `mDegreesRotated`. Seems like an easy improvement :)

thanks for keeping this view alive :)

regards,
  Herbert

**Comment by ArthurHub** [comment]
will do

**Comment by ArthurHub** [comment]
added in **v1.2.1**
