### ISSUE TITLE
Unable to retrive file While uploading to server

### ISSUE THREAD

**Issue by paragsarkar** [ArthurHub/Android-Image-Cropper#290]
Hi,

I was trying to upload the file to server after I got the image. Then cropped image we had is not getting uploaded to server its going to exception for file not exception. Please let me know if you have the solution.
TIA

**Comment by majidln** [comment]
what is solution for this problem?

**Comment by paragsarkar** [comment]
what i did is I saved the file in different folder after cropping and it from there I uploaded the image from that file to server using loopj library please make sure there you add another paramter in the requestParam as the mine majidin
