### ISSUE TITLE
Compilation error with gradle plugin 3.0.0-alpha2

### ISSUE THREAD

**Issue by bogdanflorianmihai** [ArthurHub/Android-Image-Cropper#292]
Hi,
I get this error with the gradle plugin 3.0.0-alpha2
`Error: java.lang.RuntimeException: com.android.builder.internal.aapt.AaptException: AAPT2 compile failed
ERROR: /Users/.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:728 invalid drawable
`
The problem seems to be: 
`<item name="crop_image_menu_crop" type="drawable"/>`

With gradle plugin 2.3.2 works fine.
Version 2.4.4
Thanks

**Comment by Rainer-Lang** [comment]
https://github.com/ArthurHub/Android-Image-Cropper/pull/291

**Comment by bogdanflorianmihai** [comment]
Sorry I didn't see that pull request
