### ISSUE TITLE
Is it possible to retrict the aspect ratio of the cropting area?

### ISSUE THREAD

**Issue by roostaamir** [ArthurHub/Android-Image-Cropper#294]
Hi
Is the possible to set a limitation for the aspect ratio (for example that only square images are accaptable) in addition to size limitations?

**Comment by ArthurHub** [comment]
Look for aspect ratio, see https://github.com/ArthurHub/Android-Image-Cropper/wiki/FAQ#how-can-i-set-crop-shape-to-squarecircle.
