### ISSUE TITLE
Can't load any image on Galaxy S8+

### ISSUE THREAD

**Issue by vulegend** [ArthurHub/Android-Image-Cropper#295]
Trying it out on my phone and whatever picture i'm selecting it just endlessly loads and nothing happens. 

I'm using this - 

        CropImage.activity()
                .setGuidelines(CropImageView.Guidelines.ON)
                .start(this);

I have both read and write permissions on the app so it shouldn't be a problem.

**Comment by vulegend** [comment]
It appears to be endlessly loading on all devices i've tested on.

**Comment by ArthurHub** [comment]
can you reproduce it on the sample app?

**Comment by ArthurHub** [comment]
and also try it with latest version 2.4.7
