### ISSUE TITLE
Accept CharSequence for title in ActivityBuilder class

### ISSUE THREAD

**Issue by KentHawkings** [ArthurHub/Android-Image-Cropper#297]
At the moment the `ActivityBuilder` class only accepts a `String` in the `setActivityTitle()` method. Ideally this would be a `CharSequence`. It's more "correct" since `ActionBar.setTitle()` accepts a `CharSequence`. Moreover, it would allow for more flexibility in theming the `CropImageActivity`. Some applications (such as my own) have a custom font so this would convenient in cases like those (and any other cases where users want to apply spans to an activity title).

**Comment by ArthurHub** [comment]
That is an excellent point, fixed in 2.4.7, thx
