### ISSUE TITLE
Fatal Exception on Samsung Devices

### ISSUE THREAD

**Issue by sairaapponative** [ArthurHub/Android-Image-Cropper#298]
While Using this lib , all devices  work perfectly fine. except Some Samsung devices where I get some weird error log for capturing or image pick. Below is error log:

Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.nest.mymaapp/com.nest.mymaapp.activities.StudentListActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.nest.mymaapp/com.nest.mymaapp.activities.StudentListActivity}: java.lang.IllegalArgumentException: Uri must be non null or empty
android.app.ActivityThread.performResumeActivity

android.app.ActivityThread.performResumeActivity (ActivityThread.java:4221)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4323)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3426)
android.app.ActivityThread.access$1100 (ActivityThread.java:229)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1821)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7325)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
Caused by java.lang.RuntimeException
android.app.ActivityThread.deliverResults (ActivityThread.java:4998)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:4207)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4323)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3426)
android.app.ActivityThread.access$1100 (ActivityThread.java:229)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1821)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7325)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
**Caused by java.lang.IllegalArgumentException
com.theartofdev.edmodo.cropper.CropImage.activity (CropImage.java:358)**
com.nest.mymaapp.activities.StudentListActivity.onActivityResult (StudentListActivity.java:751)
android.app.Activity.dispatchActivityResult (Activity.java:7165)
android.app.ActivityThread.deliverResults (ActivityThread.java:4994)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:4207)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4323)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3426)
android.app.ActivityThread.access$1100 (ActivityThread.java:229)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1821)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7325)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

**Comment by ArthurHub** [comment]
can you reproduce it on the sample app?

**Comment by ArthurHub** [comment]
and also try it with latest version 2.4.7
