### ISSUE TITLE
Does not show any control button to save cropped image

### ISSUE THREAD

**Issue by deep1931** [ArthurHub/Android-Image-Cropper#299]
Hello, I have made a sample app, the issue is that when i am on crop activity it is not showing any control like save rotate etc, i have set setAllowRotation true but still not found. It is showing white space on top and bottom.

**Comment by deep1931** [comment]
Issue resolved, it was related to style. Thanks.

**Comment by phanvanduc** [comment]
Yep, i dont still any control button to save cropped image.
Please help me.
i use compile 'com.theartofdev.edmodo:android-image-cropper:2.4.+'

**Comment by deep1931** [comment]
this issue is related to styles, u can set style to crop activity for
toolbar controls.

**Comment by vadimleonov** [comment]
This issue is still exists, v2.7.0
