### ISSUE TITLE
setImageUri takes too long

### ISSUE THREAD

**Issue by gmarques33** [ArthurHub/Android-Image-Cropper#3]
When I get a photo from G+ Photos app, sometimes this need to be downloaded. In this case the app will hang for some time and I get an ANR.

With older devices, decodeBitmat takes too long too.

I think that setImageUri needs to be executed on a background thread. The method setImageUri can accept a callback and return after the job has done.

**Comment by sethgho** [comment]
This seems like a problem worth solving.  @ArthurHub, what do you think the right answer should be here? Disabling the crop support and drawing some sort of loading indicator on the crop image view while downloading the Bitmap?

**Comment by ArthurHub** [comment]
Yep, that sounds reasonable, maybe provide the client with optional widget to be placed while it is loading.

**Comment by sethgho** [comment]
Hmm... how about an async overload of setImageUri with just a basic success/failure callback? That should let the client toggle whatever UI state they want.

**Comment by gmarques33** [comment]
@sethgho That's exactly what I did.
I will improve the code and make a pull request.

**Comment by sethgho** [comment]
:+1:

**Comment by ArthurHub** [comment]
:+1:

**Comment by ArthurHub** [comment]
added `setImageUriAsync(Uri)` and `getCroppedImageAsync()` in v1.1.0
