### ISSUE TITLE
Ability to manually set position and size of cropping rectangle

### ISSUE THREAD

**Issue by wher** [ArthurHub/Android-Image-Cropper#30]
Is it possible to manually set the position and size of the cropping shape? For example if I want to use the cropper in combination with face detection and center the initial cropping rectangle around the face of a person. 
Tanks!

**Comment by ArthurHub** [comment]
love it, will add.
I'm thinking something like this: `setCropRect(Rect rect)`, where the `rect` is in the image bitmap coordinates.
Sound good?

**Comment by wher** [comment]
Sounds great, that's about what I had in mind too. 
Thank you for your fast reply!

**Comment by ArthurHub** [comment]
added in **v1.2.1**
