### ISSUE TITLE
cropFixAspectRatio together with cropMultiTouchEnabled could break the aspect

### ISSUE THREAD

**Issue by TheMarketka** [ArthurHub/Android-Image-Cropper#300]
When the crop view is setup with fixed aspect ratio (say, 1:1 for square cropping), but with `cropMultiTouchEnabled="true"`, it is possible to break the aspect ratio of the cropped area after scale gesture. It jumps back to the fixed ratio after dragging the cropping edge though.

**Comment by ArthurHub** [comment]
duplicate: #161 
Can't commit time for proper multi-touch support at this time, PR is always welcome.
