### ISSUE TITLE
Is it possible to change CROP text?

### ISSUE THREAD

**Issue by Zayid** [ArthurHub/Android-Image-Cropper#301]
is it possible to change the text in actionbar of CropImageActivity?

**Comment by yeganehaym** [comment]
+1

**Comment by tomrennen** [comment]
Yes, you can easily do this by adding this to your style:
`<string name="crop_image_menu_crop">Crop</string>`
For more info on usage and changing other elements refer to [this ](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Activity-Visual-Customization)wiki page.
