### ISSUE TITLE
Possible to customize entire appbar/toolbar?

### ISSUE THREAD

**Issue by AlanCPSC** [ArthurHub/Android-Image-Cropper#303]
Hello, I was wondering if it is possible to customize the entire appbar/toolbar and replace it with a custom one (e.g. inflating it from some XML) and manually connecting the new buttons to the Crop Activity's callbacks.

Is this something that can be done? If so, could you link me to some helpful resources? Thanks!

**Comment by ArthurHub** [comment]
You can use `CropImageView` in your custom activity: https://github.com/ArthurHub/Android-Image-Cropper/wiki/Using-CropImageView-in-own-Activity
