### ISSUE TITLE
Getting 'Search' icon instead of 'CROP' in top right corner

### ISSUE THREAD

**Issue by apgapg** [ArthurHub/Android-Image-Cropper#305]

**Comment by jwolinsky** [comment]
Same here, except it's not a search icon. It seems to pull a random icon from the drawables folder. Also it seems to happen intermittently. Sometimes when I compile and the run the CropImage activity I see the old CROP text, but if I close the activity and reopen it I see an icon from the drawables folder where the CROP text should be. Weird.

**Comment by ArthurHub** [comment]
Are you using the latest version?
Is it on specific devices?

**Comment by jwolinsky** [comment]
Yes, latest version of Android Image Cropper. Running on Galaxy S5 with Android 6.0. It's only when I don't set a `crop_image_menu_crop` drawable. Ultimately, I just made a `crop_image_menu_crop` drawable that says "CROP" and it works.
