### ISSUE TITLE
Rotating does not reset aspect ratio.

### ISSUE THREAD

**Issue by krupalagile** [ArthurHub/Android-Image-Cropper#306]
Steps to reproduce: 
1. set rotation enabled
2. set custom aspect ratio
3. open CropActivity
4. Click on Rotate icon
5. Cropping window will not be reset according to aspect ration given,

Expected Behaviour:
Without clicking anywhere, crop window should reset automatically according to aspect ratio given.

**Comment by ArthurHub** [comment]
I can't reproduce it. Used 3-to-1 aspect ratio in quick-start app and it worked as expected.

**Comment by krupalagile** [comment]
I used the latest version and it looks fixed now. I am closing this, Thanks.
