### ISSUE TITLE
Image Crop screen open twice in samsung devices.

### ISSUE THREAD

**Issue by JaydipRadadiya** [ArthurHub/Android-Image-Cropper#309]
Hi, ArthurHub!

This is a great library for cropping image, but I am facing an issue right now. When I take a picture using camera in fragment on Samsung Galaxy J7, Crop with frame screen open twice. when click on **CROP** button again open same screen for same image, how to fix ? and also displayed image rotated. I used _result.getUri()_ from _CropImage.ActivityResult result = CropImage.getActivityResult(data)_ for request code CROP_IMAGE_ACTIVITY_REQUEST_CODE. 

Can you help me? 

Thanks a lot!

**Comment by ARTos98** [comment]
did you find the solution >???

**Comment by mrgulshanyadav** [comment]
any solution?
