### ISSUE TITLE
Rotate image to 45 degrees overlay coming out of the boundary 

### ISSUE THREAD

**Issue by syam82** [ArthurHub/Android-Image-Cropper#31]
It's very useful library. I am facing an issue with rotation. when I am trying to  rotate image to 45 degrees overlay coming out of the boundary. Please take a look of attached image.
![screenshot_2016-02-12-15-40-29-018](https://cloud.githubusercontent.com/assets/8858054/13004217/31a59fda-d1a0-11e5-8ac2-c7ef2c49e227.jpeg)
 
Using same method as you used to rotate image for 90 degrees.
 mCropImageView.rotateImage(45);

**Comment by Y-E-P** [comment]
is it possible to fix???

**Comment by ArthurHub** [comment]
it's not easy, working on it.

**Comment by Y-E-P** [comment]
@ArthurHub thanks for your work!

**Comment by Y-E-P** [comment]
Error in my case:Image load failed: width must be >0

**Comment by ArthurHub** [comment]
Sorry it took so long, finally done in **2.2.0**.
