### ISSUE TITLE
Not working in kit kat

### ISSUE THREAD

**Issue by Parveshdhull** [ArthurHub/Android-Image-Cropper#310]
It works fine in marshmallow but in kit kat when i start activity for crop it instantly calling result (result code = 25) even before crop with result code error and null data 

 if (requestCode == 12 && resultCode == RESULT_OK && data != null && data.getData() != null) {

            try {
                Uri uri = data.getData();

                Intent intent = CropImage.activity(uri)
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setFixAspectRatio(true)
                        .setActivityTitle("Crop Image")
                        .getIntent(this);

                Log.d("RemoveTAG", "13"+ intent.toString());
                startActivityForResult(intent, 25);

            } catch (Exception e) {
                e.printStackTrace();

            }
        }

        if (requestCode == 25 && viewPager.getCurrentItem()==0) {
            CropImage.ActivityResult result = CropImage.getActivityResult(data);

            Log.d("RemoveTAG", "23"+resultCode);
            if (resultCode == RESULT_OK) {
                final Uri  resultUri = result.getUri();

                

            } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                Exception error = result.getError();
            }
        }

**Comment by ArthurHub** [comment]
permissions, see wiki
