### ISSUE TITLE
Image doesn't crop when it is selected fully 

### ISSUE THREAD

**Issue by Kovartthan** [ArthurHub/Android-Image-Cropper#320]
I selected a image with its full size (width,height) from the gallery and that picture taken from the camera . 
It sets the image in black color in the image view

**Comment by ArthurHub** [comment]
what?

**Comment by OsamaDarabeh** [comment]
Same problem here in 4.4.2 android API please check it.

**Comment by ArthurHub** [comment]
I need more info

**Comment by OsamaDarabeh** [comment]
you can see the screen shot for problem in this link.
[https://www.dropbox.com/sh/jdga47oxg9nw54l/AAA4u5q5qOw1MICXK4BwE-GWa?dl=0](url)
regard.

**Comment by ArthurHub** [comment]
404 on the link

**Comment by OsamaDarabeh** [comment]
i have updated the link please check again.

**Comment by ArthurHub** [comment]
Thanks,
Can you reproduce it in the sample app?

**Comment by Kovartthan** [comment]
I resolved issues with custom circle image view and advice not to use hdodenhof circle image view because this causes the issue when i crop a high resolution image from camera , it sets black in the image view

**Comment by ArthurHub** [comment]
I think what you see is Android max allowed texture size limitation ([example question](https://stackoverflow.com/questions/15313807/android-maximum-allowed-width-height-of-bitmap))

I would advise limiting the size of the cropped image, I don't think you need 3000x3000 avatars...
See: https://github.com/ArthurHub/Android-Image-Cropper/wiki/FAQ#how-can-i-limit-the-size-of-the-cropped-image
