### ISSUE TITLE
Problem with appcompat v7:26

### ISSUE THREAD

**Issue by Dreyar** [ArthurHub/Android-Image-Cropper#321]
After including on app gradle the  compile 'com.theartofdev.edmodo:android-image-cropper:2.4.+' I get the following error:

`Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:design:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:exifinterface:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.`

**Comment by kirich1409** [comment]
Add in you application module build.gradle next:

```groovy
dependencies {
    compile "com.android.support:appcompat-v7:$supportLibraryVersion"
    compile "com.android.support:exifinterface:$supportLibraryVersion"
    implementation("com.theartofdev.edmodo:android-image-cropper:$androidImageCropperVersion") {
        exclude group: 'com.android.support'
    }
}
```

Do not forget to replace `$supportLibraryVersion` and _$androidImageCropperVersion_ with specific library versions.

**Comment by Redman1037** [comment]
I am getting following error after adding this

```
Error:(34, 0) Could not find method implementation() for arguments [com.theartofdev.edmodo:android-image-cropper:2.4.6, build_7rzbtt106zalioieyntzoyx7j$_run_closure2$_closure7@14594ce] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
<a href="openFile:F:\Android\GameWallPapers\app\build.gradle">Open File</a>
```
