### ISSUE TITLE
geting crop transformation to use it for any other image

### ISSUE THREAD

**Issue by simarsingh24** [ArthurHub/Android-Image-Cropper#322]
Hey Dev, i have multiple images of same resolution, i want to crop only one of them and use the same pattern to crop any new image , is there any way i can do that?

**Comment by ArthurHub** [comment]
Not out-of-the-box but you can look how `BitmapUtils.cropBitmap()` works.
There is a bunch of code to support the library features which I'm sure you don't need all of them.
I don't think this capability is common enough to be added to the library.
But if you do it a PR is always welcome.
