### ISSUE TITLE
Request: return original photo dimensions in CropImage.ActivityResult

### ISSUE THREAD

**Issue by gazialankus** [ArthurHub/Android-Image-Cropper#324]
In the result of CropImage.activity(), we get the crop rectangle values, which is great. However, these values would be more meaningful if we had the dimensions of the original image. 

For example, to determine that a crop rectangle (0, 0, 400, 300) is the whole first quadrant of the image, we need to know that the image is 800x600. 

To get the image dimensions, we have to repeat the task of reading the image ourselves. Since CropImage.activity() already reads the image, it can also return the image dimensions in CropImage.ActivityResult, which would make the crop rectangle more meaningful.

**Comment by ArthurHub** [comment]
Thanks for the PR!
