### ISSUE TITLE
Image Rotate in Samsung Devices

### ISSUE THREAD

**Issue by dhananjay23** [ArthurHub/Android-Image-Cropper#326]
Hello Sir,
I am facing same problem for image capture in samsung device and image rotate automatically ,
i have check other device but image is set potrait format , i have use picasso library to resize the
image.

Pleaase provide me any suggestion and help for solve this problem !!!!!!

**Comment by ArthurHub** [comment]
Are you using the latest version? there was a fix in 2.4.4: #267
Otherwise please provide more details of the issue.
Samsung camera uses exif data to rotate the image, the library should handle it.
