### ISSUE TITLE
setShowCropOverlay() not working properly

### ISSUE THREAD

**Issue by davidaik** [ArthurHub/Android-Image-Cropper#33]
If I put setShowCropOverlay(false) in my Activity onCreate(), the crop overlay is hidden, but doing setShowCropOverlay(true) later does not do anything.

**Comment by ArthurHub** [comment]
shit, didn't call set visibility, sorry, will fix

**Comment by davidaik** [comment]
Wow that was quick! Thanks for the awesome work on the library! :)

**Comment by ArthurHub** [comment]
fixed in **1.2.2**

**Comment by davidaik** [comment]
Awesome!
