### ISSUE TITLE
Multitouch: doesnt mantain aspect ratio and wierd behaviour

### ISSUE THREAD

**Issue by jcnoriega** [ArthurHub/Android-Image-Cropper#330]
I enabled multitouch, but if I have a fixed aspect ratio (my case 3:3), it doesnt mantain it and it has a weird bahaviour. Here is a gif showing what happens:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10046176/27862866-d3119498-615d-11e7-9d35-49aa168f0763.gif)

Here is the layout:
![screen shot 2017-07-05 at 8 45 21 am](https://user-images.githubusercontent.com/10046176/27862977-66f2fc4c-615e-11e7-8ca4-141f22f6cc06.png)

Here is the code:
![screen shot 2017-07-05 at 8 45 44 am](https://user-images.githubusercontent.com/10046176/27862982-6bd928ee-615e-11e7-8482-a0b4f5e7b316.png)

This was tested on a Motorola MotoG3, Android 6.0, API 23

**Comment by jcnoriega** [comment]
Edit: Reported in https://github.com/ArthurHub/Android-Image-Cropper/issues/300

**Comment by ArthurHub** [comment]
It's actually older: #161 
Can't commit time for proper multi-touch support at this time, PR is always welcome.
