### ISSUE TITLE
Question: zoom function

### ISSUE THREAD

**Issue by QiiqeAzuara** [ArthurHub/Android-Image-Cropper#331]
hi! nice work, i want disable zoom function, only i need crop the image. is possible ? Thanks

**Comment by QiiqeAzuara** [comment]
solved !  .setMinCropResultSize(99999, 99999)   

based on this:
 /**
  * the max size the resulting cropping image is allowed to be, affects the cropping window limits
  * (in pixels).<br>
  * <i>Default: 99999, 99999</i>
  */
setMaxCropResultSize(int maxCropResultWidth, int maxCropResultHeight)

**Comment by ArthurHub** [comment]
It may be easier to use AutoZoomEnabled property as documented in the wiki: https://github.com/ArthurHub/Android-Image-Cropper/wiki/Visual-Customization

**Comment by QiiqeAzuara** [comment]
I already tried that and it did not work :(
.setMinCropResultSize(99999, 99999) work fine ....

**Comment by ArthurHub** [comment]
Setting it to false doesn't disable auto zoom?
That's an issue you defintly should report! I will check and fix if it's so. 

Regardless, I would advice against using hacks to achieve your goal, you never know what future changes in the library, any library, will break your scenario.

**Comment by QiiqeAzuara** [comment]
@ArthurHub thanks ;)

**Comment by ArthurHub** [comment]
Hmmm... `.setAutoZoomEnabled(false)` works as documented by disabling auto-zoom.

`.setMinCropResultSize(99999,99999)` makes the crop window fill the whole image without the ability to resize it.. so the user can only rotate the image... is that what you want?

**Comment by QiiqeAzuara** [comment]
exactly!  user only rotate and move the crop area without resize it.

**Comment by ArthurHub** [comment]
resizing and zooming is not the same thing...
but the hack you propose will always set the crop to the full size of the image, not much moving can happen there...

**Comment by QiiqeAzuara** [comment]
@ArthurHub Thanks for taking the time to review this. I have already obtained my answer.
