### ISSUE TITLE
Cannot change crop_image_menu_rotate_left / change crop_image_menu_rotate_right drawable

### ISSUE THREAD

**Issue by RobinCheptileh** [ArthurHub/Android-Image-Cropper#333]
Hi, as indicated in the wiki, I can override the rotation and the crop drawables. I have successfully changed the crop drawable but I can't change the rotation drawables. I have both the change crop_image_menu_rotate_left and crop_image_menu_rotate_right drawable resources.
Help would be much appreciated, thanks.

**Comment by ArthurHub** [comment]
you must replace all 4 dpi variations (hdpi,xhdpi,xxhdpi,xxhdpi) and rebuild the project.

**Comment by RobinCheptileh** [comment]
Thanks it worked
