### ISSUE TITLE
Get bitmap after crop

### ISSUE THREAD

**Issue by Straiker13** [ArthurHub/Android-Image-Cropper#334]
Hi, Im using Crop Activity for set result of this to classic Image View, iv done it by using `Uri uri = result.getData();` and `imageview.setBitmapURI(uri)`, but i cant get bitmap image after CA result.
(I`m not using Crop Image View) How can I get a picture after the activity result?
(Sorry for my English!)

**Comment by itaybia** [comment]
private InputStream getInputStreamFromUri(Uri uri) {
        try {
            File imageFile = new File(uri.getPath());
            return new FileInputStream(imageFile);
        } catch (FileNotFoundException e) {
            Log.w(TAG, "getInputStreamFromUri: exception while opening input stream from file. try from content resolver");
        }

        try {
            return getApplicationContext().getContentResolver().openInputStream(uri);
        } catch (FileNotFoundException e) {
            Log.e(TAG, "getInputStreamFromUri: exception while opening input stream from content resolver. returning");
        }

        return null;
    }

**Comment by Straiker13** [comment]
Thanks!!!
