### ISSUE TITLE
Update for SDK 26

### ISSUE THREAD

**Issue by muruthi** [ArthurHub/Android-Image-Cropper#335]
Building for Target SDK 26 fails due to the below AppCompat dependency. 

`compile 'com.android.support:appcompat-v7:25.3.1'`

**Comment by aprabhak** [comment]
Do you have a fix for this?

**Comment by muruthi** [comment]
You just have to use a lower build for now. I can push a PR later.

**Comment by aprabhak** [comment]
Okay, I have done that and all seems well for now. Thanks.

**Comment by ArthurHub** [comment]
v2.5.0 is using sdk 26
