### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by MohammadAyman** [ArthurHub/Android-Image-Cropper#339]
com.theartofdev.edmodo.cropper.CropImageView.getWholeImageRect (CropImageView.java:625)
--
  | com.theartofdev.edmodo.cropper.CropImageActivity.getResultIntent (CropImageActivity.java:322)
  | com.theartofdev.edmodo.cropper.CropImageActivity.setResult (CropImageActivity.java:299)
  | com.theartofdev.edmodo.cropper.CropImageActivity.onSetImageUriComplete (CropImageActivity.java:241)
  | com.theartofdev.edmodo.cropper.CropImageView.onSetImageUriAsyncComplete (CropImageView.java:1067)
  | com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute (BitmapLoadingWorkerTask.java:116)
  | com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute (BitmapLoadingWorkerTask.java:26)
  | android.os.AsyncTask.finish (AsyncTask.java:632)
  | dalvik.system.NativeStart.main (NativeStart.java)

**Comment by ArthurHub** [comment]
That can only happen if you click crop without loaded image.. maybe if it failed...
I will look into it to prevent the exception and maybe prevent the button from being clickable
