### ISSUE TITLE
how to set requestCode?

### ISSUE THREAD

**Issue by Shachar87** [ArthurHub/Android-Image-Cropper#341]
Hi,
I want do use this lib in several screens, And in every screen I want from onActivityResult to do something different.
The problem is onActivityResult happening in start method of CropImage, and because of that I cant set requestCode.
Any suggestions?

**Comment by ArthurHub** [comment]
See the FAQ

**Comment by Shachar87** [comment]
Ok found it, sorry.
I looked at all the files besides that one.

**Comment by rashidfiverivers** [comment]
Where to find that? I couldn't find that. Can anyone guide?
