### ISSUE TITLE
Not able to set height and width of cropper

### ISSUE THREAD

**Issue by prajwal-appiness** [ArthurHub/Android-Image-Cropper#343]
I am not able to set the height and width of the cropper while using it as a view. I want the cropper width to be match_parent and height of about 250dp.  But when I select a portrait image where height is greater than width then the cropper height and width is same as that of image.

**Comment by ArthurHub** [comment]
can you post a reproducible example so I can debug and fix it?

**Comment by sweta01** [comment]
Hi ArthurHub,

I am getting stuck in cropper. please help me asap.

I want to get hieght and width when image croping in cropper window . please let me know if any method is available.
