### ISSUE TITLE
result bitmap is not working..

### ISSUE THREAD

**Issue by yash59** [ArthurHub/Android-Image-Cropper#345]
i used this library it works fine and cropped the image but in onactivityresult when i am trying to set result bitmap to my imageview then it's showing nothing and no error is showing..

**Comment by ArthurHub** [comment]
check the logcat, Android rarely fail without a reason.
Also check this: https://github.com/ArthurHub/Android-Image-Cropper/wiki/FAQ#when-i-get-cropped-image-it-all-shown-black
