### ISSUE TITLE
App Crashing in Android 4.4.4 Samsung Galaxy 

### ISSUE THREAD

**Issue by sunil553** [ArthurHub/Android-Image-Cropper#346]
CropImage.ActivityResult result = CropImage.getActivityResult(data);
                Uri resultUri = result.getUri();
              
![image001](https://user-images.githubusercontent.com/10163144/28572203-923600ce-7163-11e7-94c2-705247f30e92.png)

When Clicked On Crop App crashes only on 4.4.4 please help me.

**Comment by ArthurHub** [comment]
It may be Samsung issue similar to #329, or maybe not as it's not the same error...
I don't see the library code in the stack trace and the library doesn't parse URI in the activity result flow...
Can you reproduce it using the `quick-start` app in the library?
