### ISSUE TITLE
Not compatible with the library 26

### ISSUE THREAD

**Issue by mechak** [ArthurHub/Android-Image-Cropper#349]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:design:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:exifinterface:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

**Comment by Shreyas-R** [comment]
Yes, its not working. Please update the SDK versions ASAP.

**Comment by mechak** [comment]
Now it is fixed

**Comment by tvelf009** [comment]
i have same problem.

Please help, how to fix this?

**Comment by NoManMade** [comment]
You can add 
`    compile('com.theartofdev.edmodo:android-image-cropper:2.4.7') {
        exclude group: 'com.android.support'
    }` in gradle

**Comment by Shreyas-R** [comment]
If you exclude com.android.support @NoManMade then it builds fine but app crashes when you use cropping within the app with exif class not found exception.

**Comment by vanyasem** [comment]
@Shreyas-R you need to manually add `com.android.support:exifinterface` to your build.gradle (as you're excluding it from the library itself):
`compile "com.android.support:exifinterface:$supportLibraryVersion"`

**Comment by ArthurHub** [comment]
v2.5.0 is using sdk 26

**Comment by amarjeetak** [comment]
**Error :**
Program type already present: android.arch.lifecycle.LiveData$LifecycleBoundObserver 

Program type already present: android.arch.lifecycle.LiveData$LifecycleBoundObserver
Message{kind=ERROR, text=Program type already present: android.arch.lifecycle.LiveData$LifecycleBoundObserver, sources=[Unknown source file], tool name=Optional.of(D8)}
