### ISSUE TITLE
Fix crop area reset after keyboard appearance

### ISSUE THREAD

**Issue by Actify** [ArthurHub/Android-Image-Cropper#35]
Hi,
in my app, i use your awesome library in a way like whatsapp, showing the image to crop and a text input below.
When i change the crop area and then i tap on the edittext, the keyboard appearance make a crop area reset.
I configured the androidManifest.xml like this for this activity
`<activity
       ...
       android:configChanges="orientation|screenSize"
       android:windowSoftInputMode="adjustPan" >
</activity>`
and the layout xml is this one:
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/activity_background"
    android:orientation="vertical" >

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:gravity="center" >

        <com.theartofdev.edmodo.cropper.CropImageView
            android:id="@+id/imgPreview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_centerInParent="true"
            app:cropGuidelines="on"
            app:cropInitialCropWindowPaddingRatio="0"
            app:cropScaleType="fitCenter" />

        <ImageButton
            android:id="@+id/btnRotate"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_margin="16dp"
            android:background="#424242"
            android:padding="4dp"
            android:src="@drawable/ic_action_rotate_right" />
    </RelativeLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical" >
...
`

Is there a way to keep the crop area? I have to change something on the activity configuration?
Thank you a lot for your efforts!

**Comment by ArthurHub** [comment]
it's a bug i was too lazy to fix because it requires recalculate the crop window after size change...
will fix it soon
for now you can save the crop window before keyboard is shown and set it again after... it will work because it adjusts the calculation to original image bitmap... or wait a week or two :)

**Comment by Actify** [comment]
Thank you for your workaround, I'll try it!
But for sure i'll wait for the clean fix too.

Thanks again

**Comment by ArthurHub** [comment]
fixed in **1.2.2**
