### ISSUE TITLE
Retrieve intent extra through CropImageActivity

### ISSUE THREAD

**Issue by okaa-pi** [ArthurHub/Android-Image-Cropper#352]
Hi.

It's more of an enhancement than an issue. 
I would like to send intent Extra to CropImageActivity, and get it back in the onActivityResult.

An exemple : 
I have a recyclerview listing my friends. When I select a friend, it opens the image picker/cropper like this:
`CropImage.activity()`
`                .setGuidelines(CropImageView.Guidelines.ON)`
`                .start(this)`

The problem is that, in onActivityResult, I don't know which friend was selected.
Currently, the only way I found to correct this, is to have a global variable "Friend", that I assign before starting the CropImageActivity, and I use it in onActivityResult.

It works, but it's not the best way to do it. I think it would be better if I could do it like that:
`Intent cropIntent = CropImage.activity().getIntent(this);`
`cropIntent.putExtra("friend", friend);`

onActivityResult:
`Friend selectedFriend = resultIntent.getParcelableExtra("friend");`

Don't you think it would be a good idea?

**Comment by ArthurHub** [comment]
added in 2.5.1

**Comment by Magurosenbei** [comment]
Is it possible to propagate extras for the PickImageChooserIntent as well?

**Comment by sara1010** [comment]
@ArthurHub  can you explain how can i use this library in fragment and send extra data by example?
