### ISSUE TITLE
Crop a video similar to image using cropper

### ISSUE THREAD

**Issue by pawaom** [ArthurHub/Android-Image-Cropper#353]
Crop a video similar to image using cropper

I am basically looking for a UI, for cropping

**Comment by pawaom** [comment]
this is the code I have tried so far

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical">

    <RelativeLayout
        android:layout_weight="1"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        >


        
            
            
            
            
            
            
            
        

            
            
            
            
            
            
            
            
            
            
        <VideoView
            android:id="@+id/VideoView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
              />
        <com.theartofdev.edmodo.cropper.CropImageView

            android:id="@+id/VideocropImageView"
            android:background="#00000000"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
                        />
    </RelativeLayout>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1">
        <Button
            android:id="@+id/VideocropButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="abcd"/>
    </LinearLayout>


</LinearLayout>

and 

import android.app.Activity;
import android.app.ProgressDialog;
import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.graphics.Bitmap;
import android.media.MediaMetadataRetriever;
import android.media.MediaPlayer;
import android.net.Uri;
import android.os.Bundle;
import android.os.Environment;
import android.view.View;
import android.widget.Button;
import android.widget.MediaController;
import android.widget.Toast;
import android.widget.VideoView;

import com.github.hiteshsondhi88.libffmpeg.ExecuteBinaryResponseHandler;
import com.github.hiteshsondhi88.libffmpeg.FFmpeg;
import com.github.hiteshsondhi88.libffmpeg.LoadBinaryResponseHandler;
import com.github.hiteshsondhi88.libffmpeg.exceptions.FFmpegCommandAlreadyRunningException;
import com.github.hiteshsondhi88.libffmpeg.exceptions.FFmpegNotSupportedException;
import com.quest.fsrecorder.R;
import com.theartofdev.edmodo.cropper.CropImageView;

public class VideoCropTryAct extends Activity implements CropImageView.OnSetImageUriCompleteListener, CropImageView.OnCropImageCompleteListener {
    VideoView simpleVideoView;
    MediaController mediaControls;
    String j;
    int width, height;
    int videocroptop, videocropBottom, videocropLeft, videocropRight;
    private CropImageView mCropImageView;
    FFmpeg ffmpeg;
    Button bb;
    private ProgressDialog progressDialog;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);


        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_PORTRAIT);
        try {
            Intent iin = getIntent();
            Bundle b = iin.getExtras();
            if (b != null) {
                j = (String) b.get("fileVideoPath");
            }
            setContentView(R.layout.videocroptryact);
            simpleVideoView = (VideoView) findViewById(R.id.VideoView);
            mCropImageView = (CropImageView) findViewById(R.id.VideocropImageView);
            progressDialog = new ProgressDialog(this);
            progressDialog.setTitle(null);
            progressDialog.setCancelable(false);
            if (mediaControls == null) {
                mediaControls = new MediaController(VideoCropTryAct.this, false);
                mediaControls.setAnchorView(simpleVideoView);
            }
            simpleVideoView.setMediaController(mediaControls);
            simpleVideoView.setVideoPath(j);
            simpleVideoView.start();
            simpleVideoView.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
                @Override
                public void onCompletion(MediaPlayer mp) {
                }
            });
            simpleVideoView.setOnErrorListener(new MediaPlayer.OnErrorListener() {
                @Override
                public boolean onError(MediaPlayer mp, int what, int extra) {
                    Toast.makeText(getApplicationContext(), R.string.VideoError,
                            Toast.LENGTH_LONG).show();
                    return false;
                }
            });

            MediaMetadataRetriever retriever = new MediaMetadataRetriever();
            retriever.setDataSource(j);
            width = Integer.valueOf(retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH));
            height = Integer.valueOf(retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT));

            Toast.makeText(VideoCropTryAct.this, "width "+ width + "height " + height, Toast.LENGTH_SHORT).show();
            Bitmap.Config conf = Bitmap.Config.ARGB_8888; // see other conf types
            Bitmap bmp = Bitmap.createBitmap(width, height, conf); // this creates a MUTABLE bitmap
            mCropImageView.setImageBitmap(bmp);
            mCropImageView.setAutoZoomEnabled(false);

            // Canvas canvas = new Canvas(bmp);


        } catch (Exception e) {

        }
        bb = (Button) findViewById(R.id.VideocropButton);
        bb.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                videocroptop = mCropImageView.getCropRect().top;
                videocropBottom = mCropImageView.getCropRect().bottom;
                videocropLeft = mCropImageView.getCropRect().left;
                videocropRight = mCropImageView.getCropRect().right;

                String out = Environment.getExternalStorageDirectory().
                        getAbsolutePath() + "/" + getResources().
                        getString(R.string.string_store_video_Edited_folder) + "/" + "_Crop.mp4";
                loadFFMpegBinary();

                Toast.makeText(VideoCropTryAct.this, "crop=" + videocropRight + ":" + videocropBottom + ":" + videocropLeft + ":" + videocroptop, Toast.LENGTH_SHORT).show();

               // String[] cc = {"-y", "-i", j, "-filter:v", "crop=" + 240 + ":" + 120 + ":" + 100 + ":" + 100, "-c:a", "copy", out};
                String[] cc = {"-y", "-i", j, "-filter:v", "crop=" + videocropRight + ":" + videocropBottom + ":" + videocropLeft + ":" + videocroptop, "-c:a", "copy", out};
                execFFmpegBinary(cc);
            }
        });
        mCropImageView.setOnSetImageUriCompleteListener(this);
        mCropImageView.setOnCropImageCompleteListener(this);
        mCropImageView.getCroppedImageAsync();
    }

    @Override
    protected void onResume() {
        super.onResume();
        //sendBroadcast(new Intent(FloatWithDialog.BROADCAST_HIDE_FLOAT_BUTTON));
    }

    @Override
    protected void onStop() {
        super.onStop();
        //sendBroadcast(new Intent(FloatWithDialog.BROADCAST_SHOW_FLOAT_BUTTON));

    }

    @Override
    public void onBackPressed() {

        finishAndRemoveTask();
    }

    @Override
    public void onCropImageComplete(CropImageView view, CropImageView.CropResult result) {

    }

    @Override
    public void onSetImageUriComplete(CropImageView view, Uri uri, Exception error) {

    }

    /**
     * Load FFmpeg binary
     */
    private void loadFFMpegBinary() {
        try {
            if (ffmpeg == null) {

                ffmpeg = FFmpeg.getInstance(this);
            }
            ffmpeg.loadBinary(new LoadBinaryResponseHandler() {
                @Override
                public void onFailure() {
                    //  showUnsupportedExceptionDialog();
                    Toast.makeText(VideoCropTryAct.this, "onFailure", Toast.LENGTH_SHORT).show();
                }

                @Override
                public void onSuccess() {
                    //  Log.d(TAG, "ffmpeg : correct Loaded");
                    Toast.makeText(VideoCropTryAct.this, "onSuccess", Toast.LENGTH_SHORT).show();
                }
            });
        } catch (FFmpegNotSupportedException e) {
            //showUnsupportedExceptionDialog();
        } catch (Exception e) {
            Toast.makeText(VideoCropTryAct.this, "FFmpegNotSupportedException", Toast.LENGTH_SHORT).show();
            // Log.d(TAG, "EXception no controlada : " + e);
        }
    }


    private void execFFmpegBinary(final String[] command) {
        try {
            ffmpeg.execute(command, new ExecuteBinaryResponseHandler() {
                @Override
                public void onFailure(String s) {
                    Toast.makeText(VideoCropTryAct.this, "onFailure exec" + s, Toast.LENGTH_SHORT).show();

                }

                @Override
                public void onSuccess(String s) {

                    Toast.makeText(VideoCropTryAct.this, "onSuccess exec" + s, Toast.LENGTH_SHORT).show();
                }

                @Override
                public void onProgress(String s) {


                    // progressDialog.setMessage("progress : splitting video " + s);

                }

                @Override
                public void onStart() {

                    progressDialog.setMessage("Processing...");
                    progressDialog.show();
                }

                @Override
                public void onFinish() {


                    progressDialog.dismiss();


                }
            });
        } catch (FFmpegCommandAlreadyRunningException e) {
            // do nothing for now
        }
    }
}

I do get the cropped video , but I am having problem with getting it to match with wysiwyg, the videoview and the cropview , so that what we crop on the screen we get back that exactly , can some one help

I have kept the comments part and imports for people to use them and change accordingly , ffmpeg is from the link mentioned above

**Comment by ArthurHub** [comment]
it's outside the scope of this library
