### ISSUE TITLE
Crash because Bitmap.getWidth() is null

### ISSUE THREAD

**Issue by kkm** [ArthurHub/Android-Image-Cropper#354]
> Exception java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
> com.theartofdev.edmodo.cropper.CropImageView.getWholeImageRect (CropImageView.java:625)
> com.theartofdev.edmodo.cropper.CropImageActivity.getResultIntent (CropImageActivity.java:322)
> com.theartofdev.edmodo.cropper.CropImageActivity.setResult (CropImageActivity.java:299)
> com.theartofdev.edmodo.cropper.CropImageActivity.onSetImageUriComplete (CropImageActivity.java:241)
> com.theartofdev.edmodo.cropper.CropImageView.onSetImageUriAsyncComplete (CropImageView.java:1067)
> com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute (BitmapLoadingWorkerTask.java:116)
> com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute (BitmapLoadingWorkerTask.java:26)
> android.os.AsyncTask.finish (AsyncTask.java:632)
> android.os.AsyncTask.access$600 (AsyncTask.java:177)
> android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:645)
> android.os.Handler.dispatchMessage (Handler.java:102)
> android.os.Looper.loop (Looper.java:145)
> android.app.ActivityThread.main (ActivityThread.java:5951)
> java.lang.reflect.Method.invoke (Method.java)
> java.lang.reflect.Method.invoke (Method.java:372)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1388)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1183)

Other devices works very well but Samsung Galaxy S4 got this crash after photo camera save to file.
kkm

**Comment by jugglejackapps** [comment]
I just got the same error when I want to crop whatsapp images. Other images work fine except with this images.
Maybe it is about permissions?

**Comment by MyoZawOoPD** [comment]
I also got this error.

**Comment by kkm** [comment]
I found that filename doesnt exisits

**Comment by ArthurHub** [comment]
update to v2.5.0, let me know if you still experience this

**Comment by Debdeep009** [comment]
Still happening on api 22 with v2.5. Was just passing an image uri for a file stored in cache dir. File exists and is readable and writable as well.

**Comment by Debdeep009** [comment]
Ops sorry! Found out that it was crashing due to instant run.

**Comment by AndroidDeveloperLB** [comment]
Similar issue to those:
https://github.com/ArthurHub/Android-Image-Cropper/issues/356
https://github.com/ArthurHub/Android-Image-Cropper/issues/502
