### ISSUE TITLE
no apps can perform this action

### ISSUE THREAD

**Issue by ajayqualwebs** [ArthurHub/Android-Image-Cropper#359]
Giving this error when trying to upload a image. In only MI mobile phones.

**Comment by ArthurHub** [comment]
upload an image? where does the error occurs?

**Comment by ajayqualwebs** [comment]
problem is already solved in your last update by this code.
List<Intent> galleryIntents = getGalleryIntents(packageManager, Intent.ACTION_GET_CONTENT, includeDocuments);
        if (galleryIntents.size() == 0) {
            // if no intents found for get-content try pick intent action (Huawei P9).
            galleryIntents = getGalleryIntents(packageManager, Intent.ACTION_PICK, includeDocuments);
        }
