### ISSUE TITLE
Circular crop shape changes to oval

### ISSUE THREAD

**Issue by loeschg** [ArthurHub/Android-Image-Cropper#36]
I believe with the latest updates, I've started seeing odd behavior with the circle crop shape where it changes to an oval shape after attempting to resize. This seems to happen on low-res images where the crop circle shape is "maxed out" so-to-speak (when viewing, the circle shape is extended as large as the photo itself). 

To reproduce, try cropping the following image using the oval shape with a Fixed AspectRatio (you may need to click outside the bounds): 
![small-image-crop](https://cloud.githubusercontent.com/assets/766021/13160394/cd52756e-d65c-11e5-8c05-71ce430bb80f.png) 

![crop-issue 2](https://cloud.githubusercontent.com/assets/766021/13160476/370b2078-d65d-11e5-9cbb-73f193314d47.png)

**Comment by ArthurHub** [comment]
fixed in **1.2.2**
