### ISSUE TITLE
Don't use actionbar and pass style manually

### ISSUE THREAD

**Issue by PaulWoitaschek** [ArthurHub/Android-Image-Cropper#362]
I need to style the crop activity with different colors depending on where I want to use it.

I suggest to remove the `supportActionBar` stuff completely and use a plain toolbar directly. 

Then the colors etc for the theme could be passed directly through the builder.

If you like I can make a pull request for this.

**Comment by ArthurHub** [comment]
but then you can support old APIs.
you can just create your own activity, it's not a lot of code

**Comment by PaulWoitaschek** [comment]
What about bumping to api 14? The support library you use right now is outdated and won't get any more fixes.

**Comment by ArthurHub** [comment]
done, published 2.5.0

**Comment by PaulWoitaschek** [comment]
So a pull request would be accepted?

**Comment by ArthurHub** [comment]
What will it include? You still can't use Toolbar directly...

**Comment by PaulWoitaschek** [comment]
Toolbar is part of the support library.

**Comment by ArthurHub** [comment]
Sorry, I don't think I understand the change.
If you feel it's valuable to the users and doesn't break backward compatibility then I will accept the PR.
