### ISSUE TITLE
Crop to circle not working

### ISSUE THREAD

**Issue by rasselll** [ArthurHub/Android-Image-Cropper#363]
I am trying to crop my images as a circle through using the library of 'com.theartofdev.edmodo:android-image-cropper:2.4.+1 so far the user can select an image button, to choose a image from the gallery, and here the crop window appears as a circle. But when it crops, it does it as a rectangle. Not sure what I am doing wrong.

        @Override
        protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    
            super.onActivityResult(requestCode, resultCode, data);
    
            if (requestCode == GALLERY_REQUEST && resultCode == RESULT_OK) {
                Uri imageUri = data.getData();
    
    
                CropImage.activity(imageUri)
                        .setAspectRatio(150,150)
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setCropShape(CropImageView.CropShape.OVAL)
                        .start(this);
    
    
            }
    
    
            if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
                CropImage.ActivityResult result = CropImage.getActivityResult(data);
                if (resultCode == RESULT_OK) {
                    mImageUri = result.getUri();
                    mSetupImageBtn.setImageURI(mImageUri);
    
    
                } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                    Exception error = result.getError();
                }
            }
        }
    }

**Comment by ArthurHub** [comment]
It's by design, see #216

**Comment by symphonyrecords** [comment]
possible solve #642
