### ISSUE TITLE
Cannot add library

### ISSUE THREAD

**Issue by hani777** [ArthurHub/Android-Image-Cropper#364]
getting error while build
Error:(54, 13) Failed to resolve: com.theartofdev.edmodo:android-image-cropper:2.4.+
<a href="openFile:E:/projects/slapi new/MapMyPakistan - Copy/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

this same error occur with version 2.3.+

**Comment by Naveed-anwar123** [comment]
Same Error.

**Comment by bakhman1981** [comment]
same for 2.5.+.
Just use 2.3.0 version in dependency and everything works fine.

**Comment by Redman1037** [comment]
same error , please fix this

**Comment by zho8789** [comment]
ArthurHub, why did you close this issue? Is it solved? Same error in my computer!
Please fix this.
