### ISSUE TITLE
SDK26 exifinterface dependency conflict temporary solution

### ISSUE THREAD

**Issue by Thomastasa** [ArthurHub/Android-Image-Cropper#367]
For anyone else waiting for a new release to fix the exifinterface dependency conflict with Android O SDK26  in Android-Image-Cropper-v2.4.5.

This is my work around: Ignore bundled exifinterface, and manually add the latest support library. Initial tests seem to be working fine, please let us know if it causes any problems. Hope this helps you :)

``` Java
compile 'com.android.support:exifinterface:26.0.1'
compile ('com.theartofdev.edmodo:android-image-cropper:2.4.5'){
    exclude group:'com.android.support', module: 'exifinterface'
}
```

**Comment by ArthurHub** [comment]
v2.5.0 is using sdk 26
