### ISSUE TITLE
Android Manifest Merger failed

### ISSUE THREAD

**Issue by harleendutt5** [ArthurHub/Android-Image-Cropper#369]
when I add the updated library in Gradle it gives me the Manifest merger failed error.
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.0) from [com.android.support:design:25.3.0] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:exifinterface:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

when I add the tools: replace=" android: value" then it gives the below error.
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs.

**Comment by ArthurHub** [comment]
try v2.5.0

**Comment by IHNEL** [comment]
I faced this problem on v2.5.0
