### ISSUE TITLE
Unwanted crop window behavior when using setFixedAspectRatio(true)

### ISSUE THREAD

**Issue by davidaik** [ArthurHub/Android-Image-Cropper#37]
When I use

mImageCropperView.setFixedAspectRatio(true);			mImageCropperView.setAspectRatio(1, 1);

and the crop window is touching two adjacent sides of the image, it is not possible to expand the crop window further.

In other words, when the crop window is at a corner of the image, I'm not able to expand it even though there is more space for it to expand.

This is a really weird behaviour. I hope it gets improved in future updates.

**Comment by ArthurHub** [comment]
Fixed in **1.2.3**
