### ISSUE TITLE
Select Source :( hot to fix?

### ISSUE THREAD

**Issue by atakanyildirim** [ArthurHub/Android-Image-Cropper#372]
![25](https://user-images.githubusercontent.com/7900816/29830245-6b8abba2-8cea-11e7-86a4-8827c429fe22.PNG)
![basliksiz-1](https://user-images.githubusercontent.com/7900816/29830246-6b8b13f4-8cea-11e7-8b91-0300a5fe3350.jpg)
![l](https://user-images.githubusercontent.com/7900816/29830329-9a832fe8-8cea-11e7-975c-c438b5b6cd10.PNG)

**Comment by ArthurHub** [comment]
what?
