### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by rajendrachauhan** [ArthurHub/Android-Image-Cropper#374]
java.lang.NullPointerException: 	at com.theartofdev.edmodo.cropper.CropImageView.getWholeImageRect(CropImageView.java)
  at com.theartofdev.edmodo.cropper.CropImageActivity.getResultIntent (CropImageActivity.java)

plz try to solve this issue.

**Comment by ArthurHub** [comment]
update to latest version
