### ISSUE TITLE
Crop should be only square not rectangle

### ISSUE THREAD

**Issue by Anilds04** [ArthurHub/Android-Image-Cropper#375]
Hi I want to crop only square shop not in rectangle could u please help me

**Comment by yummyummyummy** [comment]
Use AspectRatio property of CropImage.Activity

**Comment by mwshubham** [comment]
use` setFixAspectRatio(true)`

**Comment by truthhonestmessaging** [comment]
[CropImage.activity()
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setActivityTitle("Crop")
                        .setAspectRatio(1,1)
                        .setFixAspectRatio(true)
                        .setCropMenuCropButtonTitle("Done")
                        .start(this);](url)
                        
   Still rectangle cropping box. help!
