### ISSUE TITLE
Get cropped and scaled bitmap without GUI interaction?

### ISSUE THREAD

**Issue by stefanb22** [ArthurHub/Android-Image-Cropper#379]
Love this library.

I would like to do a fixed scale and center crop of an image bitmap in an Android service. Is there any way of doing this by using your library? It would save me from having to implement all the logic myself.  

Thanks

**Comment by ArthurHub** [comment]
Just look at the code and pick what you need from there, most of the complexity comes from UI interactions and not actual cropping.
https://github.com/ArthurHub/Android-Image-Cropper/blob/master/cropper/src/main/java/com/theartofdev/edmodo/cropper/BitmapUtils.java
