### ISSUE TITLE
Black line at left side when picture's background is white

### ISSUE THREAD

**Issue by masoud2v** [ArthurHub/Android-Image-Cropper#38]
when i crop white images, about 50% of the times a black line shows up on left side or upper side of the picture

![fkoyfdqvo4gc5crwqzwh6gv880xhctch436nrrj0njjkespg0vnrgsjnjwadowtuyagdft6qhsrufswu thumbnail](https://cloud.githubusercontent.com/assets/6926271/13262997/eab6e53a-da7c-11e5-817c-73daa71e35c3.jpg)
![single-strawberry-on-white-background](https://cloud.githubusercontent.com/assets/6926271/13262998/eabaedc4-da7c-11e5-8d19-291b2b046cbd.jpg)

**Comment by ArthurHub** [comment]
I assume it has something to do with rounding error but I'm unable to reproduce it.
Do you use the image you provided in the in this issue?
What configs and crop method do you use?

**Comment by masoud2v** [comment]
Yes the second image is the original one and my configs are like below:        

`cropImageView.setGuidelines(1);`
`cropImageView.setCropShape(CropImageView.CropShape.RECTANGLE);`
`cropImageView.setScaleType(ImageView.ScaleType.CENTER_INSIDE);`

**Comment by ArthurHub** [comment]
I've tried everything but I can't reproduce it
Also noticed that the black line contains gradient so it can't be rounding issue.

Can you create a simple project that recreates the issue?

**Comment by ArthurHub** [comment]
Sorry, after much work on latest version I still was unable to reproduce it, string to think it's not  a bug in the library...
If you still have this issue and are willing to work on it, I am too, let me know.
