### ISSUE TITLE
Custom Crop Shape

### ISSUE THREAD

**Issue by abhinav011085** [ArthurHub/Android-Image-Cropper#382]
Is it possible to use my custom shape?

**Comment by TheOneMonkey** [comment]
Not for sure, go a head and the check it, https://github.com/ArthurHub/Android-Image-Cropper/wiki.

Can you help me to figure out the solution for my problem
https://github.com/ArthurHub/Android-Image-Cropper/issues/381

I am a starter to Android, hope you will help me.

**Comment by ArthurHub** [comment]
nope, that is super complicated
