### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by saeedmozaffari** [ArthurHub/Android-Image-Cropper#383]
i have following error from image cropper

```java

Caused by java.lang.NoClassDefFoundError
--
  | com.theartofdev.edmodo.cropper.BitmapUtils.rotateBitmapByExif (BitmapUtils.java:86)
  | com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground (BitmapLoadingWorkerTask.java:92)
  | com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground (BitmapLoadingWorkerTask.java:26)
  | android.os.AsyncTask$2.call (AsyncTask.java:288)
  | java.lang.Thread.run (Thread.java:841)
```
my app user got this error and i did not encounter this error.
also proguard is enable

current version of image cropper is '2.4.0'. 
android device : Y625-U32 
android version: 4.4.2

**Comment by ArthurHub** [comment]
Looks like you need to add some pro-guard rules, please update the post so I can add it to FAQ

**Comment by ArthurHub** [comment]
well.. if you decide to care please post in #238
