### ISSUE TITLE
Don't find crop option on toolbar 

### ISSUE THREAD

**Issue by atarek017** [ArthurHub/Android-Image-Cropper#384]
![screenshot_2017-09-13-16-35-27](https://user-images.githubusercontent.com/26245770/30383340-c15bef7a-98a1-11e7-9115-8a9d4a685711.png)

**Comment by atarek017** [comment]
@ArthurHub

**Comment by Shahjahan786** [comment]
Add CropImageActivity into your AndroidManifest.xml

<activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
  android:theme="@style/Base.Theme.AppCompat"/>
