### ISSUE TITLE
Accepts all kinds of files, including PDF and others

### ISSUE THREAD

**Issue by brntsw** [ArthurHub/Android-Image-Cropper#385]
Hello,

I am trying to validate the file extension from a file coming from the Google drive to accept only "jpg" and "png", but the URI comes with no extension and the library does not seem to handle that, as the error variable on the onSetImageUriComplete method is always null. If I proceed selecting a PDF, for example, the library tries to load it and fails, as nothing is shown. How could I handle that? Any ideas?

Thanks

**Comment by ArthurHub** [comment]
duplicate #200
