### ISSUE TITLE
Compress cropped image into respective size after user croping

### ISSUE THREAD

**Issue by TheOneMonkey** [ArthurHub/Android-Image-Cropper#387]
I have viewed [https://github.com/ArthurHub/Android-Image-Cropper/wiki/Limit-cropped-image-result-min-max-size](url) the code restricts the user to limit their size from min to max. 

Then how can I implement, user can crop their image in their respective size with out any restrictions except square box, but after their selection, how can I compress to respective size (Example - 150*150)

**Comment by ArthurHub** [comment]
See: https://github.com/ArthurHub/Android-Image-Cropper/wiki/FAQ#how-can-i-limit-the-size-of-the-cropped-image
