### ISSUE TITLE
Support Library update merge error

### ISSUE THREAD

**Issue by eduardo-santos** [ArthurHub/Android-Image-Cropper#388]
Hi, i configured all my graddle support libraries to use '26.+' and the image cropper library to '2.5.+', and this worked properly since i configured (one month ago), but today i've got a merged error saying that i have to use support library version '26.0.2'. My question is: you need to update the support library of the image cropper to work properly again?

**Comment by Tiganimohammad** [comment]
ihave the same problem  @snow3king i added what you mentioned but nothing happened

**Comment by eduardo-santos** [comment]
Thank you for your reply @snow3king , it's working now with your changes.

**Comment by danponce** [comment]
It happened the same to me but it says this:
Error:Failed to resolve: com.android.support:exifinterface:26.0.2
Error:Failed to resolve: com.android.support:appcompat-v7:26.0.2
Error:Failed to resolve: annotationProcessor

**Comment by ArthurHub** [comment]
make sure you update all the relevant bits that I had to do in this commit: https://github.com/ArthurHub/Android-Image-Cropper/commit/85b624ca736d343cb8790808af73613d9f11c48c

**Comment by justluvher** [comment]
i soved this problem 
app build.gradle. 

comileSdkVersion 26
buildToolsVersion '26.0.1'
compile 'com.android.support:appcompat-v7:26.0.1'

main build.gradle  add maven url.

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"  -> 
        }
    }
