### ISSUE TITLE
MS office showing even set false documen in Mi 4i device

### ISSUE THREAD

**Issue by sohijain** [ArthurHub/Android-Image-Cropper#392]
i am using this code :
`    startActivityForResult(CropImage.getPickImageChooserIntent(this, "Select Image",false, false), 200);
  ` and set false for document but in chooser dialog its showing MS Office . how can i resolved this issue?

**Comment by ArthurHub** [comment]
"document" is a special activity, the idea is not to filter document supporting apps.
feel free to start activity picker by yourself, the given code intention is for simple use and quick start
