### ISSUE TITLE
need translate word crop in activty CropImageActivity to arabic word

### ISSUE THREAD

**Issue by kickstartinteractiveandroidteam** [ArthurHub/Android-Image-Cropper#393]

**Comment by sweta01** [comment]
Hi ArthurHub,

I am getting stuck in cropper. please help me asap.

I want to get hieght and width when image croping in cropper window . please let me know if any method is available.

**Comment by ArthurHub** [comment]
see https://github.com/ArthurHub/Android-Image-Cropper/wiki/Activity-Visual-Customization
