### ISSUE TITLE
2.5.0 Gradle errors

### ISSUE THREAD

**Issue by danponce** [ArthurHub/Android-Image-Cropper#395]
When updating to version 2.5.0 it's throwing me this errors in Gradle app file:

Error:Failed to resolve: com.android.support:exifinterface:26.0.2
Error:Failed to resolve: com.android.support:appcompat-v7:26.0.2
Error:Failed to resolve: annotationProcessor

I tried to update the com.android.support.appcompat library to 26.0.2 and add the exifinterface library but with no success. Any ideas?

**Comment by ArthurHub** [comment]
see the changes I had to do in this comment: https://github.com/ArthurHub/Android-Image-Cropper/commit/85b624ca736d343cb8790808af73613d9f11c48c

**Comment by mamunx** [comment]
Same problem, i tried to add your library but giving errors:

Error:Failed to resolve: com.android.support:exifinterface:26.0.2
Error:Failed to resolve: com.android.support:appcompat-v7:26.0.2
Error:Failed to resolve: annotationProcessor

Any help would be really appreciated. Thanks a lot. btw I saw the changes in your comment, but i couldn't understand. I am new in Android Programming. Please Help

**Comment by ArthurHub** [comment]
see #396
