### ISSUE TITLE
getting this error on gradle sync 

### ISSUE THREAD

**Issue by uday-mshr** [ArthurHub/Android-Image-Cropper#396]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.1.0) from [com.android.support:design:26.1.0] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:exifinterface:26.0.2] AndroidManifest.xml:25:13-35 value=(26.0.2).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**Comment by pingothedoer** [comment]
Hi, found any solution? I am having same issue.

**Comment by gcrescent** [comment]
I think to fix this they must update the Android Support library to 26.1.0

**Comment by ArthurHub** [comment]
see #396

**Comment by zameelpichen** [comment]
the problem still persists

**Comment by safakesberk** [comment]
the problem still persists, to add 'tools:replace="android:value" didn't fix

**Comment by araujobarret** [comment]
The problem still persists for me too.

package.json
```
...
"dependencies": {
  "react-native-camera": "^0.13.0",
}
...
```
