### ISSUE TITLE
Need circle and square - not oval or rectangle.

### ISSUE THREAD

**Issue by Rainer-Lang** [ArthurHub/Android-Image-Cropper#4]
I need both: A circle (not an oval) and also a square (not rectangle).
How can this be done?

**Comment by ArthurHub** [comment]
fixed aspect ration with equal width and height

**Comment by Rainer-Lang** [comment]
But width und height shouldn't be fix.

**Comment by Rainer-Lang** [comment]
btw great lib!

**Comment by Rainer-Lang** [comment]
Found it!
```java
mCropImageView.setAspectRatio(1, 1);
mCropImageView.setFixedAspectRatio(true);
```

**Comment by ZhengXiaoWu** [comment]
I use this 
```
setFixedAspectRatio(true);
```
show a circle

**Comment by Radhika026** [comment]
I want to use fix aspect ratio of 1:1 and already tried this but not working.

 // Here we will pick image from gallery or camera
    private void pickFromGallery() {
        CropImage.activity().setAspectRatio(1,1);
        CropImage.activity().setFixAspectRatio(true);
        CropImage.activity().start(NewMemberForm.this);
    }

**Comment by Brijesh-kumar-sharma** [comment]
if you want circle then select crop image type oval , set aspect ration 1,1 & fixaspect ratio true it will give you circle
