### ISSUE TITLE
[Suggestion] Support library

### ISSUE THREAD

**Issue by j-garin** [ArthurHub/Android-Image-Cropper#405]
Hi. I have a suggestion for you. Could you please use
`implementation 'com.android.support:exifinterface:<your version>`
or
```
compile ('com.android.support:exifinterface:<your version>) {
    transitive = false
}```
to avoid support library version conflicts in following versions?  Thank you.

**Comment by ArthurHub** [comment]
Can you link some documentation explaining what it does?

**Comment by lisawray** [comment]
I suspect this is related:

> Error:Execution failed for task ':app:processDebugManifest'.
Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.1.0) from [com.android.support:design:26.1.0] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:exifinterface:26.0.2] AndroidManifest.xml:25:13-35 value=(26.0.2).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

To fix it, I have to put in my own build.gradle:

    implementation 'com.theartofdev.edmodo:android-image-cropper:2.5.0', {
        exclude group: 'com.android.support', module: 'exifinterface'
    }

I'm no gradle expert but I hope that helps understand what's going on!

**Comment by j-garin** [comment]
@lisawray exactly
@ArthurHub transitive libraries will be available in modules, which depend on your library. This can cause issues when people use other library versions than you. @lisawray gave you a good example just above. If you set transitive to false, such conflicts will no longer occur even without that workaround.
More info on that here: [official gradle docs](https://docs.gradle.org/4.2/userguide/dependency_management.html#client-modules)

**Comment by ArthurHub** [comment]
added in 2.5.1, hope it solves the merge issue, thx @j-garin
