### ISSUE TITLE
choosen image is not showing in the crop activity..

### ISSUE THREAD

**Issue by yash59** [ArthurHub/Android-Image-Cropper#408]
![whatsapp image 2017-10-03 at 5 24 32 pm](https://user-images.githubusercontent.com/27333071/31123922-db29e3c6-a85f-11e7-9daf-1cea3eca5ce1.jpeg)

**Comment by yash59** [comment]
here is my code..
      CropImage.activity()
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setCropShape(CropImageView.CropShape.RECTANGLE)
                        .setAspectRatio(1,1)
                        .start(Profile_upload.this);

**Comment by ArthurHub** [comment]
is there an error in logcat?

**Comment by shekharmohite** [comment]
I observe problem. To solve problem we need to change in CropImageActivity.java class, I added following lines, issue get resolved, 

 ```
@Override
    protected void onRestoreInstanceState(Bundle bundle) {
        super.onRestoreInstanceState(bundle);

        if (bundle != null) {
            mCropImageUri = bundle.getParcelable(CropImage.CROP_IMAGE_EXTRA_SOURCE);
            mOptions = bundle.getParcelable(CropImage.CROP_IMAGE_EXTRA_OPTIONS);
        }
    }


    @Override
    protected void onSaveInstanceState(Bundle outState) {
        if (mCropImageUri != null){
            outState.putParcelable(CropImage.CROP_IMAGE_EXTRA_SOURCE, mCropImageUri);
            outState.putParcelable(CropImage.CROP_IMAGE_EXTRA_OPTIONS, mOptions);
        }

        super.onSaveInstanceState(outState);
    }
```

because of some mobile camera intent kills android activity so that purpose we need to save bundle data and restore it, for that we need to override savedInstance and restore instance methods.
