### ISSUE TITLE
After Cropping a image, they returning a null bitmap.

### ISSUE THREAD

**Issue by brunocardosor** [ArthurHub/Android-Image-Cropper#409]
public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == CropImage.PICK_IMAGE_CHOOSER_REQUEST_CODE) {
            Uri imageUri = CropImage.getPickImageResultUri(getContext(), data);
            CropImage.activity(imageUri).setAspectRatio(1, 1).start(getContext(), this);
        }
        if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            if (resultCode == Activity.RESULT_OK) {
                Bitmap bitmap = result.getBitmap();
                profileImage.setImageBitmap(bitmap);
            } if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                Exception error = result.getError();
                Toast.makeText(getContext(), error.getMessage(), Toast.LENGTH_LONG).show();
            }
        }
    }

this is my code, so when select area and click to crop, they returning a null bitmap...

**Comment by ArthurHub** [comment]
the image is returned via uri, please read the documentation

**Comment by brunocardosor** [comment]
Oh, o saw the method, so i tried use then.
