### ISSUE TITLE
Does not work in Async Task

### ISSUE THREAD

**Issue by pipipzz** [ArthurHub/Android-Image-Cropper#41]
I am using this library to crop an image selected from the phone album. If the image is large and crop the image, it takes some time to crop and it does that on the main UI thread because of that I am not able to show a progress dialog. The progress dialog becomes visible only after the cropping has been done which is better than having a progress dialog. So I tried putting the code inside an Async Task and when I ran, it gave an error that the cropping function has to run on UI thread. Is there any way to solve this?

**Comment by ArthurHub** [comment]
yep, using `setImageUriAsync` and `getCroppedImageAsync` methods that use async task internally available since **v1.1.0** 
see: [Android Image Cropper async support and custom progress UI](http://theartofdev.com/2016/01/15/android-image-cropper-async-support-and-custom-progress-ui/)

**Comment by pipipzz** [comment]
@ArthurHub hey, thanks a lot. I just updated the library. Nice work !!!
