### ISSUE TITLE
Start Crop Activity from AppCompatActivity not working

### ISSUE THREAD

**Issue by soyuznii** [ArthurHub/Android-Image-Cropper#410]
when starting the crop activity from an existing uri the crop activity doesnt show in appcompatactivity

Intent intent = CropImage.activity(Uri.parse(n))
                                    .setGuidelines(CropImageView.Guidelines.ON)
                                    .getIntent(activity);
                            startActivityForResult(intent, CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE);

**Comment by ArthurHub** [comment]
The sample app, quick-start and test apps in the project use `AppCompatActivity` so that's not the issue.
Check logcat, make sure `Uri.parse(n)` doesn't throw an exception, Android doesn't just fail.
