### ISSUE TITLE
Can i input image is download from url ?,it just inside app, not available on device?

### ISSUE THREAD

**Issue by dinhhoi1102** [ArthurHub/Android-Image-Cropper#411]
thanks a lot, It is awesome library, it worked perfectly for me with input is image available on device, but my question is " can input file  image is downloaded from url,it just inside app, not available on device?",Do I have to download it in to device or have another way?(sorry for my english )

**Comment by ArthurHub** [comment]
You need to download the image yourself, there are a lot of open source libraries that can do that.

**Comment by dinhhoi1102** [comment]
your mean is i need download image in my app in to device then use your library

**Comment by ArthurHub** [comment]
yes

**Comment by dinhhoi1102** [comment]
thanks a lot,good day to you ^^
