### ISSUE TITLE
Failed to load sampled bitmap:

### ISSUE THREAD

**Issue by tarunsantu** [ArthurHub/Android-Image-Cropper#416]
java.lang.RuntimeException: Failed to load sampled bitmap: file:///storage/emulated/0/file1507719041982.jpg
                                                                /storage/emulated/0/file1507719041982.jpg (No such file or directory)

**Comment by ArthurHub** [comment]
How did you start the activity?
Which file to you pick?

**Comment by tarunsantu** [comment]
For this...
java.lang.RuntimeException: Failed to load sampled bitmap: file:///storage/emulated/0/file1507719041982.jpg
/storage/emulated/0/file1507719041982.jpg (No such file or directory)

try to change the saving mode of your file.

save file in this way....




 Bitmap photo = (Bitmap) data.getExtras().get("data");
                //captured_photo.setImageBitmap(photo);

                String root = Environment.getExternalStorageDirectory().toString();
                File myDir = new File(root + "/DCIM/myCapturedImages");
                myDir.mkdirs();
                Random generator = new Random();
                int n = 10000;
                n = generator.nextInt(n);
                String fname = "FILENAME-"+ n +".jpg";
                File file = new File (myDir, fname);

                if (file.exists ()) file.delete ();
                try {
                    FileOutputStream out = new FileOutputStream(file);
                    photo.compress(Bitmap.CompressFormat.JPEG, 100, out);
                    Toast.makeText(MainActivity.this, "Image Saved", Toast.LENGTH_SHORT).show();
                    out.flush();
                    out.close();

                } catch (Exception e) {
                    e.printStackTrace();
                }




This will work

**Comment by tarunsantu** [comment]
I got it....Thanks for your Library, It worked awsm...

**Comment by prabhakar612** [comment]
what is the solution for this issue, I'm still facing this issue.

**Comment by donhill** [comment]
The issue seems to be coming when calling `CropImage.getActivityResult(data)` the result contains the error from above. It seems the image has changed in newer versions.

Looking at the solution above where exactly did you change this code as the CropActivity still has control.

**Comment by sachin-varshney** [comment]
Replace the method getCaptureImageOutputUri in the CropImage.java file with the below code, might solve the problem.
it worked for me

public static Uri getCaptureImageOutputUri(@nonnull Context context) {
Uri outputFileUri = null;
File getImage = context.getExternalCacheDir();
if (getImage != null) {
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
outputFileUri = FileProvider.getUriForFile(context, BuildConfig.APPLICATION_ID + ".provider",
new File(getImage.getPath(), "pickImageResult.jpeg"));
} else {
outputFileUri = Uri.fromFile(new File(getImage.getPath(), "pickImageResult.jpeg"));
}
}
return outputFileUri;
}

**Comment by hueimin426** [comment]
> 

Hi May I know how you edit the read-only CropImage.class file?
