### ISSUE TITLE
getCropRect() wrong coordinates

### ISSUE THREAD

**Issue by gerc99** [ArthurHub/Android-Image-Cropper#418]
On samsung devices the coordinates are confused, although in the correct orientation of the bitmap

**Comment by ArthurHub** [comment]
Example?

**Comment by rupinderjeet** [comment]
This happened to me today. An image had width of 2218. But, `getCropRect()` says that `rect.right`[]() is 2220.

I have attached a sample image from dropbox.

https://www.dropbox.com/sh/94fxu6hnpyfxabk/AAAqYtQnRrpVmxcCEVRzSKyea?dl=0
