### ISSUE TITLE
cropMinCropWindowWidth and cropMinCropWindowHeight don't seem to work

### ISSUE THREAD

**Issue by clocksmith** [ArthurHub/Android-Image-Cropper#42]
```
  <com.theartofdev.edmodo.cropper.CropImageView
      xmlns:custom="http://schemas.android.com/apk/res-auto"
      android:id="@+id/cropImageView"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      custom:cropScaleType="fitCenter"
      custom:cropGuidelines="onTouch"
      custom:cropFixAspectRatio="true"
      custom:cropBorderLineThickness="1dp"
      custom:cropBorderCornerThickness="1dp"
      custom:cropMinCropWindowWidth="1px"
      custom:cropMinCropWindowHeight="1px"/>
```

All of the attrs work except the min crop window ones. I have tried both dp and px. Looking in the src, it looks like the default is 40.

**Comment by ArthurHub** [comment]
* `cropMinCropWindowWidth/Height` sets min limit on cropping window width/height in the UI used to have good cropping UX.
* `cropMinCropResultWidthPX/HeightPX` sets min on cropping image result width/height used to limit the actual cropped image result.

Combined the actual min during cropping is the max value between the two.
The ddefault for min crop result is 80 pixels, I assume the density in 2 so you see it as 40dp.

Hope it make sense.

**Comment by clocksmith** [comment]
Ok thanks that explains how they are supposed to work, but they still don't seem to change anything when set. I have tried everything from 1dp to 100dp and the minimum cropping rectangle is always the same. Can somebody confirm that it works for them?

**Comment by clocksmith** [comment]
<img width="483" alt="screen shot 2016-03-06 at 10 20 29 pm" src="https://cloud.githubusercontent.com/assets/591699/13560105/b44f55a6-e3e9-11e5-83fb-90b045cebd3f.png">

This is as small as it goes, but i need it to go smaller.

**Comment by clocksmith** [comment]
I now understand what you mean by the max between the 2.
I got what I wanted with:

```
      custom:cropMinCropWindowWidth="1px"
      custom:cropMinCropWindowHeight="1px"
      custom:cropMinCropResultWidthPX="1"
      custom:cropMinCropResultHeightPX="1"
```

**Comment by ArthurHub** [comment]
Yes, sorry I wasn't clear.
