### ISSUE TITLE
Some samples issues

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ArthurHub/Android-Image-Cropper#420]
I've noticed some issues with the samples:

1. The sample of "sample" requires camera permission , even though it should run just fine without it, as there are other ways to get an image (from storage, for example), as is done on "quick-start" sample.
2. The "Done" action item icon has circle background, in the "quick-start" sample
3. The "quick-start" sample marks a circle crop, but when cropping, it's a normal rectangle.
4. The toolbar icons/text sometimes have different color from others, like on the "sample" sample and the "test" sample.
5. The navigation drawer on the "sample" sample cannot be opened easily at all via swiping from the left. Clicking at the top is the only safe way to do it.
6. On the "sample" sample , the multitouch feature seems a big buggy in how it works. Hard to explain. However, I can say that I can't zoom or pan using it. I don't understand what it's used for.
7. When rotating the result activity (the one that's shown after finished cropping), the image is gone.

**Comment by ArthurHub** [comment]
1. There a "feature" in Android that you must explicitly request CAMERA permission on Android M and above when you open intent if you requested it in manifest, see fixes in versios 2.1.4
2. I tested changing the icon and was lazy to use a different icon, why?
3. See FAQ: [Why is the cropped image rectangular when I used oval crop shape?](https://github.com/ArthurHub/Android-Image-Cropper/wiki/FAQ#why-is-the-cropped-image-rectangular-when-i-used-oval-crop-shape)
4. So?
5. It's a sample app to play around...
6. Multitouch was added in PR without real effort, I probably should just delete it
7. It's a sample app.. why it's important?

**Comment by AndroidDeveloperLB** [comment]
1. Sorry for that. I didn't know.
2. It's just that it doesn't look well on the toolbar. You should have used a more native one.
3. So what's the use of cropping in oval shape, if it doesn't do anything? I don't get it. It does the exact same thing as rectangle cropping.
4. It looks bad currently. Items on the toolbar should have consistent colors. 
5. Question is how to fix it in case we use it in an app, that needs to have this view, together with a drawer, and why can't it work well on the sample.
6. I see.
7. If I rotate the screen while using this library, I should know how to handle it well, including still showing the image and also have the cropping&zooming states restored. The sample doesn't show this important thing. It has bugs regarding this.

**Comment by ArthurHub** [comment]
None of the points you mention affect the library, samples are used to showcase the library capabilities and help contributors debug. 
It's not shipped with the library and not intended to educate android development. 
But if you feel so strongly about it, please send a PR

**Comment by AndroidDeveloperLB** [comment]
I don't understand. Shouldn't the sample work fine with the library?
How can you demonstrate how to use it properly, without a sample?
Currently I see not just cosmetic issues (incorrect icons and colors), but also crucial ones (incorrect cropping, inability to use drawer with this view,  and incorrect handling of configuration changes). How doesn't it affect the library?
A sample should show the library at its best.
Not being able to handle very common scenarios, and features of the library, inside the sample, shows that the library could have issues.
If the library isn't the one that has issues, the sample should be updated. If the library has issues, the library should be updated.
In any case, there should be fixes.

**Comment by ArthurHub** [comment]
Well, we don't have to agree. 
The beauty of open source is that anyone can contribute. I see you're passionate about the sample app, so please fix and send a PR.

**Comment by AndroidDeveloperLB** [comment]
I can't fix something that I don't know the reason for why it's faulty.
best the creator to know how to fix it.
Why doesn't the cropping in oval shape work?
What's the way to save the state of the view, across configuration change?
What's the correct way to use the view, if there is a drawer?

Those questions cannot be answered by me, as I've only recently was even aware of this library.

**Comment by AndroidDeveloperLB** [comment]
The only things I can fix, which are very easy, are the cosmetic ones.

**Comment by ArthurHub** [comment]
That's how software works, you see something that you think is wrong.. Let's say oval bitmaps, you do the research on how stuff work in bitmaps, in alpha chsnnels, in Android image api, Android rendering api, performance considerations, etc. you debug the source to see how the flow goes, what api it's using and where is the code responsible for the issue you're looking into. 
By now you may learn that what you thought is incorrect is actually a software compromise that has to be there, or you discover that there is a better way to solve this problem and you have a lead on how to solve it. 

That's what I do, every day, that's software development.

**Comment by AndroidDeveloperLB** [comment]
I don't see any way that oval bitmap cropping should behave exactly like rectangle one.
About the output bitmap, if it has alpha, it should be used, and if not, the function to crop should require a color to set for around the circle.
But in no possible scenario, an oval crop should return the exact same image as rectangle one (unless the input bitmap is oval too, of course).
There is no compromise here. It's a bug.

**Comment by AndroidDeveloperLB** [comment]
Please explain.
Why the correct behavior of oval cropping should be rectangle cropping?
Why can't it always be oval, as this is the name of the function?
Why, if the function doesn't do oval cropping, does it even exist?

**Comment by ArthurHub** [comment]
The FAQ briefly explains that, I don't want to go into lengthy discussion beyond that.

**Comment by AndroidDeveloperLB** [comment]
If you mean this:

> The resulting cropped image is always rectangular simply because bitmaps are.
> Usually, the oval shape is created during rendering of the image, there are many solutions for it.
> But if you do want the resulting image pixels to reflect the oval shape you can use CropImage.toOvalBitmap(Bitmap) helper method that does exactly that.

That's not what I meant. I didn't mean why the bitmap is rectangular. Bitmaps are supposed to be rectangular, as they have width and height to define their rectangle shape size.
I mean why the content is not oval, within the bitmap. 

See here:
"sample" project does correct circular cropping:
![image](https://user-images.githubusercontent.com/5357526/31844411-31992402-b601-11e7-989e-6e1f303d7c56.png)


But "quick-start" project doesn't: 
![image](https://user-images.githubusercontent.com/5357526/31844389-0ef8d3ac-b601-11e7-92b5-126609e45992.png)

It's the exact same input image.

**Comment by AndroidDeveloperLB** [comment]
So again, why should it work differently?

**Comment by AndroidDeveloperLB** [comment]
And, how can I make the view retain its state?
And if there is a drawer, how should it work with the view?

**Comment by ArthurHub** [comment]
Debug the code

**Comment by AndroidDeveloperLB** [comment]
Well, the triggers seem to be ok. On both samples, they do pass that they wish it to be oval-shaped cropping.
I tried to dig for a clue for this issue, but I just can't find a usage of the oval-shape cropping on "quick-start" sample. 

This is called:

![image](https://user-images.githubusercontent.com/5357526/31851079-32f13cb6-b667-11e7-865e-41b2e6dea956.png)

So I don't see a call to using the shape here. 
The result bitmap is sent back to the view:

![image](https://user-images.githubusercontent.com/5357526/31851090-69aff666-b667-11e7-8b21-e8df17d481bb.png)

Which does nothing special to it either (and it shouldn't, because the cropping should be done on the bitmap before it's sent to it) :

![image](https://user-images.githubusercontent.com/5357526/31851095-7840f324-b667-11e7-90ef-e7e489679b44.png)

Even on "CropImageActivity" , I don't see the shape being used:

![image](https://user-images.githubusercontent.com/5357526/31851123-033b5c1c-b668-11e7-98e0-963470093444.png)

Again, I'm not familiar with the code, but to me it seems that everything starts fine, but when the time comes to crop the image, the shape is ignored.

**Comment by AndroidDeveloperLB** [comment]
Why close it? Have you fixed it?

**Comment by ArthurHub** [comment]
like I said before, this is not a bug

**Comment by AndroidDeveloperLB** [comment]
How can it not be a bug?
It calls to crop in an oval shape, but it doesn't crop in oval shape, even though on another sample, it does work fine.
