### ISSUE TITLE
Bug (?) : cannot provide Uri to an Internet image file (URL) or to a contact photo?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ArthurHub/Android-Image-Cropper#422]
If I provide the CropImageView with a Uri to a URL address of an image file, or to a contact photo, I don't see that it gets loaded and viewed.

How come?
Does it only accept Uris of local storage?

**Comment by ArthurHub** [comment]
yes, it only supports android storage uri

**Comment by AndroidDeveloperLB** [comment]
So please consider updating the description. It doesn't say it's limited to storage alone (using the SAF API).
This is the current description:

> Set cropping image as Bitmap, Resource or Android URI (Gallery, Camera, Dropbox, etc.).

**Comment by ArthurHub** [comment]
Android uri means Android, not web

**Comment by AndroidDeveloperLB** [comment]
Android uri can be of contacts, of Internet, and of anything the contentProvider allows...

**Comment by ArthurHub** [comment]
Will update the documentation

**Comment by AndroidDeveloperLB** [comment]
Thank you
