### ISSUE TITLE
Invalid appcompat version in test build.gradle

### ISSUE THREAD

**Issue by yvlad** [ArthurHub/Android-Image-Cropper#425]
https://github.com/ArthurHub/Android-Image-Cropper/blob/master/test/build.gradle#L19

Version of appcompat is invalid, and possibly must be `$supportLibraryVersion`.

Current variant:
```groovy
compile "com.android.support:appcompat-v7:6.0.2"
```

Should be:
```groovy
compile "com.android.support:appcompat-v7:$supportLibraryVersion"
```

**Comment by ArthurHub** [comment]
fixed, thanks
