### ISSUE TITLE
How to start the crop rectangle with a custom size?

### ISSUE THREAD

**Issue by hungMta** [ArthurHub/Android-Image-Cropper#433]
I'm trying to set the crop rectangle size to 30:25 when the activity is initialed. Please help me!

**Comment by GithubRyze** [comment]
CropImage.activity(imageUri).setMaxCropResultSize(100,100).start(this);  you can use above code with a custom size,  SetMaxCropResultSize or SetMinCropResultSize. hope it is help to you!!

**Comment by Redman1037** [comment]
Try this

         cropImageView.setAspectRatio(30, 25);
         cropImageView.setFixedAspectRatio(true);
