### ISSUE TITLE
Compile with 27.0.0

### ISSUE THREAD

**Issue by Transformat** [ArthurHub/Android-Image-Cropper#440]
Hi the library is based on 26.0.2 but the latest version is 27.0.0. Can you please update the library as it is causing some errors.

**Comment by AhmadullahSaikat** [comment]
27.0.1

**Comment by HaghighatDoost** [comment]
please update to 27.0.1

**Comment by Jadnap** [comment]
Yeah please update it.

**Comment by AndroidDeveloperLB** [comment]
I thought that when a repo is using an old version, and yet the app uses newer one, it replaces the one the repo uses, no?

**Comment by ArthurHub** [comment]
done, and moved to gradle v3
