### ISSUE TITLE
Fixed version

### ISSUE THREAD

**Issue by BrunoCarrier** [ArthurHub/Android-Image-Cropper#45]
Hi,

this doesn't work (compile 'com.theartofdev.edmodo:android-image-cropper:1.2.3') despite your page on Github saying 1.2.3 is the latest version

Would it be possible to disclose what is the latest version?  My internet connection went down and I couldn't develop anymore since Gradle was trying to resolve the latest version and couldn't connect to the internet.  

By the way, congratulations on this fantastic API!  I love it :)

Bruno

**Comment by ArthurHub** [comment]
Not sure what happened, looks like a publish bug in jCenter.
I've republished the latest version (1.2.3) and it should work now, sorry for not testing it myself previously.
Huge thanks for reporting the issue!
