### ISSUE TITLE
Whole image getting display on capturing via Camera

### ISSUE THREAD

**Issue by patelrohan22** [ArthurHub/Android-Image-Cropper#450]
In my app there are 2 option pick image.

1. From Gallery
2. From Camera

Cropping on gallery image is working fine, while a image which i capture via camera don't have any effect of cropping area. Its always show original image into imageview.

**Comment by ArthurHub** [comment]
can you reproduce it using the sample app?

**Comment by patelrohan22** [comment]
its fixed
