### ISSUE TITLE
error when using latest support library

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ArthurHub/Android-Image-Cropper#452]
![image](https://user-images.githubusercontent.com/5357526/33391276-27437a84-d541-11e7-8fb4-54d27e4a1f4f.png)

**Comment by AndroidDeveloperLB** [comment]
Workaround: add something to override it:

compile 'com.android.support:exifinterface:27.0.2'

**Comment by ArthurHub** [comment]
duplicate #440
