### ISSUE TITLE
Proguard Settings

### ISSUE THREAD

**Issue by vikassable** [ArthurHub/Android-Image-Cropper#453]
Could you please specify Prguard settings for the project? Your lib is really awesome but we are facing issues with release build. 
Without `+-dontwarn com.theartofdev.edmodo.cropper.**` option proguard-rules.pro file, build is failing with unresolved reference.
When above option has been added, we are getting release build but it is crashing now. Could you please, look into this? that would be really helpful.

**Comment by ArthurHub** [comment]
see #238
