### ISSUE TITLE
No bitmap in CropImage.Activity result

### ISSUE THREAD

**Issue by core2root** [ArthurHub/Android-Image-Cropper#460]
hi, i'm using CropImage.activity....
in onActivityResult method i get result from intent but this result bitmap object is null and the originalBitmap also null.

**Comment by ArthurHub** [comment]
When using activity you only get URI's, it's in the documentation: https://github.com/ArthurHub/Android-Image-Cropper/blob/master/cropper/src/main/java/com/theartofdev/edmodo/cropper/CropImageView.java#L2069

**Comment by core2root** [comment]
ok thank you.
