### ISSUE TITLE
Can I open the camera or gallery directly ? Either Camera or Gallery in option ?

### ISSUE THREAD

**Issue by sayami007** [ArthurHub/Android-Image-Cropper#470]

**Comment by AhYousefi** [comment]
I also have the same question please answer

**Comment by sayami007** [comment]
I got the hack 😆 
For Gallery:

void openGallery(){
           Intent getPictureIntent = new Intent();
            getPictureIntent.setType("image/*");
            getPictureIntent.setAction(Intent.ACTION_GET_CONTENT);
            activity.startActivityForResult(getPictureIntent, Constant.CODE_PICK_IMAGE_GALLERY);
}

 public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (resultCode == RESULT_OK) {
            if (requestCode == Constant.CODE_PICK_IMAGE_GALLERY) {
                Uri imageUri = data.getData();
                CropImage.activity(imageUri).start(activity);
}
}

Similar way can be done for camera as well.. We just have to use the Uri 😄
