### ISSUE TITLE
Is there a way that I can crop an image right after take the picture without opening the image picker?

### ISSUE THREAD

**Issue by rickpms** [ArthurHub/Android-Image-Cropper#491]
`protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode == CAMERA_REQUEST && resultCode == Activity.RESULT_OK) {

            CropImage.activity(data.getData())
                    .start(this);`

I thought doing that way with this library I would be able to get to crop right away after take a picture but instead it takes me to gallery again to select a picture. 

Is there a way that I can crop an image right after take the picture instead of opening the image picker?

**Comment by ArthurHub** [comment]
not that I know of, sry
