### ISSUE TITLE
Please don't use dynamic versions for dependencies

### ISSUE THREAD

**Issue by androideveloper** [ArthurHub/Android-Image-Cropper#496]
Please fix support library version for this library (don't use 27.+).

http://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/

**Comment by alexandersokol** [comment]
+1 remove this shit pls

**Comment by pparreno** [comment]
I concur. No wonder building our app threw out a ZipException

**Comment by ArthurHub** [comment]
Updated v2.7.0 to use static version, thanks @androideveloper for the link
