### ISSUE TITLE
Any news about further development?

### ISSUE THREAD

**Issue by Rainer-Lang** [ArthurHub/Android-Image-Cropper#5]
Are there any plans for future versions? Enhancements...?

**Comment by ArthurHub** [comment]
sorry, just started a new startup, allocating time is a bit hard =\

**Comment by ArthurHub** [comment]
maybe...

**Comment by Rainer-Lang** [comment]
What about your startup? I hope it is alright and you're fine.

**Comment by ArthurHub** [comment]
Going well, we are in alpha, thank you for asking :)
Have a little time so decided to do something different for day-to-day stuff.
