### ISSUE TITLE
Alpha channel is discarded

### ISSUE THREAD

**Issue by bpappin** [ArthurHub/Android-Image-Cropper#50]
If the selected image has an Alpha channel (transparent section) the transparent pixels are discarded during crop, and replaced with black pixels.

This may be a function of the BitmapRegionDecoder configuration.

**Comment by ArthurHub** [comment]
Just tested it in the sample app, the cropped image correctly contained alpha pixels in the shown crop result image view.
It may be a device specific issue, can you make sure you see the issue, maybe describe how you tested it.
thx.

**Comment by bpappin** [comment]
Hmm, let me check it again.
Can you attach the image you used for testing?

**Comment by bpappin** [comment]
Try with this image. This is the one that gave me a problem, and I'm now wondering if the type of image might a factor.

![vl9ujqeazi871b9ikj4u](https://cloud.githubusercontent.com/assets/3903833/14530180/bed59f26-0225-11e6-8fb9-86ef9e63d918.png)

**Comment by ArthurHub** [comment]
tried the image and it also works...
did you saved the image or viewed the resulting bitmap in app?
Side note, the image is too small enough that the library can use the loaded bitmap for cropping so it doesn't use `BitmapRegionDecoder`

**Comment by bpappin** [comment]
OK, let me investigate. Sounds like it might not be an issues, but I'll feel better once I can identify the issue.

**Comment by bpappin** [comment]
OK, i have confirmed that the cropper at least is not causing the alpha to be discarded.

I modified the library a little bit to use a checkered background, so I could more easily see transparencies, and since it is somewhat useful, I left it in the pull request.

**Comment by ArthurHub** [comment]
cool, will add it, thx.
