### ISSUE TITLE
Can i choose another image from gallery after pressing back 

### ISSUE THREAD

**Issue by nearohen** [ArthurHub/Android-Image-Cropper#511]

**Comment by Biplovkumar** [comment]
yup.u  can put another clickListener which clean the object and restart the image picker intent.

//ADD A BUTTON IN TOOL BAR:-

@Override
  public boolean onOptionsItemSelected(MenuItem item) {
    switch (item.getItemId()) {
      case R.id.action_home:

        Intent intent = getBaseContext().getPackageManager()
            .getLaunchIntentForPackage(getBaseContext().getPackageName());
        assert intent != null;
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        startActivity(intent);
        return true;
      default:
        // If we got here, the user's action was not recognized.
        // Invoke the superclass to handle it.
        return super.onOptionsItemSelected(item);

    }
  }

///start image import from default galary
    Intent intent = new Intent(Intent.ACTION_PICK,
        android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
    startActivityForResult(intent, 1);


  @Override
  protected void onActivityResult(int requestCode, int resultCode, Intent imageReturnedIntent) {
    super.onActivityResult(requestCode, resultCode, imageReturnedIntent);
    switch (requestCode) {
      case 1:
        if (resultCode == RESULT_OK) {
          Uri selectedImage = imageReturnedIntent.getData();
          mimageview.setImageURI(selectedImage);

**Comment by nearohen** [comment]
first

Thanks for the fast reply and thanks for the library !

i deleted the issue because i wanted to specify more clearly  what i mean
first , but you got it anyway and replied .

I started diving into the code and i concluded there is not much to be done
. please correct me if i'm wrong (i hope i'm wrong).


The problem is

 picking a good picture from asmall thumbnail is hard
and going through and scrolling again from the bigning of camera library
(that some times have thousands of pictures)  is frustraing


what i want is

After the user chose the image and croping has begun he decides that the
picture is not good enough.
than he wants another picture.

i would like to start picking from the gallery from the same sroll position
in the gallery .


if thats not possible or to much to implement

what i want is  -   that the picker activity will end only after viewing
the picture in full screen

like when taking image from camera - i have [ok] [retry] option and only
than the actual crop activity begins.
i want the same for gallery
maybe if the user take a good look at the picture in full screen  and only
when approving it the crop activity will begin.
and when going back (not approving) he will return to the same position  in
gallery,



give me  your opinion ,advice or maybe a workaround
Thanks alot again
