### ISSUE TITLE
Image orientation bug on Samsung devices

### ISSUE THREAD

**Issue by qcdyx** [ArthurHub/Android-Image-Cropper#52]
This is a very helpful library, but I'm facing an issue right now. When I take a portrait picture using camera on Samsung S4(Android 5.0.1), the image shown on CropImageView is displayed in landscape mode. I tried fixing image orientation based on ExifInfo, but it doesn't work; It seems like pictures taken by Samsung doesn't have any ExifInfo. In my previous apps, I fix Image orientation issue by using Picasso library. Not sure how to fix it in your library.

Could you help me? Thanks a lot!

**Comment by ArthurHub** [comment]
Do you use `setImageUriAsync(Uri)` method to set the image? if so it will read the exif data automatically.
How Picasso is helping you?

**Comment by qcdyx** [comment]
Yes, I use mCropImageView.setImageUriAsync(Uri.parse(mUriStr)) to set the image. I guess It doesn't work because there's no ExifInfo available. To be honest, I never dig deeply into how Picasso works. But every time I use Picasso.with(context).load(uri).into(imageView), it will fix the problem automatically.

**Comment by ArthurHub** [comment]
Without exif data I don't see how Picasso could "fix" it...
Can you upload an image taken from camera, maybe I don;t handle the exif data correctly..

**Comment by qcdyx** [comment]
![1](https://cloud.githubusercontent.com/assets/5789435/14677131/51c18b44-06de-11e6-850a-d2159621123f.png)
![2](https://cloud.githubusercontent.com/assets/5789435/14677132/51d20122-06de-11e6-975d-565b5c3aec66.png)

**Comment by ArthurHub** [comment]
I need to original image from camera, not screen capture, sorry I wan't clear

**Comment by qcdyx** [comment]
![original1_cropping](https://cloud.githubusercontent.com/assets/5789435/14678101/710a7ffc-06e2-11e6-88a6-c3ea896c36d0.png)
![original1](https://cloud.githubusercontent.com/assets/5789435/14678102/710d4d4a-06e2-11e6-93b8-b92e34d7187c.jpg)
![original2_cropping](https://cloud.githubusercontent.com/assets/5789435/14678110/765c8608-06e2-11e6-8818-1835e86ddcbd.png)
![original2](https://cloud.githubusercontent.com/assets/5789435/14678111/765cfcf0-06e2-11e6-8629-fea5b4965817.jpg)

**Comment by qcdyx** [comment]
Hi again, sorry, I told you wrong information. In this case, orientation == ExifInterface.ORIENTATION_ROTATE_90. I tried rotateImage(bitmap, 90) but it doesn't work.
    public static Bitmap rotateImage(Bitmap src, int degree) {
        int w = src.getWidth();
        int h = src.getHeight();

        Matrix mtx = new Matrix();
        mtx.postRotate(degree);
        Timber.e("degree: %d", degree);

        return Bitmap.createBitmap(src, 0, 0, w, h, mtx, true);
    }

**Comment by qcdyx** [comment]
Hi again, do you have an idea where the bug could be? Maybe I can help as I need this library for a project that needs to be delivered soon. Thanks for letting me know.

**Comment by ArthurHub** [comment]
I'm not sure as the images you uploaded are very confusing... the image with the coffee cup looks corrupted, half of it is white...
Lets help each other, I believe i will find the bug quickly when I get an image with the exif data. Unfortunately github changed the images, probably during the upload, can you upload them to this public [one drive folder](https://onedrive.live.com/redir?resid=D3212A92B75AB545!60943&authkey=!AJ5Jt1r2p0Fp1Ho&ithint=folder%2c), thx.

p.s. you should not rotate the image manually, when using `setImageUriAsync(Uri)` it should just work, it reads the exif data and does the rotation internally.
Also it's not clear to me when you rotates the bitmap...

**Comment by qcdyx** [comment]
I rotate the image in onActivityResult before the app goes to the cropping screen. The images should be there. Thank you and keep me posted.

**Comment by ArthurHub** [comment]
I don't get it... the images don't have exif data and are correctly oriented...
are you able to reproduce the issue in the library sample app?

**Comment by qcdyx** [comment]
Sorry for the delay. It takes me a while to get the sample run. It works for me. Any suggestions?

**Comment by ArthurHub** [comment]
Ok... I'm 98% sure the library handles the images correctly.

We need to understand what your code does different than the sample.
See `MainActivity.onActivityResult` method, there is a bit of code to handle new permissions system but basically it calls `mCurrentFragment.setImageUri(imageUri)` that will set the image for cropping using `mCropImageView.setImageUriAsync(imageUri)`.

`imageUri` is an Android reference URI instance that is retrieved from `CropImageHelper.getPickImageResultUri(this, data)` that has the logic to get the correct URI depending if the source is camera app of gallery app.

Note that it doesn't load the bitmap, or read the exif data at any point in the sample, all the work is done in `setImageUriAsync(Uri)` that is part of the library.

Now, what happens in your code?
If you can post it, that may help too.

**Comment by qcdyx** [comment]
I might know where goes wrong. In MainActivity.onActivityResult method, after the app gets mFileUri = CropImageHelper.getPickImageResultUri(this, data), it replaces the current fragment with a new fragment and displays the image in the new Fragment. Let me try something first and get back to you. Thank you.

**Comment by qcdyx** [comment]
Hi, it works now! Instead of replacing the current fragment with a new fragment, I create a pair of Activity and Fragment to display the image. I also use CropImageHelper.startPickImageActivity(this) instead of using my own methods.

**Comment by ArthurHub** [comment]
Awesome! glad it worked out.

**Comment by qcdyx** [comment]
Thank you for this amazing library!

**Comment by dhananjay23** [comment]
Hello Sir,  
           I am facing same problem for image capture in samsung device and image rotate automatically ,
           i have check other device but image is set potrait format , i have use picasso library to resize the 
          image.


Pleaase provide me any suggestion and help for solve this problem   !!!!!!
