### ISSUE TITLE
app>build.gradle - Runtime Gradle issue

### ISSUE THREAD

**Issue by prashant31191** [ArthurHub/Android-Image-Cropper#520]
after added

compile 'com.theartofdev.edmodo:android-image-cropper:2.6.+'

-------------

app\build\intermediates\multi-dex\debug\componentClasses.jar]

(Can't read [C:\Users\XXXXX\.gradle\caches\transforms-1\files-1.1\support-core-ui-27.1.1.aar\1fe26f8429e65a3fd8ade1df99ec415d\jars\classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:android/support/design/widget/CoordinatorLayout$Behavior.class]))

Error:Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't write [D:\XXX\....\app\build\intermediates\multi-dex\debug\componentClasses.jar] (Can't read [C:\Users\XXX\.gradle\caches\transforms-1\files-1.1\support-core-ui-27.1.1.aar\1fe26f8429e65a3fd8ade1df99ec415d\jars\classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:android/support/design/widget/CoordinatorLayout$Behavior.class]))

all version is 27.1.0

buildscript {

    ext {
        androidSupportVersion = '27.0.1'
...

**Comment by ArthurHub** [comment]
update to 2.7.0 that uses 27.1.1
