### ISSUE TITLE
How to setBorderLineThickness, setBorderCornerThickness and setBorderCornerLength with CropImageView

### ISSUE THREAD

**Issue by chimanaco** [ArthurHub/Android-Image-Cropper#521]
I followed [Using CropImageView in own Activity](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Using-CropImageView-in-own-Activity), but there are no methods for `setBorderLineThickness`, `setBorderCornerThickness` and `setBorderCornerLength`.

Any ways I can make them happen?

**Comment by ArthurHub** [comment]
set it via xml, see https://github.com/ArthurHub/Android-Image-Cropper/wiki/Visual-Customization

**Comment by chimanaco** [comment]
I got it. Thank you!
