### ISSUE TITLE
getCroppedImage() method does not display flogged counterclockwise

### ISSUE THREAD

**Issue by tweaker** [ArthurHub/Android-Image-Cropper#54]
Hello,
I tried to get a bitmap using the method getCroppedImage(), but since I was a turn counterclockwise (-90 degrees), for some reason he does not appear. Since turning clockwise all works well.

`cropImageView.rotateImage(-90);`

**Comment by ArthurHub** [comment]
Never tested counterclockwise.. silly me
fixed in **2.0.1**

**Comment by tweaker** [comment]
Everything works fine! Many thanks!
