### ISSUE TITLE
How can I enforce a Square Image to be chosen?

### ISSUE THREAD

**Issue by ousanmazCT** [ArthurHub/Android-Image-Cropper#558]

**Comment by ousanmazCT** [comment]
for square: 
                .setAspectRatio(300,300) does it:

        CropImage.activity(imageUri)
                .setGuidelines(CropImageView.Guidelines.ON)
                .setActivityTitle("Crop")
                .setAspectRatio(300,300)
                .setCropShape(CropImageView.CropShape.RECTANGLE)
                .setCropMenuCropButtonTitle("Done")
                .setRequestedSize(300, 300, CropImageView.RequestSizeOptions.RESIZE_FIT)
                .setCropMenuCropButtonIcon(R.drawable.crop_image)
                .start(mContext, this);

**Comment by LorenzoDD96** [comment]
and for circle?

**Comment by truthhonestmessaging** [comment]
> for square: .setAspectRatio(1,1) //does it:
> 
> ```
>     CropImage.activity(imageUri)
>             .setGuidelines(CropImageView.Guidelines.ON)
>             .setActivityTitle("Crop")
>             .setAspectRatio(1,1)
>             .setCropShape(CropImageView.CropShape.RECTANGLE)
>             .setCropMenuCropButtonTitle("Done")
>             .setRequestedSize(300, 300, CropImageView.RequestSizeOptions.RESIZE_FIT)
>             .setCropMenuCropButtonIcon(R.drawable.crop_image)
>             .start(mContext, this);
> ```

this didn't work for me. The cropping box is still a rectangle.
