### ISSUE TITLE
No Contect Provider Error in Library

### ISSUE THREAD

**Issue by vkiranmaniya** [ArthurHub/Android-Image-Cropper#559]
D/Cropped Image: java.lang.RuntimeException: Failed to load sampled bitmap: /storage/9016-4EF8/Picture/3_underdog_wallpaper_hi_res_black.png
                 No content provider: /storage/9016-4EF8/Picture/3_underdog_wallpaper_hi_res_black.png

**Comment by ShaunLWM** [comment]
The `uri` parameter requires a `file://` infront of the image path.
Use this to convert into a `uri` before passing it into the CropImageActivity .

`Uri.fromFile(new File(IMAGE_PATH))`

**Comment by vkiranmaniya** [comment]
Solved
