### ISSUE TITLE
Cropping photo throws SecurityException

### ISSUE THREAD

**Issue by LloydBlv** [ArthurHub/Android-Image-Cropper#56]
Thanks for the great library! after selecting an image from gallery and performing crop action this is what I see in my logcat:
05-01 07:53:02.301 17475-17475/tap30.taxi.passenger W/System.err: java.lang.RuntimeException: Failed to load sampled bitmap: content://com.android.providers.media.documents/document/image%3A74085
05-01 07:53:02.301 17475-17475/tap30.taxi.passenger W/System.err:     at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:212)
05-01 07:53:02.301 17475-17475/tap30.taxi.passenger W/System.err:     at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:153)
05-01 07:53:02.301 17475-17475/tap30.taxi.passenger W/System.err:     at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:25)
05-01 07:53:02.301 17475-17475/tap30.taxi.passenger W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
05-01 07:53:02.301 17475-17475/tap30.taxi.passenger W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-01 07:53:02.301 17475-17475/tap30.taxi.passenger W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
05-01 07:53:02.302 17475-17475/tap30.taxi.passenger W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-01 07:53:02.302 17475-17475/tap30.taxi.passenger W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-01 07:53:02.302 17475-17475/tap30.taxi.passenger W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-01 07:53:02.302 17475-17475/tap30.taxi.passenger W/System.err: Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{35342aa 17475:tap30.taxi.passenger/u0a227} (pid=17475, uid=10227) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
05-01 07:53:02.302 17475-17475/tap30.taxi.passenger W/System.err:     at android.os.Parcel.readException(Parcel.java:1620)
05-01 07:53:02.302 17475-17475/tap30.taxi.passenger W/System.err:     at android.os.Parcel.readException(Parcel.java:1573)
05-01 07:53:02.302 17475-17475/tap30.taxi.passenger W/System.err:     at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550)
05-01 07:53:02.302 17475-17475/tap30.taxi.passenger W/System.err:     at android.app.ActivityThread.acquireProvider(ActivityThread.java:4783)
05-01 07:53:02.303 17475-17475/tap30.taxi.passenger W/System.err:     at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
05-01 07:53:02.303 17475-17475/tap30.taxi.passenger W/System.err:     at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
05-01 07:53:02.303 17475-17475/tap30.taxi.passenger W/System.err:     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1088)
05-01 07:53:02.303 17475-17475/tap30.taxi.passenger W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
05-01 07:53:02.303 17475-17475/tap30.taxi.passenger W/System.err:     at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
05-01 07:53:02.303 17475-17475/tap30.taxi.passenger W/System.err:     at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:201)
05-01 07:53:02.303 17475-17475/tap30.taxi.passenger W/System.err: 	... 8 more

**Comment by ArthurHub** [comment]
Looks like it has something to do with KitKat documents provider, there are a few relevant question on SO: [example1](http://stackoverflow.com/questions/19834842/android-gallery-on-kitkat-returns-different-uri-for-intent-action-get-content), [example2](http://stackoverflow.com/questions/19837358/android-kitkat-securityexception-when-trying-to-read-from-mediastore), [example3](http://stackoverflow.com/questions/20248178/kitkat-error-while-trying-to-load-an-image).

Is it 100% reproducible?
Do you experience it on KitKat?
Did you use the "Documents" source for getting image for cropping?
What was the source of the image within the "Documents" UI? (Recent/Drive/Downloads/Gallery/etc.)

**Comment by LloydBlv** [comment]
@ArthurHub I'm on android 6.0.1, And yes for some images it's 100% reproducible, The source of images was Recents, and i'm using com.mlsdev.rximagepicker:library as image picker library, I'm wondering that there's no problem before cropping the image and CropImageView loads the URI properly but just after pressing crop it throws that exception!

**Comment by ArthurHub** [comment]
100% reproducible is excellent, we can make sure we found a solution then.

I think this library is missing a "persistable" permissions request ([relevant doc](http://developer.android.com/intl/es/guide/topics/providers/document-provider.html#client)):
```java
getContentResolver().takePersistableUriPermission(uri, Intent.FLAG_GRANT_READ_URI_PERMISSION);
```
can you try adding it before setting it for cropping.

**Comment by LloydBlv** [comment]
@ArthurHub Sure! let me give it a try! thanks

**Comment by LloydBlv** [comment]
@ArthurHub It didn't help added another exception:
 No persistable permission grants found for UID 10240 and Uri 0 @ content://com.android.providers.media.documents/document/image:74085

**Comment by ArthurHub** [comment]
Looks like there are a few things missing in the image pick intent creation, [this SO](http://stackoverflow.com/questions/25414352/how-to-persist-permission-in-android-api-19-kitkat) questions cover this problem exactly.

looking at *rximagepicker* it doesn't use the "proper" intent for KitKat and above API ([source](https://github.com/MLSDev/RxImagePicker/blob/master/library/src/main/java/com/mlsdev/rximagepicker/HiddenActivity.java))

It should be more like this one:
```java
Intent intent;
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT){
    intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
    intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true);
    intent.addFlags(Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);
}else{
    intent = new Intent(Intent.ACTION_GET_CONTENT);
}
intent.putExtra(Intent.EXTRA_LOCAL_ONLY, true);
intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
intent.setType("image/*");
startActivityForResult(Intent.createChooser(intent, getResources().getString(R.string.form_pick_photos)), REQUEST_PICK_PHOTO);
```

Try using your own code to pick the image from the library and see if it works

P.S. a quick look at *rximagepicker* didn't impress me, there may be better libraries or just write a simple picker like I use in this library sample ([source](https://github.com/ArthurHub/Android-Image-Cropper/blob/master/sample/src/main/java/com/theartofdev/edmodo/cropper/sample/MainActivity.java)).

**Comment by LloydBlv** [comment]
@ArthurHub Thanks,i'll try your solution to pickup images and let you know the results!

**Comment by LloydBlv** [comment]
@ArthurHub You were right! I couldn't reproduce the issue using your way of selecting files, thank you so much!
