### ISSUE TITLE
Custom request code

### ISSUE THREAD

**Issue by mac229** [ArthurHub/Android-Image-Cropper#564]
Add possibility to set custom request code (not only CROP_IMAGE_ACTIVITY_REQUEST_CODE) for multiple crop selections

**Comment by mughalasim** [comment]
I agree, is there a possibility to get the result and set it for different images .. Something like this
```
case RESULT_AVATAR:
                if (resultCode == RESULT_OK) {
                    Uri selectedImage = imageReturnedIntent.getData();
                    img_avatar.setImageURI(selectedImage);
                }

                break;
case RESULT_BANNER:
                if (resultCode == RESULT_OK) {
                    Uri selectedImage = imageReturnedIntent.getData();
                    img_banner.setImageURI(selectedImage);
                }
                break;
```

**Comment by mac229** [comment]
Ok. I've made research and I was wrong. It is possible.
 `      val intent = CropImage.activity().getIntent(context!!)
        startActivityForResult(intent, 1234)
`

**Comment by alexei-28** [comment]
adminka 
на странице входа выбери sign in with seed и введи значение, которое я выделил
