### ISSUE TITLE
Rotate not working?

### ISSUE THREAD

**Issue by radujica** [ArthurHub/Android-Image-Cropper#57]
I might be doing something wrong but even though I use `cropImageView.rotateImage(90);` it is not shown as rotated. Basically all I do in onCreate is:

`cropImageView.setImageUriAsync(picUri);`
`cropImageView.rotateImage(90);`

and then take care of saving the cropped picture. Am I missing something?

**Comment by ArthurHub** [comment]
`setImageUriAsync(uri)` is async and resets its state when the image is loaded due to exif data.
you should subscribe to complete event using `setOnSetImageUriCompleteListener(listener)` method and execute the rotate there (also you will know if load was successful).
Hope it make sense.

**Comment by radujica** [comment]
it doesn't seem to help. I inserted `rotateImage` inside the `setOnSetImageUriCompleteListener` and it's still not rotated. Do I have to refresh somehow?

**Comment by ArthurHub** [comment]
I don't know what to tell you.. I just added `view.rotateImage(90)` to `MainFragment.onSetImageUriComplete` line 185 in the sample app and it just works...

**Comment by radujica** [comment]
Quite odd. Guess it's because the custom camera activity I made does not save any exif info so far

**Comment by radujica** [comment]
That's exactly what it was. After setting `Camera.Parameters.setRotation(90)` in the custom camera, it rotated in the crop activity. Thanks for the help!
