### ISSUE TITLE
Camera image not working on Nexus 4 and Nexus 5

### ISSUE THREAD

**Issue by AkhilDad** [ArthurHub/Android-Image-Cropper#58]
The image uri comes null for nexus 4 and nexus 5 after clicking a picture.

Reason : getPickImageResultUri(Intent data) is returning null.
The intent doesn't have MediaStore.ACTION_IMAGE_CAPTURE, so the isCamera becomes false. also the intent in not null

**Comment by AkhilDad** [comment]
The solution that worked for me is

```
/**
     * Get the URI of the selected image from  {@link #getPickImageChooserIntent()}.<br/>
     * Will return the correct URI for camera  and gallery image.
     *
     * @param data the returned data of the  activity result
     */
    public Uri getPickImageResultUri(Intent  data) {
        boolean isCamera = true;
        Uri dataUri = null;
        if (data != null) {
            String action = data.getAction();
            isCamera = action != null && action.equals(MediaStore.ACTION_IMAGE_CAPTURE);
            dataUri = data.getData();
        }

        if (!isCamera) {
            if (dataUri != null) {
                return dataUri;
            }
        }
        return getCaptureImageOutputUri();
    }

```

**Comment by ArthurHub** [comment]
I don't understand the scenario.
Did you use camera or gallery?
If camera, is it the standard camera app?
How did you create the pick intent?
What Android version you used?

**Comment by ArthurHub** [comment]
I have added the check for if `data.getData()` is null as it make sense, thx.
but I do want to know what the data object looks like.

**Comment by AkhilDad** [comment]
data just has this {} empty intent, nothing in it

**Comment by ArthurHub** [comment]
damn Android, I saw so many variations for different devices and versions..
Thank you for your contribution

**Comment by AkhilDad** [comment]
@ArthurHub I guess we can make it more generalised, if rather than creating a chooser intent, first fire an intent which will get all the gallery intents, then get all camera intents.
We can than manually add request codes to that and process response accordingly. Just a thought not sure how feasible it is. But then we don't have to worry about checking Uri and making assumption that it came from camera/gallery
