### ISSUE TITLE
Pinch gesture applying scale to the image instead of the overlay

### ISSUE THREAD

**Issue by wrbl606** [ArthurHub/Android-Image-Cropper#582]
As was stated many times before (eg. [here](https://github.com/ArthurHub/Android-Image-Cropper/issues/161)) multitouch scaling of the overlay is buggy. I think there's too many variables to handle for the overlay view and the pinch gesture could be applied to the cropped image instead of overlay.

**Comment by denmarie** [comment]
Can this be merged?
