### ISSUE TITLE
onGetCroppedImageComplete returns null bitmap after image rotation. [bug]

### ISSUE THREAD

**Issue by marcin-szulc** [ArthurHub/Android-Image-Cropper#59]
Here is the scenario for the issue I get:
1. Hide crop overlay with CropImageView.setShowCropOverlay(false)
2. Rotate image with CropImageView.rotateImage
3. Show crop overlay with CropImageView.setShowCropOverlay(true)
4. Call CropImageView.getCroppedImageAsync()
5. Notice, that bitmap object in onGetCroppedImageComplete is null.

Here is some logCat:
`05-05 15:41:55.659 25255-25255/pl.gopay.photoandcrop E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.NullPointerException
                                                                           at pl.gopay.photoandcrop.CropActivity.onGetCroppedImageComplete(CropActivity.java:131)
                                                                           at com.theartofdev.edmodo.cropper.CropImageView.onGetImageCroppingAsyncComplete(CropImageView.java:811)
                                                                           at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.onPostExecute(BitmapCroppingWorkerTask.java:179)
                                                                           at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.onPostExecute(BitmapCroppingWorkerTask.java:25)`
![device-2016-05-05-154131](https://cloud.githubusercontent.com/assets/361896/15045148/587d5c86-12d9-11e6-866c-bc07fb9701b1.png)

**Comment by ArthurHub** [comment]
I can't reproduce it :(
I don't think it is related to crop overlay or rotation though.
there is no error in logcat for bitmap loading?

**Comment by marcin-szulc** [comment]
The bitmap loads fine (as you can see in picture). I am not sure, but I think it is somehow related also with crop size (and maybe bitmap size). When it is small I am able to crop the image after rotation. When it' s bigger, I get null bitmap object. I test it on few devices.

I just uploaded my activity and layout files.

[cropActivity.zip](https://github.com/ArthurHub/Android-Image-Cropper/files/251648/cropActivity.zip)

**Comment by marcin-szulc** [comment]
As far as I can tell condition if (((int) points[i]) == compareTo) in cropForRotatedImage in BitmapUtils class is never met often after image rotation.

**Comment by ArthurHub** [comment]
Interesting usage, I run the attached activity, note that if the rotation is not a straight  angle (90,180,270) the cropping window may be outside of the bitmap bounds, resulting in error:
```
java.lang.IllegalArgumentException: width must be > 0
```

Supporting this is a bit hard, especially for oval crop window so its not done yet.
Also for your scenario you may prefer to use [uCrop](https://github.com/Yalantis/uCrop)

**Comment by ArthurHub** [comment]
duplicate #31
