### ISSUE TITLE
getCroppedImage size has no effect

### ISSUE THREAD

**Issue by rafalsk** [ArthurHub/Android-Image-Cropper#6]
I;m currently testing and the size restrictions ahve no effect. user is able to clip image with his finger but it is not possible to impose any restriction with these width/height parameters of the getCroppedImage function. even if set to 500x500 I get result bitmaps much larger. also there is now way to set the ratio (hardcode it) of the clipping rectangle.

**Comment by sethgho** [comment]
>     * Gets the cropped image based on the current crop window.<br>
>     * If image loaded from URI will use sample size to fir the requested width and height.

I'm not sure I understand the purpose of the requested width and height args according to this comment.

**Comment by rafalsk** [comment]
as far as I can tell it has no effect at all I had no time so far to look into this further , will need to come back to this issue later on

**Comment by ArthurHub** [comment]
The purpose of the optional params is to provide an easy way to load downsized (sampled) image after cropping using the technique described [here](http://developer.android.com/training/displaying-bitmaps/load-bitmap.html).

I needed it for upload avatar functionality in client app:
 - Avatar size should be roughly 400x400 pixels
 - When user selects camera generated image it is huge (3264x2448 pixels on Nexus 5)
 - User can selects a cropping rectangle of the original image, lets say 2150x2150.
 - Using the width, height optional params the decoded image will be 538x538 pixels
 - In my case I uploaded that image to the server.

this can only work when the cropping image was set by URI, so the library code loaded a sampled image for the cropping UI and then can load again only the required rectangle.

Hope it helps.
