### ISSUE TITLE
SD card required?

### ISSUE THREAD

**Issue by victinformatici** [ArthurHub/Android-Image-Cropper#60]
It seems the cropper doesn't work on devices (or emulators) without a SD card?
If I run the sample app in my device emulator I get an "SD is full" error, running it directly on a device without a SD card seems to destroy the app.

**Comment by ArthurHub** [comment]
The short answer is NO, SD is not required in any way.
I have tested it in multiple emulators, apart from Android Studio 2.* emulators are horrible, never seen "SD is full" message.
The only case the library is writing to storage is when when cropped image is saved using CropImageActivity or direct method call, either way you can control where it is saved to.
I'm sorry I don't know what "destroy the app" mean.
