### ISSUE TITLE
Black screen after selecting a pdf file

### ISSUE THREAD

**Issue by InesRo** [ArthurHub/Android-Image-Cropper#607]
I am trying to show a chooser just for files to crop documents. The problem is after selecting, for example, a PDF file. I don´t get any error, but the document is not shown and I get a black screen. This is the screenshot:

![screenshot_20180918-095714](https://user-images.githubusercontent.com/43367911/45672905-9e60d700-bb29-11e8-855f-a54e2d9bd247.png)

This is my logcat:

      [CropImageActivity]: setView = DecorView@26884cb[CropImageActivity] touchMode=true
      [CropImageActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
    MSG_WINDOW_FOCUS_CHANGED 1

And this is my code:

       public void onGalleryClicked() {
                Intent documentsIntent = new Intent(Intent.ACTION_GET_CONTENT);
                documentsIntent.setType(file/*);
                startActivityForResult(Intent.createChooser(documentsIntent, 
                getString(R.string.dialog_chooser_select_from_gallery)), Constants.DOC_REQUEST);
        }

        public void showImageCropping(final String uri) {
                 DisplayMetrics dm = Resources.getSystem().getDisplayMetrics();
                 int minCroppedSize = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 21, dm);
                  float borderSize = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 7, dm);
                  if (getContext() != null) {
                        CropImage.activity(Uri.parse(uri))
                         .setGuidelines(CropImageView.Guidelines.OFF)
                         .setBorderCornerColor(ContextCompat.getColor(getContext(), R.color.colorPrimary))
                         .setMinCropWindowSize(minCroppedSize, minCroppedSize)
                         .setBorderCornerLength(borderSize)
                         .start(getContext(), this);
                  }
          }

         public void onActivityResult(int requestCode, int resultCode, Intent data) {
         switch (requestCode) {
           case Constants.DOC_REQUEST:
                 if (resultCode == RESULT_OK) {
                     if (data != null && data.getData() != null) {
                         showImageCropping(data.getData().toString());
                     }
                 }
                 break;
        }

Any idea? Thanks in advance!

**Comment by sivasankar0457** [comment]
Pdf format is not allowed format instead of image how you can crop the pdf file so it cant show any unauthorized file formats it allows only jpg and png formats

**Comment by InesRo** [comment]
Thanks!
