### ISSUE TITLE
CropImageActivity returns activity without buttons

### ISSUE THREAD

**Issue by jangerhard** [ArthurHub/Android-Image-Cropper#61]
Calling CropImageActivity from within a fragment results in a screen where the user is unable to get further. 

This is using this code: 

```
CropImage.activity(uri)
                    .setGuidelines(CropImageView.Guidelines.ON)
                    .start(getActivity());
```

Which results in this screen, where the user is unable to get any further. 
![2016-05-06 19 21 28](https://cloud.githubusercontent.com/assets/6482205/15083938/3fecf51c-139e-11e6-9968-78fe709d11b8.png)

**Comment by ArthurHub** [comment]
I think its a theme issue, if your main theme has `NoActionBar` then you need to specify on the activity to use the action bar
```xml
<activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
    android:theme="@style/Base.Theme.AppCompat" />
```

**Comment by mskmx** [comment]
@ArthurHub Thanks, works now fine.
Regards
