### ISSUE TITLE
Float degree rotation (Help wanted)

### ISSUE THREAD

**Issue by Inkon** [ArthurHub/Android-Image-Cropper#62]
In my project I wanted to use this cropper, and I think it's cool, but I really need to rotate image to float degree, and right now can't imagine how to do it right. Any suggestions? Thanks.

**Comment by ArthurHub** [comment]
You mean that rotation by 5 degrees is not fine enough, you want by 5.6 degrees?
Not sure what kind of UX will support it..
Also, rotation by non-straight angles support is currently problematic, will improve it in a week or two.

**Comment by Inkon** [comment]
Well, OK thanks for the answer.
