### ISSUE TITLE
referenced from method com.theartofdev.edmodo.cropper.CropImage.isUriRequiresPermissions

### ISSUE THREAD

**Issue by lesiaki** [ArthurHub/Android-Image-Cropper#63]
am getting this error when am try to crop the image, please can someone help

**Comment by ArthurHub** [comment]
what is the error? is there a stack trace?

**Comment by lesiaki** [comment]
these are stack trace am getting

.example.georgejohn.baboapp2016 E/dalvikvm: Could not find class 'android.system.ErrnoException', referenced from method com.example.georgejohn.baboapp2016.ProfileActivity.isUriRequiresPermissions
05-08 10:15:38.487 15364-15364/com.example.georgejohn.baboapp2016 E/dalvikvm: Could not find class 'android.system.ErrnoException', referenced from method com.theartofdev.edmodo.cropper.CropImage.isUriRequiresPermissions

**Comment by lesiaki** [comment]
when it crop it return the empty data

**Comment by ArthurHub** [comment]
Interesting.. what device and API version are you seeing it on?

What do you mean empty data? is there an error?

**Comment by lesiaki** [comment]
Sumsung s4min android v4.2.2

**Comment by ArthurHub** [comment]
Can you put a break point there and tell me what is the type of the exception and what the error message, thx.

**Comment by lesiaki** [comment]
Great, i fix the problem it was my mistaken, i was expecting to the set the image to the imageview using setImageURI, i convert it to bitmap and set to setImageBitmap. Thanks!

**Comment by ArthurHub** [comment]
Wait, the call not found is a legitimate error, I would like to know what error you get in  `isUriRequiresPermissions` so I can fix it.
Also `setImageURI` should also work, no need to manually decode the image, what was the problem?

I know you made it work and just want to go on with it, but please help me to make it better.

**Comment by lesiaki** [comment]
E/dalvikvm: Could not find class 'android.system.ErrnoException', referenced from method com.theartofdev.edmodo.cropper.CropImage.isUriRequiresPermissions

**Comment by ArthurHub** [comment]
k, thx, will fix

**Comment by lesiaki** [comment]
Great!

**Comment by jimsmithm3** [comment]
I ran into this today.  Pass in a bad uri string(like  /storage/emulated/0/permanent/crop_orig.jpeg)  and the error will be thrown.

**Comment by ArthurHub** [comment]
Thanks, still doesn't happens to me =\
Also it's strange that this code even reachable for lesiaki because there is a check that the SDK is M or higher.
Either way I have updated the library yesterday (2.1.2) and removed the exception type check, this may result in requesting permissions when the uri is not valid but I feel it's not a big deal, many will require the permissions upfront, I believe.

Please check it with the latest version and let me know if it worked.

thx.

**Comment by jimsmithm3** [comment]
It still is complaining even in 2.1.2.  I was curious what was going on. 

I downloaded your library and hacked on it a bit as such (log output is below that). 

TL;DNR.  Java is checking internal function availability before it executes the called function.

` public static boolean isReadExternalStoragePermissionsRequired(Context context, Uri uri) {
        Log.d("XXX start of function", Build.VERSION.SDK_INT + " " + Build.VERSION_CODES.M);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
        {
            Log.d("XXX", "in if");
            return context.checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED &&
                    isUriRequiresPermissions(context, uri);
        }
        else
        {
            Log.d("XXX", "in else");
            return false;
        }
    }`
05-09 18:59:59.826 19276-19276/org.permanent.android E/LibraryActivity: calling CropImage.isReadExternalStoragePermissionsRequired
05-09 18:59:59.826 19276-19276/org.permanent.android I/dalvikvm: Could not find method android.content.Context.checkSelfPermission, referenced from method com.theartofdev.edmodo.cropper.CropImage.isReadExternalStoragePermissionsRequired
05-09 18:59:59.826 19276-19276/org.permanent.android W/dalvikvm: VFY: unable to resolve virtual method 545: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
05-09 18:59:59.830 19276-19276/org.permanent.android D/dalvikvm: VFY: replacing opcode 0x6e at 0x004d
05-09 18:59:59.834 19276-19276/org.permanent.android D/XXX start of function: 19 23
05-09 18:59:59.834 19276-19276/org.permanent.android D/XXX: in else

**Comment by ArthurHub** [comment]
Oh... I think I misunderstood the issue.
I though an exception was thrown that prevented the code from running, I understand now that it's not the case but logcat has a bunch of "could not find method" error messages, correct?
If that's the case, it's a [normal Android behavior](https://code.google.com/p/android/issues/detail?id=198567).

**Comment by jimsmithm3** [comment]
That is a correct assessment.  I only noticed the messages because of another bug about a bad URI I was passing in (later fixed) so was paying close attention to what was happening in the logs. 

I wasn't aware that those are 'normal' errors.  Thanks for pointing that out, learn something new everyday.

Really liking your library.

**Comment by Mandy1125** [comment]
When I select Picture from gallery it's working find. but when i capture Picture using camera intent - error!
I/dalvikvm: Could not find method android.content.Context.checkSelfPermission, referenced from method com.theartofdev.edmodo.cropper.CropImage.isExplicitCameraPermissionRequired

**Comment by immyemperor** [comment]
i am getting null pointer exception  on the same...the resultUri is null plz tell me hoe do i fix it

**Comment by immyemperor** [comment]
hello you there?
