### ISSUE TITLE
Cropper won't open after ImagePick S6 edge

### ISSUE THREAD

**Issue by janskod** [ArthurHub/Android-Image-Cropper#65]
Hello, i tested the simple example on a S6 edge and sometime it happens, that after choosing an image by using the image picker, only the image will be visible in fullscreen mode with a homeasup arrow on the left. But the menu itself is not visible with the rotate and crop option.

Anyone got an idea, why this happens non predictable?

**Comment by ArthurHub** [comment]
That is very strange, just to be clear, when you run the same app on the same device, sometimes the menu items appears and sometimes not?

is there any error in logcat? in `onCreateOptionsMenu` method?

can you reproduce it in `quick-start` sample app?

**Comment by janskod** [comment]
It happens only in minority case :(. I will send it, when i capture it. But when i remember it properly it also happens if using another project, which bases on edmodo. Maybe its a bug in edmodo directly. An exception is not thrown.

**Comment by ArthurHub** [comment]
Does anyone else saw this issue? 
and/or has any idea what it could be please leave a comment.

**Comment by gustavomc** [comment]
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 15132368)

**Comment by ArthurHub** [comment]
How is it relevant to this issue?
