### ISSUE TITLE
Loading a bitmap object

### ISSUE THREAD

**Issue by Minitour** [ArthurHub/Android-Image-Cropper#66]
Hi, I was wondering If I can load a bitmap object (basically load an image without a URI), since in the features it is mentioned that I can load Bitmaps, Resources and URI, however I only saw the URI option.

**Comment by ArthurHub** [comment]
It is available if you use CropImageView, see:
https://github.com/ArthurHub/Android-Image-Cropper/wiki/Using-CropImageView-in-own-Activity.

Passing bitmaps between activities is problematic, so I couldn't provide
this option for the built in activity.

**Comment by Minitour** [comment]
Alright, Thanks for the quick reply.
