### ISSUE TITLE
Failed to resolve: com.theartofdev.edmodo:android-image-cropper:2.5.+

### ISSUE THREAD

**Issue by prabodhana** [ArthurHub/Android-Image-Cropper#662]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.theartofdev.edmodo:android-image-cropper:2.5.+.

getting this error any idea?

**Comment by taher-medsolace** [comment]
Could not resolve com.theartofdev.edmodo:android-image-cropper:2.8.+.

**Comment by prabodhana** [comment]
now work fine

**Comment by taher-medsolace** [comment]
It still not working

**Comment by usergoodvery** [comment]
I also get ERROR: Unable to resolve dependency for ':@playDebug/compileClasspath': Could not download android-image-cropper.aar (com.theartofdev.edmodo:android-image-cropper:2.7.0)

**Comment by prabodhana** [comment]
if I use com.theartofdev.edmodo:android-image-cropper:2.8.+ it works but
 I use com.theartofdev.edmodo:android-image-cropper:2.5.+ it gets error "ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:26.+."

**Comment by prabodhana** [comment]
jcenter is having issues at the moment, please check http://status.bintray.com/

**Comment by talon-so** [comment]
using 2.8+ gives me 
app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.

**Comment by prabodhana** [comment]
guys jcenter issues are now solved my errors are gone check  yours <3 (y)
