### ISSUE TITLE
CropImage.activity(uri) - how to use imageUrl - UCrop has it  

### ISSUE THREAD

**Issue by emailsubjekt** [ArthurHub/Android-Image-Cropper#686]
How can I set url to change to change an image from an url. Obviously the only way is download the image and turn it into a bmp or save it to file and get the uri, but is there an included way?

**Comment by emailsubjekt** [comment]
Come on man! Answer!

**Comment by emailsubjekt** [comment]
Your library is pissing me off!

**Comment by emailsubjekt** [comment]
Nevermind, I solved it.

**Comment by benedictcontawe** [comment]
Can you re open this
