### ISSUE TITLE
Toolbar in CropperActivity not showing

### ISSUE THREAD

**Issue by younas-bangash** [ArthurHub/Android-Image-Cropper#70]
Toolbar is not showing in CropperImage Activity when i try to run the quick-start

**Comment by ArthurHub** [comment]
If your main theme has `NoActionBar` then you need to specify on the activity to use theme with action bar
```xml
<activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
    android:theme="@style/Base.Theme.AppCompat" />
```

**Comment by younas-bangash** [comment]
Thanks ArthurHub it's displaying now and can we add one more menu option like cancel ?

**Comment by ArthurHub** [comment]
you have two cancel options there, the back/up button on the top-left corner and android back button

**Comment by younas-bangash** [comment]
Thanks
