### ISSUE TITLE
How to go back to the gallery's image list?

### ISSUE THREAD

**Issue by lx5475** [ArthurHub/Android-Image-Cropper#707]
Hi, i want to see the image list again when i cancel crop.

```java
public void takeGallery(Activity activity) {
        mIsCamera = false;
        activity.startActivityForResult(
                getPickImageChooserIntent(activity), REQUEST_GALLARY);
    }
```
**`Now`**
Activity A -> Gallery -> Pick an image from specific folder -> Try to crop -> press back button on crop activity -> Activity A

**`What I want`**
Activity A -> Gallery -> Pick an image from specific folder -> Try to crop -> press back button on crop activity -> specific folder

**Comment by ROOMEODESSRICON** [comment]
I.nfo
