### ISSUE TITLE
Failed to resolve: com.theartofdev.edmodo:android-image-cropper:2.1.+

### ISSUE THREAD

**Issue by alexliubj** [ArthurHub/Android-Image-Cropper#72]
Any idea

**Comment by ArthurHub** [comment]
Missing *jcenter* repository?
```groovy
buildscript {
    repositories {
        jcenter()
    }
}
```

**Comment by alexliubj** [comment]
Still the same error. after I added Jcenter.
`
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }

    repositories {
        jcenter()
    }
}

`

**Comment by ArthurHub** [comment]
compare what you have in the app with the sample gradle files, you are missing something

**Comment by alexliubj** [comment]
Any other ref than this file?

https://github.com/ArthurHub/Android-Image-Cropper/blob/master/sample/build.gradle

**Comment by alexliubj** [comment]
That's what I have in gradle file. please advise. :)
`
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }

    repositories {
        jcenter()
    }
}

apply plugin: 'com.android.application'
apply plugin: 'android'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 125
        versionName "2.12.4"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
   }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    signingConfigs{
        debug{
            storeFile file('../debug.keystore')
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
}

dependencies {
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.google.android.gms:play-services:7.3.0'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:support-v4:23.0.1'
    compile 'com.android.support:cardview-v7:23.0.+'
    compile 'com.android.support:recyclerview-v7:23.0.1'
    compile 'com.getbase:floatingactionbutton:1.9.0'
    compile 'com.zendesk:sdk:1.4.1.1'
    compile 'it.sephiroth.android.library.easing:android-easing:1.0.3'
    compile 'com.squareup:otto:1.3.8'
    compile 'com.facebook.network.connectionclass:connectionclass:1.0.1'
    compile 'com.github.gabrielemariotti.cards:cardslib-core:2.0.1'
    compile 'commons-io:commons-io:2.4'
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.facebook.stetho:stetho:1.1.1'
    androidTestCompile 'com.android.support.test:runner:0.4'
    androidTestCompile 'com.android.support.test:rules:0.4'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.1'
    compile files('libs/httpclientandroidlib-1.2.1.jar')
    compile 'com.viewpagerindicator:library:2.4.1@aar'
    compile 'com.theartofdev.edmodo:android-image-cropper:2.1.+'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
}
`

**Comment by alexliubj** [comment]
`buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }

    repositories {
        jcenter()
    }
}

apply plugin: 'com.android.application'
apply plugin: 'android'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 125
        versionName "2.12.4"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
   }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    signingConfigs{
        debug{
            storeFile file('../debug.keystore')
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
}

dependencies {
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.google.android.gms:play-services:7.3.0'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:support-v4:23.0.1'
    compile 'com.android.support:cardview-v7:23.0.+'
    compile 'com.android.support:recyclerview-v7:23.0.1'
    compile 'com.getbase:floatingactionbutton:1.9.0'
    compile 'com.zendesk:sdk:1.4.1.1'
    compile 'it.sephiroth.android.library.easing:android-easing:1.0.3'
    compile 'com.squareup:otto:1.3.8'
    compile 'com.facebook.network.connectionclass:connectionclass:1.0.1'
    compile 'com.github.gabrielemariotti.cards:cardslib-core:2.0.1'
    compile 'commons-io:commons-io:2.4'
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.facebook.stetho:stetho:1.1.1'
    androidTestCompile 'com.android.support.test:runner:0.4'
    androidTestCompile 'com.android.support.test:rules:0.4'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.1'
    compile files('libs/httpclientandroidlib-1.2.1.jar')
    compile 'com.viewpagerindicator:library:2.4.1@aar'
    compile 'com.theartofdev.edmodo:android-image-cropper:2.1.+'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
}
`

**Comment by alexliubj** [comment]
when I clean the project , it has `Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find any matches for com.theartofdev.edmodo:android-image-cropper:2.1.+ as no versions of com.theartofdev.edmodo:android-image-cropper are available.
     Searched in the following locations:
         file:/C:/Users/alex.liu/Downloads/android-studio-ide-143.2790544-windows/android-studio/gradle/m2repository/com/theartofdev/edmodo/android-image-cropper/maven-metadata.xml
         file:/C:/Users/alex.liu/Downloads/android-studio-ide-143.2790544-windows/android-studio/gradle/m2repository/com/theartofdev/edmodo/android-image-cropper/
         http://dl.bintray.com/populov/maven/com/theartofdev/edmodo/android-image-cropper/maven-metadata.xml
         http://dl.bintray.com/populov/maven/com/theartofdev/edmodo/android-image-cropper/
         https://zendesk.artifactoryonline.com/zendesk/repo/com/theartofdev/edmodo/android-image-cropper/maven-metadata.xml
         https://zendesk.artifactoryonline.com/zendesk/repo/com/theartofdev/edmodo/android-image-cropper/
         https://repo1.maven.org/maven2/com/theartofdev/edmodo/android-image-cropper/maven-metadata.xml
         https://repo1.maven.org/maven2/com/theartofdev/edmodo/android-image-cropper/
         https://maven.fabric.io/public/com/theartofdev/edmodo/android-image-cropper/maven-metadata.xml
         https://maven.fabric.io/public/com/theartofdev/edmodo/android-image-cropper/
         file:/C:/Users/alex.liu/AppData/Local/Android/sdk1/extras/android/m2repository/com/theartofdev/edmodo/android-image-cropper/maven-metadata.xml
         file:/C:/Users/alex.liu/AppData/Local/Android/sdk1/extras/android/m2repository/com/theartofdev/edmodo/android-image-cropper/
         file:/C:/Users/alex.liu/AppData/Local/Android/sdk1/extras/google/m2repository/com/theartofdev/edmodo/android-image-cropper/maven-metadata.xml
         file:/C:/Users/alex.liu/AppData/Local/Android/sdk1/extras/google/m2repository/com/theartofdev/edmodo/android-image-cropper/
     Required by:
         FSAndroid:app:unspecified`

**Comment by ArthurHub** [comment]
add this:
```groovy
allprojects {
    repositories {
        jcenter()
    }
}
```

in the sample it exist in the root gradle file: https://github.com/ArthurHub/Android-Image-Cropper/blob/master/build.gradle

**Comment by alexliubj** [comment]
Thanks, work now.

**Comment by piyushmishhy** [comment]
Hi Arthur,
I have same issue. First, it was working fine, now it is showing Failed to resolve: com.theartofdev.edmodo:android-image-cropper:2.2.+. I have checked root gradle it is exactly what was given above

**Comment by ArthurHub** [comment]
Hey, I don't know what the issue can be but it's not on the library side, double-checked it.
Try googling for "gradle failed to resolve" error.

**Comment by piyushmishhy** [comment]
I have changed Gradle setting to "offline work" and it works. Would it effect app anymore. Thanks for suggestion. Your Image library is awesome.

**Comment by AshwiniDabir** [comment]
I am still not able to solve this error after implementing all above suggestions. Is there a guide/document specifying how to integrate Android-Image-Cropper in my app ? pls help

**Comment by jhegedus42** [comment]
I have it too.

**Comment by santoshbachkar19** [comment]
i have occur one issue in android nougat device . I can't crop Image . i have use  'compile 'com.theartofdev.edmodo:android-image-cropper:2.3.+'  after i select image and try to crop but click on crop it's showing  "Lab-Intent-FileProvider" open app again.
![screenshot1](https://user-images.githubusercontent.com/17003677/26961867-b109696a-4cff-11e7-9f40-68cdb3850e2e.jpg)

**Comment by hassaanjamil** [comment]
Add this to your gradle:
compile 'com.theartofdev.edmodo:android-image-cropper:2.4.7'

It worked fine for me, before I was facing the same issue.

**Comment by mhdSVU** [comment]
compile 'com.theartofdev.edmodo:android-image-cropper:2.4.7'
also worked nice for me!
Thanks hassaanjamil!

**Comment by sagorbrur** [comment]
Hello,
I had this problem. when I build my project without internet it show that error. But building with internet connection it's build perfectly as before.
agree with **piyushmishhy** and thanks **ArthurHub**  for this amazing tool.

**Comment by akshaymalik75** [comment]
unable to resolve : compile com.theartofdev.edmodo:android-image-cropper:2.3.+
When i am trying to add this dependency it shows me this error please help me as i have applied all the above methode but still its giving me the same error
![capturesad](https://user-images.githubusercontent.com/25265773/39661745-4bc5c76e-5074-11e8-9617-e23034675f7b.PNG)

**Comment by tazzhuxiao** [comment]
> unable to resolve : compile com.theartofdev.edmodo:android-image-cropper:2.7.+
> When i am trying to add this dependency it shows me this error please help me as i have applied all the above methode but still its giving me the same error
> ![capturesad](https://user-images.githubusercontent.com/25265773/39661745-4bc5c76e-5074-11e8-9617-e23034675f7b.PNG)

i meet the same problem ,have you slove it?

**Comment by MWaseemMatto** [comment]
i have also same problem android ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.theartofdev.edmodo:android-image-cropper:2.3.1.

**Comment by bermufine** [comment]
> add this:
> 
> ```groovy
> allprojects {
>     repositories {
>         jcenter()
>     }
> }
> ```
> 
> in the sample it exist in the root gradle file: https://github.com/ArthurHub/Android-Image-Cropper/blob/master/build.gradle

Arthur, i think you have to work hard again to update this featuring because for now everyone getting error even me then Android Studio with gradle they updating libraries every week so we still facing the same problem can you keep your mind in this too update it?
will be much appreciated.

**Comment by bermufine** [comment]
> ```groovy
> jcenter()
> ```

jcenter() is already obsoleted or revoqued so you have update with the new settings

**Comment by MakoFoxY** [comment]
How can I fix the error in the builde.gradle;
 Failed to resolve: com.theartofdev.edmodo:android-image-cropper:2.8.+
<a href="open.dependency.in.project.structure">[Show in Project Structure dialog](https://github.com/ArthurHub/Android-Image-Cropper/issues/open.dependency.in.project.structure)</a>
Affected Modules: <a href="openFile:D:/AgroMarketKST/[app](openfile:D:/AgroMarketKST/app/build.gradle)/build.gradle">app</a>

**Comment by MakoFoxY** [comment]
![изображение](https://user-images.githubusercontent.com/88974060/159099001-de1946dd-4b18-4d98-911c-99726042775a.png)

**Comment by bermufine** [comment]
Your mail doesn't help

I did put dependencies already
Implement 'com. ..........2.1+'

But my app crashed that why I need a way to resolve it

**Comment by DeoAdzar** [comment]
> How can I fix the error in the builde.gradle; Failed to resolve: com.theartofdev.edmodo:android-image-cropper:2.8.+ [Show in Project Structure dialog](https://github.com/ArthurHub/Android-Image-Cropper/issues/open.dependency.in.project.structure) Affected Modules: app

change version don't use +
if you use android studio bumblebee, go to setting.gradle, and add jcenter() :

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
    }
}
```

**Comment by bermufine** [comment]
Ok, I will check.

**Comment by Mujahid133** [comment]
I had the same issue not only with this app but also with the other libraries and I solved it by importing it as a new module and the in the module settings I add its dependency in the app

**Comment by vedpathakp127** [comment]
> > How can I fix the error in the builde.gradle; Failed to resolve: com.theartofdev.edmodo:android-image-cropper:2.8.+ [Show in Project Structure dialog](https://github.com/ArthurHub/Android-Image-Cropper/issues/open.dependency.in.project.structure) Affected Modules: app
> 
> change version don't use + if you use android studio bumblebee, go to setting.gradle, and add jcenter() :
> 
> ```
> dependencyResolutionManagement {
>     repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
>     repositories {
>         google()
>         mavenCentral()
>         jcenter() // Warning: this repository is going to shut down soon
>     }
> }
> ```

this is real culprit reason, it solved for me thank you !
