### ISSUE TITLE
Can't decode image with Uri?

### ISSUE THREAD

**Issue by alexliubj** [ArthurHub/Android-Image-Cropper#74]
After I cropped it , i got an image Uri like this, `file:///data/user/0/ca.flynn.serviceapp/cache/cropped-317732689.jpg`

and trying to get bitmap by this way (since it has to be the same as how I handle the camera stuff)

				`Bitmap pic =  BitmapFactory.decodeFile(imageObj.fileUriString);`

and get null.

My picture captured from camera works with this uri: 
`/storage/emulated/0/FlynnService/aaa-1463507622/aaa-1463507622_1463601192999.jpg`

Do I have to remove 'file://' in front of my Uri?

**Comment by ArthurHub** [comment]
Android URI is not regular file path, please use google or stackoverflow to learn about Android development.
