### ISSUE TITLE
Usage In Fragment

### ISSUE THREAD

**Issue by poovarasanvasudevan** [ArthurHub/Android-Image-Cropper#76]
I can`t able to use this in fragment

**Comment by RahulKumarSaini** [comment]
+1 I am facing same problem. onActivityResult() new receiving a callback after cropping a image in frgment

**Comment by ArthurHub** [comment]
checking, will help if you explain the problem a bit more and/or provide a sample code.

**Comment by ArthurHub** [comment]
from my tests it looks like everything works.

Just to be sure you are not missing something. you should override the `onActivityResult` of the fragment to receive the result and if you did override `onActivityResult` the result there will be received with different request code, so you must call `super.onActivityResult(requestCode, resultCode, data);` to pass the result to the fragment.

If this doesn't answer you issue please provide more data than "not working".

**Comment by RahulKumarSaini** [comment]
private void selectImageFromGallary()
    {
		/* Create intent to Open Image 
		Intent galleryIntent = new Intent(Intent.ACTION_PICK,
				android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
				
		startActivityForResult(galleryIntent, RESULT_SELECT_IMG);
		
        Intent intent = new Intent();
        intent.setType("image/*");
        intent.setAction(Intent.ACTION_GET_CONTENT);
        startActivityForResult(Intent.createChooser(intent,"Select Picture"), RESULT_SELECT_IMG);    
        
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
       super.onActivityResult(requestCode, resultCode, data);

        Log.d("APP_DEBUG", String.valueOf(requestCode));
		
        try {
            // When an Image is picked
            if (requestCode == RESULT_SELECT_IMG && resultCode == Activity.RESULT_OK
                    && null != data) {
                Uri selectedImage = data.getData();

                CropImage.activity(selectedImage)
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setMinCropResultSize(800, 800)
                        .setMaxCropResultSize(1000, 1000)
                        .start(getActivity());
            }
			// when image is cropped 
            else if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
                CropImage.ActivityResult result = CropImage.getActivityResult(data);
                Log.d("APP_DEBUG",result.toString());
                if (resultCode == Activity.RESULT_OK) {
                    Uri resultUri = result.getUri();
                    Log.d("APP_DEBUG",resultUri.toString());
                    Bitmap bitmap =  MediaStore.Images.Media.getBitmap(getActivity().getContentResolver(), resultUri);
                    profilePic.setImageBitmap(bitmap);

                } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                    Exception error = result.getError();
                }
            }
            else {
                Toast.makeText(getActivity(), "You haven't picked Image",
                        Toast.LENGTH_LONG).show();
            }
        } catch (Exception e) {
            Toast.makeText(getActivity(), "Something went wrong"+e.getMessage(), Toast.LENGTH_LONG)
                    .show();
        }

    }

Here is the code that I am try to run I pick a image on a button click then on successful image pick I called CropImage Activity It works fine and Crop activity allow me to crop the image, But it never return a callback in onActivityResult. Whwn i try to debug i found onActivityResult method only executed once when user pick a image not after image image has been cropped.
 thank you.

**Comment by ArthurHub** [comment]
you started the activity using `.start(getActivity());` this way the result will only return in the activity, not in the fragment.
If you use appcompat fragment (recomended) you can call `.start(getContext(), this)` otherwise you need to call `.getIntent(getContext())` and then use this intent to start the activity from your fragment.

**Comment by RahulKumarSaini** [comment]
Yes, you are right it works now 
Thank you for your help and support.

**Comment by SkyNite** [comment]
@ArthurHub 

I'm calling this snippet in

```
 CropImage.activity(fileUri)
                        .setCropShape(CropImageView.CropShape.RECTANGLE)
                        .setGuidelines(CropImageView.Guidelines.OFF)
                        .setFixAspectRatio(true)
                        .setAutoZoomEnabled(false)
                        .start(getActivity());
```
inside my DialogFragment class, its not working when i using the same in Fragment its working fine. i tried both, .start(getActivity()); and .start(getActivity(), DummyDialogFrg.class);

Please advice on this. thanks.

**Comment by ArthurHub** [comment]
but.. but.. but.. my previous, comment in this thread no less, explains why it doesn't work... and I added it to the "[Using built-in Crop Image Activity](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Using-built-in-CropImageActivity)" wiki page and the "[FAQ](https://github.com/ArthurHub/Android-Image-Cropper/wiki/FAQ)" wiki page...

What am I doing wrong? 
How can I improve the documentation? 
Where did you look and didn't find the answer?

**Comment by arpansharma7474** [comment]
Hi I have tried using all of the ways you suggested.But the activity doesn't start. I am using it inside fragment.

**Comment by ArthurHub** [comment]
check logcat for errors
and post your code

**Comment by arpansharma7474** [comment]
I tried starting the activity from fragment and but it always instantly came back to on Activity result with result code 204. So i implemented it in a separate activity with CropImageView but the cropping is too slow in my test phone.I mean adjusting the crop area lags.

 ```
<com.theartofdev.edmodo.cropper.CropImageView
        xmlns:custom="http://schemas.android.com/apk/res-auto"
        android:id="@+id/cropImageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        custom:cropScaleType="centerInside"
        custom:cropFixAspectRatio="true" />
```

**Comment by kashyapasrc** [comment]
Hi  ArthurHub, I am using this  Theme in my project
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:colorPrimary">@color/colorPrimary</item>
    <item name="android:colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="android:colorAccent">@color/colorAccent</item>
        <item name="android:typeface">serif</item>
    </style>

Using your crop library in a fragment 

  @Override
    @SuppressLint("NewApi")
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        try {
            // When an Image is picked
            if (requestCode == 2 && resultCode == Activity.RESULT_OK
                    && null != data) {
                Uri selectedImage = data.getData();

                CropImage.activity(selectedImage)
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setMinCropResultSize(800, 800)
                        .setMaxCropResultSize(1000, 1000)
                        .start(getContext(), this);
            }
            // when image is cropped
            else if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
                CropImage.ActivityResult result = CropImage.getActivityResult(data);
                Log.d("APP_DEBUG", result.toString());
                if (resultCode == Activity.RESULT_OK) {
                    Uri resultUri = result.getUri();
                    Log.d("APP_DEBUG", resultUri.toString());
                    Bitmap bitmap = MediaStore.Images.Media.getBitmap(getActivity().getContentResolver(), resultUri);
                    photo.setImageBitmap(bitmap);

                } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                    Exception error = result.getError();
                }
            } else {
                Toast.makeText(getActivity(), "You haven't picked Image",
                        Toast.LENGTH_LONG).show();
            }
        } catch (Exception e) {
            Toast.makeText(getActivity(), "Something went wrong" + e.getMessage(), Toast.LENGTH_LONG)
                    .show();
        }

    }

   @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String permissions[], @NonNull int[] grantResults) {
        if (mCropImageUri != null && grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
            // required permissions granted, start crop image activity
            startCropImageActivity(mCropImageUri);
        } else {
            Toast.makeText(getActivity(), "Cancelling, required permissions are not granted", Toast.LENGTH_LONG).show();
        }
    }

    private void startCropImageActivity(Uri imageUri) {
        try {


            CropImage.activity(imageUri)
                    .setGuidelines(CropImageView.Guidelines.ON)
                    .setMultiTouchEnabled(true)
                    .start(getContext(), this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

On The screen of croping, I am not getting the ActionBar, I know that i am using NoActionBar theme, In This case how can i use this code, please solve the above problem.

**Comment by NajafAli** [comment]
i solved this issue @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {

        if (resultCode != RESULT_OK) {
            return;
        }

        switch (requestCode) {
            case ACTION_REQUEST_EDITIMAGE://
                handleEditorImage(data);
                break;

            case REQUEST_CODE_GALLERY:

                if (mCurrentPhotoPath == null) {

                    Uri selectedImageUri = data.getData();
                    CropImage.activity(selectedImageUri)
                            .setGuidelines(CropImageView.Guidelines.ON)
                            .start(getContext(), this);
                }

                break;

            case REQUEST_CODE_CAPTURE:

                try {
                    Uri imageUri = Uri.parse(mCurrentPhotoPath);
                    if (imageUri == null) {

                    } else {
                        CropImage.activity(imageUri)
                                .setGuidelines(CropImageView.Guidelines.ON)
                                .start(getContext(), this);
                        MediaScannerConnection.scanFile(getActivity(),
                                new String[]{imageUri.getPath()}, null,
                                new MediaScannerConnection.OnScanCompletedListener() {
                                    public void onScanCompleted(String path, Uri uri) {
                                    }
                                });
                        mCurrentPhotoPath = null;
                    }

                } catch (Exception e) {

                }

                break;

            case CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE:
                CropImage.ActivityResult result = CropImage.getActivityResult(data);
                Uri resultUri = result.getUri();
                if (resultUri != null) {
                    path = resultUri.getPath();
                    if (TextUtils.isEmpty(path)) {
                        return;
                    }
                    Intent it = new Intent(getActivity(), EditImageActivity.class);
                    it.putExtra(EditImageActivity.FILE_PATH, path);
                    File outputFile = FileUtils.getEmptyFile("tietu"
                            + System.currentTimeMillis() + ".jpg");
                    it.putExtra(EditImageActivity.EXTRA_OUTPUT,
                            outputFile.getAbsolutePath());
                    startActivityForResult(it,
                            ACTION_REQUEST_EDITIMAGE);

                }

                break;

            case CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE:
                Toast.makeText(getActivity(), "error in cropping", Toast.LENGTH_SHORT).show();
                break;
        }
        super.onActivityResult(requestCode, resultCode, data);
    }
please dont miss this article its quite separate thing when you work inactivity and fragment for cropping a liitle bit changing is required for intent ,

https://github.com/ArthurHub/Android-Image-Cropper/wiki/Using-built-in-CropImageActivity

**Comment by Rudra-n-khatri** [comment]
i am unable to use cropimage inside fragment.

                   mImageButtonn.setOnClickListener(new View.OnClickListener() {
                 @Override
                public void onClick(View view) {


                Intent galleryIntent = new Intent();
                galleryIntent.setType("image/*");
                galleryIntent.setAction(Intent.ACTION_GET_CONTENT);

                startActivityForResult(Intent.createChooser(galleryIntent, "SELECT IMAGE"), GALLERY_PICK);
              
            }
         });



              @Override
              public void onActivityResult(int requestCode, int resultCode, Intent data) {
              super.onActivityResult(requestCode, resultCode, data);

           if(requestCode == GALLERY_PICK && resultCode == RESULT_OK){

            Uri imageUri = data.getData();

            CropImage.activity(imageUri)
                    .setAspectRatio(1, 1)
                    .setMinCropWindowSize(500, 500)
                    .start(getActivity());

            Toast.makeText(getActivity(), (CharSequence) imageUri, Toast.LENGTH_LONG).show();

              }


               if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {

            CropImage.ActivityResult result = CropImage.getActivityResult(data);

            if (resultCode == RESULT_OK) {


                mProgressDialog = new ProgressDialog(getContext());
                mProgressDialog.setTitle("Uploading Image...");
                mProgressDialog.setMessage("Please wait while we upload and process the image.");
                mProgressDialog.setCanceledOnTouchOutside(false);
                mProgressDialog.show();


                Uri resultUri = result.getUri();

                File thumb_filePath = new File(resultUri.getPath());

                String current_user_id = mCurrentUser.getUid();


                Bitmap thumb_bitmap = new Compressor(getContext())
                        .setMaxWidth(200)
                        .setMaxHeight(200)
                        .setQuality(75)
                        .compressToBitmap(thumb_filePath);

                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                thumb_bitmap.compress(Bitmap.CompressFormat.JPEG, 100, baos);
                final byte[] thumb_byte = baos.toByteArray();


                StorageReference filepath = mImageStorage.child("profile_images").child(current_user_id + 
              ".jpg");
                final StorageReference thumb_filepath = 
               mImageStorage.child("profile_images").child("thumbs").child(current_user_id + ".jpg");



                filepath.putFile(resultUri).addOnCompleteListener(new 
              OnCompleteListener<UploadTask.TaskSnapshot>() {
                    @Override
                    public void onComplete(@NonNull Task<UploadTask.TaskSnapshot> task) {

                        if(task.isSuccessful()){

                            final String download_url = task.getResult().getDownloadUrl().toString();

                            UploadTask uploadTask = thumb_filepath.putBytes(thumb_byte);
                            uploadTask.addOnCompleteListener(new 
               OnCompleteListener<UploadTask.TaskSnapshot>() {
                                @Override
                                public void onComplete(@NonNull Task<UploadTask.TaskSnapshot> thumb_task) {

                                    String thumb_downloadUrl = thumb_task.getResult().getDownloadUrl().toString();

                                    if(thumb_task.isSuccessful()){

                                        Map update_hashMap = new HashMap();
                                        update_hashMap.put("image", download_url);
                                        update_hashMap.put("thumb_image", thumb_downloadUrl);

                                        mUserDatabase.updateChildren(update_hashMap).addOnCompleteListener(new 
         OnCompleteListener<Void>() {
                                            @Override
                                            public void onComplete(@NonNull Task<Void> task) {

                                                if(task.isSuccessful()){

                                                    mProgressDialog.dismiss();
                                                    Toast.makeText(getContext(), "Success Uploading.", 
          Toast.LENGTH_LONG).show();

                                                }

                                            }
                                        });


                                    } else {

                                        Toast.makeText(getContext(), "Error in uploading thumbnail.", 
         Toast.LENGTH_LONG).show();
                                        mProgressDialog.dismiss();

                                    }


                                }
                            });



                        } else {

                            Toast.makeText(getContext(), "Error in uploading.", Toast.LENGTH_LONG).show();
                            mProgressDialog.dismiss();

                        }

                    }
                });



            } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {

                Exception error = result.getError();

             }
         }
 

       }


My gallery intent is opening but when i crop the image its getting closed and i am back to the change Image Fragment. 
also in my logcat it is showing E/AndroidRuntime: FATAL EXCEPTION: main Process: com.example.jimmy.chatapplication, PID: 4315 java.lang.StackOverflowError error

**Comment by helpmeplz0219** [comment]
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if(requestCode == pick_image_request && resultCode == RESULT_OK && data != null && data.getData() != null){
            imageUri = data.getData();
            CropImage.activity(imageUri).setAspectRatio(1,1).start(getContext(), this);
           // Toast.makeText(getActivity(), imageUri, Toast.LENGTH_LONG).show();

        }
//this returns the else statement i dont know why. It's not saving in the firebase storage
        if(requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE){

            CropImage.ActivityResult result = CropImage.getActivityResult(data);

            if(resultCode == RESULT_OK){

                Uri resultUri = result.getUri();

                StorageReference filePath = ImageStorage.child("Image_Uploads").child("profile_image.jpg");

                filePath.putFile(resultUri).addOnCompleteListener(new OnCompleteListener<UploadTask.TaskSnapshot>() {
                    @Override
                    public void onComplete(@NonNull Task<UploadTask.TaskSnapshot> task) {
                        if(task.isSuccessful()){
                            Toast.makeText(getActivity(), "Hehez", Toast.LENGTH_LONG ).show();
                        }else{
                            Toast.makeText(getActivity(), "not working", Toast.LENGTH_LONG).show();
                        }
                    }
                });

            }else if(resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE){
                Exception  error = result.getError();
            }

        }else
            Toast.makeText(getActivity(), "tite di gumagana", Toast.LENGTH_LONG).show();

**Comment by nikol0900** [comment]
> you started the activity using `.start(getActivity());` this way the result will only return in the activity, not in the fragment.
> If you use appcompat fragment (recomended) you can call `.start(getContext(), this)` otherwise you need to call `.getIntent(getContext())` and then use this intent to start the activity from your fragment.

Thank you. Problem solved <3

**Comment by gamalragab21** [comment]
after selected image and show in cropped the button of crop not app !
in fragment not apper but in activity apper

**Comment by jestag4** [comment]
package com.example.image2text;

import android.Manifest;
import android.content.ContentValues;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.drawable.BitmapDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.util.SparseArray;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.ActionBar;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;

import com.google.android.gms.vision.Frame;
import com.google.android.gms.vision.text.TextBlock;
import com.google.android.gms.vision.text.TextRecognizer;
import com.theartofdev.edmodo.cropper.CropImage;
import com.theartofdev.edmodo.cropper.CropImageView;

public class MainActivity extends AppCompatActivity {

    EditText mResultEt;
    ImageView mPreview;

    private static final int CAMERA_REQUEST_CODE = 200;
    private static final int STORAGE_REQUEST_CODE = 400;
    private static final int IMAGE_PICK_GALLERY_CODE = 1000;
    private static final int IMAGE_PICK_CAMERA_CODE = 1001;

    String[] cameraPermission;
    String[] storagePermission;

    Uri image_Uri;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ActionBar actionBar = getSupportActionBar();
        actionBar.setSubtitle("Click + button to scan Image");

        mResultEt = findViewById(R.id.resultEt);
        mPreview = findViewById(R.id.imageIv);

        //camera permission
        cameraPermission = new String[]{Manifest.permission.CAMERA,
    Manifest.permission.WRITE_EXTERNAL_STORAGE};
        storagePermission = new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE};
    }
//action bar
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
        int id = item.getItemId();
        if (id == R.id.addImage){
            showImageImportDialog();
        }
        if (id == R.id.settings){
            Toast.makeText(this, "Settings", Toast.LENGTH_SHORT).show();
        }
        return super.onOptionsItemSelected(item);
    }

    private void showImageImportDialog() {
        //display
        String[] items = {"Camera", "Gallery"};
        AlertDialog.Builder dialog = new AlertDialog.Builder(this);
        //title
        dialog.setTitle("Select Image");
        dialog.setItems(items, (dialog1, which) -> {
            if (which == 0){
                //camera option
                if (!checkCameraPermission()){
                    requestCameraPermissions();
                }
                else {
                    //permission allowed
                    pickCamera();
                }
            }
            if (which == 1){
                //gallery option
                if (!checkStoragePermission()){
                    requestStoragePermissions();
                }
                else {
                    //permission allowed
                    pickGallery();
                }
            }

        });
        dialog.create().show(); //show dialog
    }

    private void pickGallery() {
        //pick image from gallery
        Intent intent = new Intent(Intent.ACTION_PICK);
        //set intent type
        intent.setType("image/*");
        startActivityForResult(intent, IMAGE_PICK_GALLERY_CODE);

    }

    private void pickCamera() {
        ContentValues values = new ContentValues();
        values.put(MediaStore.Images.Media.TITLE, "NewPic");
        values.put(MediaStore.Images.Media.DESCRIPTION, "Image To Text");
        image_Uri = getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);

        Intent cameraIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT, image_Uri);
        startActivityForResult(cameraIntent,IMAGE_PICK_CAMERA_CODE);

    }

    private void requestStoragePermissions() {
        ActivityCompat.requestPermissions(this,storagePermission, STORAGE_REQUEST_CODE );

    }

    private boolean checkStoragePermission(){
        boolean result = ContextCompat.checkSelfPermission(this,
                Manifest.permission.WRITE_EXTERNAL_STORAGE) == (PackageManager.PERMISSION_GRANTED);
        return result;
    }

    private void requestCameraPermissions() {
        ActivityCompat.requestPermissions(this,cameraPermission, CAMERA_REQUEST_CODE );
    }

    private boolean checkCameraPermission() {
        boolean result = ContextCompat.checkSelfPermission(this,
                Manifest.permission.CAMERA) == (PackageManager.PERMISSION_GRANTED);
        boolean result1 = ContextCompat.checkSelfPermission(this,
                Manifest.permission.WRITE_EXTERNAL_STORAGE) == (PackageManager.PERMISSION_GRANTED);
        return result && result1;
    }

    //handle permission result
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        switch (requestCode){
            case CAMERA_REQUEST_CODE:
                if (grantResults.length>0){
                    boolean cameraAccepted = grantResults[0] ==
                            PackageManager.PERMISSION_GRANTED;
                    boolean writeStorageAccepted = grantResults[0] ==
                            PackageManager.PERMISSION_GRANTED;
                    if (cameraAccepted && writeStorageAccepted){
                        pickCamera();
                    }
                    else {
                        Toast.makeText(this, "permission denied", Toast.LENGTH_SHORT).show();
                    }
                }
                break;

            case STORAGE_REQUEST_CODE:
                if (grantResults.length>0){
                    boolean writeStorageAccepted = grantResults[0] ==
                            PackageManager.PERMISSION_GRANTED;
                    if (writeStorageAccepted){
                        pickGallery();
                    }
                    else {
                        Toast.makeText(this, "permission denied", Toast.LENGTH_SHORT).show();
                    }
                }
                break;
        }
    }

    //handle image result
    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == RESULT_OK) {
            if (requestCode == IMAGE_PICK_GALLERY_CODE) {
                //got image from gallery
                Uri image_Uri = data.getData();
                CropImage.activity(image_Uri)
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setAspectRatio(1, 1)
                        .start(this);
             }
            if (requestCode == IMAGE_PICK_CAMERA_CODE) {
                //got image from camera
                CropImage.activity(image_Uri)
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setAspectRatio(1, 1)
                        .start(this);
            }
        }
        //get cropped image
        if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            if (resultCode == RESULT_OK) {
                Uri resultUri = result.getUri();
                mPreview.setImageURI(resultUri);

                //get drawable bitmap
                BitmapDrawable bitmapDrawable = (BitmapDrawable) mPreview.getDrawable();
                Bitmap bitmap = bitmapDrawable.getBitmap();
                TextRecognizer recognizer = new TextRecognizer.Builder(getApplicationContext()).build();

                if (!recognizer.isOperational()) {
                    Toast.makeText(this, "Error", Toast.LENGTH_SHORT).show();
                } else {
                    Frame frame = new Frame.Builder().setBitmap(bitmap).build();
                    SparseArray<TextBlock> items = recognizer.detect(frame);
                    StringBuilder sb = new StringBuilder();
                    //get text from sb
                    for (int i = 0; i < items.size(); i++) {
                        TextBlock myItem = items.valueAt(i);
                        sb.append(myItem.getValue());
                        sb.append("\n");
                    }
                    //set text to edit text
                    mResultEt.setText(sb.toString());
                }
            } else if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
                //if there is any error show it
                Exception error = result.getError();
                Toast.makeText(this, "" + error, Toast.LENGTH_SHORT).show();
            }
        }
    }

}
// I am not able to crop the image after selecting....then the app return to back to home page.... I heed help

**Comment by Pro-Cyborg** [comment]
I am using the cropper to crop an image. It has always worked well. But now when i am trying to call the crop method from a fragment it shows error. I used getContext() as mentioned in the Github Project Readme. Now please tell me how t get it working in fragments.
![screenshot](https://user-images.githubusercontent.com/62828604/115556998-e2fb1300-a2ce-11eb-9168-a53028d5d5bc.png)
