### ISSUE TITLE
Fatal Exception, when clicked crop during progress

### ISSUE THREAD

**Issue by athese6** [ArthurHub/Android-Image-Cropper#77]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
 Raw
com.theartofdev.edmodo.cropper.CropImageView.startCropWorkerTask (CropImageView.java:923)
com.theartofdev.edmodo.cropper.CropImageView.saveCroppedImageAsync (CropImageView.java:648)
com.theartofdev.edmodo.cropper.CropImageActivity.cropImage (CropImageActivity.java:164)
com.theartofdev.edmodo.cropper.CropImageActivity.onOptionsItemSelected (CropImageActivity.java:115)

**Comment by ArthurHub** [comment]
yep, was fixed in 2.1.4.
