### ISSUE TITLE
Android 10, black screen when image loaded

### ISSUE THREAD

**Issue by kokenkaan** [ArthurHub/Android-Image-Cropper#787]
Hi, I am using Xiaomi Mi 9T (MIUI Global 12.0.3, api 29). I created a custom activity for my project and I added the cropImageView view to my XML file. When I pick an image from the gallery, it shows nothing. It only shows a black screen. However, on the emulator (api 30), it shows the image.

**Comment by shubhamnandanwar** [comment]
Hey @kokenkaan, did you found any solution for this issue?
