### ISSUE TITLE
Disable/hide guides?

### ISSUE THREAD

**Issue by sethgho** [ArthurHub/Android-Image-Cropper#8]
When using the CropImageView for a shared element transition, the guidelines will show during the transition. It would be nice to work around that somehow.

Idea: Add enableCropping/disableCropping methods to the view. Disabling will hide the guidelines, enabling will return them. Is there any reason not to add something like this?

**Comment by ArthurHub** [comment]
what about CropImageView.setGuidelines()?

**Comment by ArthurHub** [comment]
Added `showCropOverlay` in **1.2.0** that hides all the crop window UI
