### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by PGMacDesign** [ArthurHub/Android-Image-Cropper#80]
Hello, I am getting an inflate exception when I try to use the library. 

Here is the logcat: 
https://gist.github.com/PGMacDesign/2c107fe99ad37c805da4047bea08f9c6

Here is what I am using to call it:
                //CropImage
                CropImage.activity(uri)
                        .setGuidelines(CropImageView.Guidelines.ON)
                        .setCropShape(CropImageView.CropShape.OVAL)
                        .start(activityPassed); //Passed from the mainactivity into this utilities method

Any ideas what is going on?

-Pgmac

**Comment by ArthurHub** [comment]
looks like [PhotoView](https://github.com/chrisbanes/PhotoView) library issue.
it has `PhotoViewAttacher` that uses `ViewTreeObserver.OnGlobalLayoutListener` probably affecting all ImageView's.

**Comment by PGMacDesign** [comment]
Gotcha, does this library (the cropper) use that one as a dependency? If so, is it a forked version? Or their current one? Thanks!

**Comment by ArthurHub** [comment]
No, the cropper only dependency is Android support library. 
Your app has dependency on this library, and this library uses a mechanism that allows it to meddle with all ImageView's, including the one used by my library. 
It is quite rare to do this so I assume they have a way to exclude code from it, see their documentation.

**Comment by PGMacDesign** [comment]
Ah I see. That explains the issue then. Thank you very much for your time!

**Comment by swativishnoi** [comment]
hey 
I am getting an inflate exception when I use ( compile 'com.theartofdev.edmodo:android-image-cropper:2.2.+')  run my app in android version 4.1 or 4.2 only , in other android devices run perfectly .
can some one please explain why ?
