### ISSUE TITLE
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 15132368)

### ISSUE THREAD

**Issue by gustavomc** [ArthurHub/Android-Image-Cropper#82]
i appears in logcat when take a photo or open a previus taken photo with my nexus 5 device

**Comment by ArthurHub** [comment]
Can you reproduce it in the library sample app?
What did you use to pick image? Did you use the library built in chooser?
When does it happens related to the code in onActivityResult?
