### ISSUE TITLE
not working properly functions of this library not defines even and after adding requirements

### ISSUE THREAD

**Issue by saurav12bisht** [ArthurHub/Android-Image-Cropper#845]
this is showing error (Class referenced in the manifest, com.theartofdev.edmodo.cropper.CropImageActivity, was not found in the project or the libraries)
<activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
           />

  Depedency is also added but it showing  
1 -Cannot resolve symbol 'CropImageView' 
2- Cannot resolve symbol 'CropImage'

depedency i added--
 implementation 'com.theartofdev.edmodo:android-image-cropper:2.8.0'

**Comment by Canato** [comment]
🚨🚨🚨🚨🚨 THIS LIBRARY IS NOT MAINTAINED, PLEASE READ THIS 🚨🚨🚨🚨🚨 #838

To avoid your issues, please use the latest updated library: https://github.com/CanHub/Android-Image-Cropper

100% kotlin
All bugs fixes
active community
34k downloads per month

**Comment by saurav12bisht** [comment]
implementation 'com.github.dhaval2404:imagepicker:2.1' 
this library is working use this
