### ISSUE TITLE
CropImage activity blue screen

### ISSUE THREAD

**Issue by trramsiq** [ArthurHub/Android-Image-Cropper#85]
Hi,

I'm picking an image and passing it to the crop activity. 
But the image is not showing in it.
If I resize it and press crop the cropped image is returned correctly

CropImage.activity(path)
                    .setMinCropResultSize(400, 300)
                    .setMaxCropResultSize(4000, 3000)
                    .setAspectRatio(3,4)
                    .setFixAspectRatio(true)
                    .setGuidelines(CropImageView.Guidelines.ON)
                    .start(getActivity());

Any what I'm doing wrong?

**Comment by ArthurHub** [comment]
blue screen?
error in logcat?
how do you crop it if it doesn't show?
what is the size of the image?

**Comment by trramsiq** [comment]
Yes. I found the error! Some of my styling was causing the error.
Sorry!

**Comment by trramsiq** [comment]
This line was making the whole view blue
<item name="android:background">@color/background_blue1</item>

How can I change the action bar on the crop tool?

**Comment by ArthurHub** [comment]
https://www.google.co.il/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=android%20how%20to%20change%20toolbar%20color%20using%20theme
