### ISSUE TITLE
Crop square

### ISSUE THREAD

**Issue by burnix** [ArthurHub/Android-Image-Cropper#86]
Is there any way to allow  using  only  foursquare for crop, instead of rectangle?

**Comment by ArthurHub** [comment]
hmm... what?

**Comment by burnix** [comment]
OK:))) So when I start CropActivity I can see a photo and rectangle. According  to the height, width and its place on the photo I can crop the one to  get  cropped pic. So  is there  any way  to  make  this  `croping rectangle`  has equal width and height (square)

**Comment by ArthurHub** [comment]
Yes, see [Visual Customization](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Visual-Customization#aspectratioxy): AspectRatioX/Y and FixAspectRatio.

**Comment by ArthurHub** [comment]
Sorry to point it out but it is also in the [FAQ](https://github.com/ArthurHub/Android-Image-Cropper/wiki/FAQ).
