### ISSUE TITLE
Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by abhikashbabu** [ArthurHub/Android-Image-Cropper#869]
Could not GET 'https://giphy.bintray.com/giphy-sdk/com/theartofdev/edmodo/android-image-cropper/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
Disable Gradle 'offline mode' and sync project

**Comment by Canato** [comment]
please read https://github.com/ArthurHub/Android-Image-Cropper/issues/858 

And update to the new repository

**Comment by abhikashbabu** [comment]
thank you
