### ISSUE TITLE
Unable to find cropped Image on device

### ISSUE THREAD

**Issue by chandrahasan** [ArthurHub/Android-Image-Cropper#87]
Hi , **Thanks for your beautiful library** 

I have some quires,
1. If I load Image through Camera for cropping ,Will that camera taken full image stored on device ?
2. Once crop option clicked  , Will Cropped Image stored on device ?

If not then , kindly advice some solution to save both Camera taken image and Cropped Image from using your library . 

I seen `WRITE_EXTERNAL_STORAGE` in your sample manifest but unable to find cropped image on device.

Thanks in Advance , Awaiting for your reply :)

**Comment by ArthurHub** [comment]
1. The location of the camera captured image is controlled by the intent creator, you can see the URI I have used in `CropImage.getCaptureImageOutputUri` method.
2. Assuming you use the built-in activity you can control the output path of the cropped image using `.setOutputUri` method of the builder.

So you can control where to save the camera/cropped image or copy them from the default location.

The `WRITE_EXTERNAL_STORAGE` permissions are not used, it was left from a test I did a while back.

**Comment by chandrahasan** [comment]
Hi , Thanks for your reply 

I dont know how to use `.setOutputUri`  to set Cropped image path on `handleCropResult` method or before click Crop option  . can you pls help me with some **sample code**.

**Comment by ArthurHub** [comment]
```java
Uri myUri = Uri.fromFile(new File(getExternalCacheDir(), "image.jpeg"));
CropImage.activity(imageUri)
    .setOutputUri(myUri)
    .start(this);
```

**Comment by chandrahasan** [comment]
I used saveCroppedImageAsync to save cropped image , Is it right approach ?

```
 if (item.getItemId() == R.id.main_action_crop) {

//         mCropImageView.getCroppedImageAsync();
    
            Uri myUri = Uri.fromFile(new File(getActivity().getExternalCacheDir(), "image.jpeg"));
            mCropImageView.saveCroppedImageAsync(myUri);

            return true;
        } 
```

**Comment by ArthurHub** [comment]
What is the problem then?

**Comment by chandrahasan** [comment]
Hi Arthur, Thanks for your reply 
 
Through `saveCroppedImageAsync(myUri); ` option I successfully changed cropped image save path , Same like **I want to change Camara capchured image path**. 

By default its storing on **AppName/cache/pickImageResult.jpeg**  , I want to change this to external path & name , Kindly advise the solution.

Thanks in Advance.
