### ISSUE TITLE
OutOfMemoryError :(

### ISSUE THREAD

**Issue by grestuccia1** [ArthurHub/Android-Image-Cropper#88]
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:640)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:586)
       at com.theartofdev.edmodo.cropper.BitmapUtils.rotateBitmapInt(BitmapUtils.java:433)
       at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:187)
       at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:176)
       at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:25)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)

**Comment by ArthurHub** [comment]
Unfortunately it can always happen due to limitations in Android API.
If your scenario allows lowering the cropped image resolution you can limit the maximum size of the cropped image using reqWidth/reqHeight parameters that will result in loading sampled image.
Depending on you scenario there may be other options like cropping on the server or using native API.

**Comment by ArthurHub** [comment]
On second thought, the library should handle this scenario more gracefully.
In the next version, after finishing non-straight angle rotation, I will add optional sampling fallback if OOM occurs during cropping giving you the option the receive lowered cropped image instead on an error.

**Comment by grestuccia1** [comment]
Good Thank you, nice library!

**Comment by TigranSarkisian** [comment]
Same problem - OutOfMemoryError in method

```
    private static Bitmap rotateBitmapInt(Bitmap bitmap, int degrees) {
        if (degrees > 0) {
            Matrix matrix = new Matrix();
            matrix.setRotate(degrees);
            Bitmap newBitmap = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, false);
            if (newBitmap != bitmap) {
                bitmap.recycle();
            }
            return newBitmap;
        } else {
            return bitmap;
        }
    }

```
line 

`Bitmap newBitmap = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, false);
`

**Comment by ssahilsahil798** [comment]
same problem. i tried compressing the image before sending it to CropImage activity, that does not help.
But when i change largeHeap = true, it is resolved but activity transition turns black for few seconds. I think features were best in this library but i am onto alternatives because i can't compromise on performance.

**Comment by TigranSarkisian** [comment]
Was struggling with it all day, fixed all significant memory leaks in app not to provocate OOM) Unfortunately  OutOfMemoryError in Bitmap.createBitmap() appears anyway after several times cropping large images (more than 2mb).  Ssahilsahil798 compressing image before sending to cropper - i do not know, it's extra job and resources.

**Comment by ArthurHub** [comment]
Android Bitmap object holds the raw image data in memory: 4 bytes per pixels.
Compression or encoding is irrelevant.
My advice is to limit the size of the cropped image using reqWidth/reqHeight parameters, if this is acceptable.

@ssahilsahil798 what alternatives can handle large images without lowering the resolution?

**Comment by ssahilsahil798** [comment]
@ArthurHub - Thanks for replying so quickly. I read about bitmaps. And you exactly pointed out what i was doing wrong. Since the library is working perfectly for gallery images i think it will work with camera too and without even requesting for largeHeap. Thanks a lot.

**Comment by ssahilsahil798** [comment]
@ArthurHub - I scaled down the bitmap before sending it to CropImage activity and IT WORKED. thanks a lot man.

**Comment by ArthurHub** [comment]
Well, yes, you can just scale down the image before cropping and it will work.
But the library has more powerful feature to handle this: requested size.
By setting the requested size to 500,500 the cropped image will be scaled down IF required.
So if the selected cropped image is 800x400 then no scaling down is required, the cropped image is small enough so you don't loose any quality.
But if the selected cropped image is 1600x1200 then the library will automatically scale it to 800x600.

```java
CropImage.activity(imageUri)
    .setRequestedSize(500, 500)
    .start(this);
```

**Comment by dsdebastiani** [comment]
Couldn't use ```setAspectRatio``` and ```setRequestedSize``` in same request, why?

I'm trying...
``` 
CropImage.activity(imageUri)
    .setAspectRatio(1,1)
    .setRequestedSize(500, 500)
    .start(this);
```
But the crop activity lost configurations and doesn't apply aspect ratio.

**Comment by anhvt52** [comment]
The problem is method BitmapUtils.calculateInSampleSizeByReqestedSize
`private static int calculateInSampleSizeByReqestedSize(int width, int height, int reqWidth, int reqHeight) {
        int inSampleSize = 1;
        if (height > reqHeight || width > reqWidth) {
            while ((height / 2 / inSampleSize) > reqHeight && (width / 2 / inSampleSize) > reqWidth) {
                inSampleSize *= 2;
            }
        }
        return inSampleSize;
    }`

[http://stackoverflow.com/questions/13696166/android-calculateinsamplesize-why-does-math-round-deal-with-height-height](url)

For fixing temporary this, I think we should decrease reqWidth and reqHeight 2 times

**Comment by ArthurHub** [comment]
finally done, see **v2.3.0**
If OOM error occur the library will use sampling to lower the size of the cropped image automatically.
The crop result object will contains the sample size used so you can know if it happened.
