### ISSUE TITLE
Edge Crop Guideline

### ISSUE THREAD

**Issue by TheFinestArtist** [ArthurHub/Android-Image-Cropper#9]
![screenshot_2015-05-17-19-01-15](https://cloud.githubusercontent.com/assets/3123741/7669931/42a66f2a-fcc7-11e4-865b-be873175c495.png)
![screenshot_2015-05-17-19-01-22](https://cloud.githubusercontent.com/assets/3123741/7669933/47db2aee-fcc7-11e4-8791-9a81a34abf0e.png)

As you can see, the guideline of the original cropper automatically fit to the end of the edge. Somehow this feature has been removed in Android-Image-Cropper which I love to use.

**Comment by TheFinestArtist** [comment]
You can either move the grey line between the corner to the edge so that the grey line always at the end of the image or fix some removed features!!

**Comment by ArthurHub** [comment]
you are right, fixed it in (1.0.5)
