### ISSUE TITLE
Image size enlarges after cropping  

### ISSUE THREAD

**Issue by TigranSarkisian** [ArthurHub/Android-Image-Cropper#91]
input: 200кb
output >2mb

Everything works good,thanks a lot! But cropper significantly enlarge image size, after crop in onGetCroppedImageComplete we receive bitmap with enlarge size, yes certainly we can compress it later,  but is there any possibility to prevent this?

thanks in advance!

**Comment by ArthurHub** [comment]
How do you measure the size of the input and output images?

**Comment by TigranSarkisian** [comment]
I apologize for my late response! Yes I do, I measure the size of the input image, then after cropping in onGetCroppedImageComplete I got bitmap and can easily measure its size in debug (I also save it on sd card without any compression and can see it size)!

**Comment by ArthurHub** [comment]
When image decoded, Android uses 4 bytes per pixel so the memory usage is always much larger than the size of the encoded image on disk (in gallery).
I assume that is what you see.
Compare the same encoding format, so if your original image is png, save the cropped image as png.

**Comment by TigranSarkisian** [comment]
Ok, I will try and then inform you! Thanks)
