### ISSUE TITLE
Repeated RotateImage() calls zooms the image

### ISSUE THREAD

**Issue by trramsiq** [ArthurHub/Android-Image-Cropper#92]
I'm using CropImageView in Fragment.

calling cropImageView.rotateImage(90) multiple times zooms the image and CropRect gets smaller.

Fragment is setup as follows
        cropImageView.setImageUriAsync(imageUri);
        cropImageView.setAspectRatio(3, 4);
        cropImageView.setMinimumHeight(400);
        cropImageView.setFixedAspectRatio(true);
        cropImageView.setGuidelines(CropImageView.Guidelines.ON);
        cropImageView.setOnGetCroppedImageCompleteListener(resultDelegate);

**Comment by ArthurHub** [comment]
Shit, will fix shortly, thx.

**Comment by ArthurHub** [comment]
fixed in **2.2.2**
