### ISSUE TITLE
Problem with using in Fragment

### ISSUE THREAD

**Issue by burnix** [ArthurHub/Android-Image-Cropper#93]
`public class SettingsFragment extends android.app.Fragment`

    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        System.out.println("code = " + requestCode);
        if (resultCode == Activity.RESULT_OK) {
            if (requestCode == SELECT_PICTURE) {
                Uri selectedImageUri = data.getData();
                if (null != selectedImageUri) {
                    CropImage.activity(selectedImageUri)
                            .setGuidelines(CropImageView.Guidelines.ON)
                            .setFixAspectRatio(true)
                            .start(getActivity(), SettingsFragment.class);
                }
            }
        }
        if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
            System.out.println("CROP_IMAGE_ACTIVITY_REQUEST_CODE");
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            if (resultCode == Activity.RESULT_OK) {
                Uri resultUri = result.getUri();
                System.out.println("result uri = " + resultUri.toString());
                try {
                    newPhoto = MediaStore.Images.Media.getBitmap(getActivity().getContentResolver(), resultUri);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                photo.setImageBitmap(Utils.getCircularBitmap(newPhoto));
            } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                Exception error = result.getError();
            }
        }
    }

I can't  get ImageUri. Please help. I've read related  topic, but it didn't help me.

**Comment by ArthurHub** [comment]
The  problem is with this line:
```java
.start(getActivity(), SettingsFragment.class);
```
Have you read ["Using built in CropImageActivity"](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Using-built-in-CropImageActivity) wiki page?

**Comment by burnix** [comment]
Yes, I have. But I don't understand complitely, maybe because for the lack of English. 

if (resultCode == Activity.RESULT_OK) {
            if (requestCode == SELECT_PICTURE) {
                Uri selectedImageUri = data.getData();
                if (null != selectedImageUri) {
                    Intent intent = CropImage.activity(selectedImageUri)
                            .setGuidelines(CropImageView.Guidelines.ON)
                            .setFixAspectRatio(true)
                            .getIntent(getActivity());
                    startActivityForResult(intent, CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE);
                }
            }
        }

I tried to make these changes and this helped. Thank you.

**Comment by Mpendxlo** [comment]
Great solution @burnix !
