### ISSUE TITLE
Blur image due to Quality reduced by cropper

### ISSUE THREAD

**Issue by pankajkrdos** [ArthurHub/Android-Image-Cropper#98]
I am using this library, so when I select any image from gallery to crop the picture quality is reduced by the cropper. How can I force cropper to remain the image quality of the cropped image compared to the original image so that it will not become blur.

**Comment by ArthurHub** [comment]
Currently I don't expose an option to control it.
Note that the image is sampled only for the cropping UI, the resulting cropped image is NOT sampled. 
Loading full image is not a good idea, especially for mid-low end devices. 
Why is this an issue for you?

**Comment by pankajkrdos** [comment]
Thanks for your support,

I have a requirement to crop document images, retaining quality. But when the cropper starts, it reduces the quality before cropping and even I am not able to read the texts in the documents after cropping as all becomes blur. Please help me on this.
 Thanks.

**Comment by ArthurHub** [comment]
Do you mean you can't read the text during cropping or in the resulting cropped image?
Can you upload a sample image?

**Comment by pankajkrdos** [comment]
Hello Arthur,
Thanks for quick reply.
I have attached the screen shots when clicking a photo and when starting the cropper to crop the same image.
Please provide me a feasible solution if possible in a quick succession.
![screenshot_20160617-151131](https://cloud.githubusercontent.com/assets/13745450/16147059/cb68bde4-349e-11e6-90b9-8451b33ce5fa.png)
![screenshot_20160617-151144](https://cloud.githubusercontent.com/assets/13745450/16147060/cb68ed5a-349e-11e6-94d3-535b91eecfdf.png)

Thanks in advance.

**Comment by ArthurHub** [comment]
That is way too much blur, how do you load the image for cropping?
Can you use the sample app and see how it works there?

**Comment by pankajkrdos** [comment]
I am passing the uri sent back by the Android Framework when clicked using camera using this code to launch your cropper
com.theartofdev.edmodo.cropper.CropImage.activity ( imageUri )
                .setGuidelines( CropImageView.Guidelines.ON)
                .setActivityMenuIconColor ( Color.WHITE )
                .setActivityTitle ( "" )
                .setOutputCompressFormat ( Bitmap.CompressFormat.PNG )
                .setAutoZoomEnabled ( true )
                .setAllowRotation ( false )
                .setCropShape ( CropImageView.CropShape.RECTANGLE )
                .setFixAspectRatio ( isToSetAspectRatio ? true : false )
                .setAspectRatio (  1,1 )
                .start ( activity );

**Comment by ArthurHub** [comment]
looks good...
how do you use the camera intent? and how do you get the uri? 
It's possible that you get the thumbnail instead of the full image.

**Comment by pankajkrdos** [comment]
For gallery ->

Intent intent = new Intent();
            intent.setType("image/*");
            intent.setAction(Intent.ACTION_GET_CONTENT);
            intent.putExtra(Intent.EXTRA_LOCAL_ONLY, true);
            requestCode = Constants.PICK_IMG_FROM_GALLERY_REQUEST;

For Camera ->
Intent intent = new Intent ( MediaStore.ACTION_IMAGE_CAPTURE );
            callingActivity.startActivityForResult ( intent, Constants.PICK_IMG_FROM_CAMERA_REQUEST);

**Comment by pankajkrdos** [comment]
For gallery
String imagePath = Util.handleGalleryResult ( DashboardContainerActivity.this, data );
                                            Uri uri = Uri.fromFile ( new File ( imagePath ) );

For Camera
String galleryPath = Util.saveClickedImage ( DashboardContainerActivity.this, data );
                                        String imagePath = Util.getPath ( DashboardContainerActivity.this, Uri.parse ( galleryPath ) );
                                        Uri uri = Uri.fromFile(new File (imagePath));
                                        Util.startCropping ( DashboardContainerActivity.this, true, uri );

**Comment by ArthurHub** [comment]
for camera you need to provide the uri to save the captured image to.
to make sure you get the full image try setting the uri you receive to a test image view.
also please see if the sample app in the library works properly, I want to make sure the issue is not in the library.

**Comment by pankajkrdos** [comment]
Yeah,
Might be an issue while saving the clicked image in the gallery since current code is creating thumbnail first and getting it again for cropping. So this is the issue as far as I know.

Can you suggest me how to include the captured image with higher quality and then include it into the gallery and then finally getting the path of that image.

**Comment by ArthurHub** [comment]
Not sure how to save an image into gallery but you don't have to. 
To get the full image uri you need to set `EXTRA_OUTPUT` on the camera intent:
```
Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
Uri outputFileUri = Uri.fromFile(new File(context.getExternalCacheDir().getPath(), "pickImageResult.jpeg"));
intent.putExtra(MediaStore.EXTRA_OUTPUT, outputFileUri);
```
and then this uri will contain the image captured by camera.
you may also use the code in the library, see ["Pick image for cropping from Camera or Gallery"](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Pick-image-for-cropping-from-Camera-or-Gallery)

**Comment by pankajkrdos** [comment]
Hello Arthur,

Finally I achieved the feat.
Hats off to the work done by you.
Thank you.
